const slides = [
  { title: "Ingeniería del Software I", eyebrow: "Clase 1 · Unidad I", lead: "¿Qué debe ser cierto para que una casa de cambio digital sea confiable?", body: `<div class="callout"><strong>Pregunta disparadora</strong><p>Global Exchange no es sólo una pantalla: es un sistema que coordina personas, reglas, datos, decisiones y responsabilidades.</p></div>`, visual: `<div class="visual-title">Caso conductor</div><div class="card"><span class="kicker">Enunciado inicial</span><h3>Global Exchange</h3><p>Consultar tasas, simular, comprar y vender divisas, recibir fondos y administrar roles.</p><span class="tag warn">No es una especificación completa</span></div>`, note: "Abrir con la pregunta y pedir una respuesta rápida: qué podría salir mal si sólo pensamos en código." },
  { title: "La ruta de la clase", eyebrow: "Mapa de aprendizaje", lead: "Vamos a pasar de la disciplina al primer inventario de requisitos.", body: `<div class="cards"><div class="card"><span class="number">01</span><h3>Disciplina</h3><p>Producto, calidad y proceso.</p></div><div class="card"><span class="number">02</span><h3>Decisiones</h3><p>Modelos, adaptación y ética.</p></div><div class="card"><span class="number">03</span><h3>Caso</h3><p>Actores, riesgos y trazabilidad.</p></div><div class="card"><span class="number">04</span><h3>Evidencia</h3><p>Actividad y salida individual.</p></div></div>`, visual: `<div class="visual-title">Hoy producimos</div><ol class="compact"><li>Un mapa del sistema sociotécnico.</li><li>Una pregunta abierta por equipo.</li><li>Un requisito trazable individual.</li></ol><p class="source">Puente: T1 → T3</p>`, note: "Señalar que la clase tiene una salida observable: no es una lista de definiciones." },
  { title: "Más allá del código", eyebrow: "Por qué importa", lead: "La ingeniería reduce incertidumbre cuando el software afecta decisiones reales.", body: `<div class="cards"><div class="card"><h3>Personas</h3><p>Necesidades, permisos, expectativas y daños.</p></div><div class="card"><h3>Contexto</h3><p>Reglas del negocio, operación y regulación por validar.</p></div><div class="card"><h3>Evidencia</h3><p>Decisiones que pueden revisarse y verificarse.</p></div></div>`, visual: `<div class="visual-title">Una pregunta útil</div><h3>¿Cómo sabremos que funciona?</h3><p>Antes de construir, hacemos explícitos el resultado esperado, el escenario y la medida.</p><div class="callout"><strong>Calidad no es una impresión.</strong><p>Es una relación entre características y requisitos.</p></div>`, note: "Conectar con experiencias previas: una aplicación puede compilar y aun así fallar como producto." },
  { title: "El software es un producto", eyebrow: "Sistema completo", lead: "Código es una parte. El producto también debe poder operarse, entenderse y evolucionar.", body: `<div class="cards"><div class="card"><h3>Código</h3><p>Comportamiento implementado.</p></div><div class="card"><h3>Datos</h3><p>Información, estados y trazas.</p></div><div class="card"><h3>Documentación</h3><p>Decisiones, reglas y uso.</p></div><div class="card"><h3>Configuración</h3><p>Monedas, tasas, roles y entornos.</p></div><div class="card"><h3>Contexto</h3><p>Personas, servicios y operación.</p></div></div>`, visual: `<div class="visual-title">Global Exchange</div><div class="table-like"><div class="row"><strong>Operación</strong><span>Comprar o vender</span><span>Cliente asociado</span></div><div class="row"><strong>Soporte</strong><span>Pagos, correo, fondos</span><span>Por validar</span></div><div class="row"><strong>Control</strong><span>Roles y estados</span><span>Trazabilidad</span></div></div>`, note: "Usar el caso para mostrar que una decisión de configuración puede cambiar la operación y los riesgos." },
  { title: "Calidad: criterios verificables", eyebrow: "Una idea, tres preguntas", lead: "Un adjetivo como “seguro” o “rápido” no alcanza: hay que transformarlo en evidencia.", body: `<div class="cards"><div class="card"><h3>Requisito</h3><p>¿Qué debe hacer o preservar el sistema?</p></div><div class="card"><h3>Medida</h3><p>¿Con qué observable lo evaluamos?</p></div><div class="card"><h3>Escenario</h3><p>¿En qué condición y con qué resultado?</p></div></div><div class="callout"><strong>Ejemplo</strong><p>“Al confirmar una compra, el sistema muestra el estado de la operación y registra la tasa aplicada”.</p></div>`, visual: `<div class="visual-title">Evitar la ambigüedad</div><p><span class="tag warn">“rápido”</span> → tiempo máximo por escenario</p><p><span class="tag warn">“seguro”</span> → actor, permiso, rechazo y evidencia</p><p><span class="tag">“usable”</span> → tarea, usuario y criterio observable</p>`, note: "No fijar números que el enunciado no trae. Cuando falte una medida, registrar Por validar." },
  { title: "El proceso conecta decisiones", eyebrow: "Ciclo de vida", lead: "Requisitos, diseño, construcción, pruebas, despliegue y evolución se retroalimentan.", body: `<div class="timeline"><div><b>Requisitos</b><small>Necesidades y reglas</small></div><div><b>Diseño</b><small>Decisiones y modelos</small></div><div><b>Construcción</b><small>Producto ejecutable</small></div><div><b>Pruebas</b><small>Evidencia</small></div><div><b>Despliegue</b><small>Operación</small></div><div><b>Evolución</b><small>Cambio controlado</small></div></div><div class="callout"><strong>No es una receta única.</strong><p>El proceso se adapta al contexto y mantiene revisión.</p></div>`, visual: `<div class="visual-title">Secuencia de trabajo</div><div class="process"><span>Requisitos</span><i>→</i><span>Diseño</span><i>→</i><span>Construcción</span><i>→</i><span>Pruebas</span><i>→</i><span>Operación</span></div>`, note: "Diferenciar proceso de una lista rígida de fases. La visualización muestra relación, no obligatoriedad lineal." },
  { title: "Trazabilidad y revisión continua", eyebrow: "Vista del ciclo de vida", lead: "Cada decisión importante debe poder seguirse desde su fuente hasta una evidencia.", body: `<div class="cycle"><span>Requisito</span><span>Modelo</span><span>Prueba</span><span>Decisión</span></div>`, visual: `<div class="visual-title">Hilo de evidencia</div><p><strong>GE-RF-06</strong> Asociación usuario-cliente</p><p>→ caso de uso</p><p>→ selección de contexto</p><p>→ escenario permitido/denegado</p><p>→ revisión T3</p><span class="tag">Fuente: enunciado</span>`, note: "Mostrar que trazabilidad no significa burocracia: permite detectar contradicciones entre modelos y escenarios." },
  { title: "Modelos de proceso: comparar para aprender", eyebrow: "Opciones con trade-offs", lead: "El contexto decide qué combinación de previsibilidad, aprendizaje y adaptación conviene.", body: `<div class="cards"><div class="card"><h3>Cascada</h3><p>Orden y hitos claros. Riesgo: descubrir tarde errores de comprensión.</p></div><div class="card"><h3>Incremental</h3><p>Entrega por partes. Riesgo: integración y prioridades mal coordinadas.</p></div><div class="card"><h3>Prototipado</h3><p>Aprende sobre necesidades. Riesgo: confundir prototipo con producto.</p></div><div class="card"><h3>Ágil</h3><p>Feedback y adaptación. Riesgo: improvisar sin diseño, calidad ni acuerdos.</p></div></div>`, visual: `<div class="visual-title">Criterios para Global Exchange</div><ul class="compact"><li>Requisitos con incertidumbre.</li><li>Riesgo financiero y de autorización.</li><li>Revisión frecuente con evidencia.</li><li>Entrega incremental sin perder trazabilidad.</li></ul>`, note: "No presentar un modelo como ganador universal. Pedir una ventaja y un riesgo por alternativa." },
  { title: "Comparar para decidir", eyebrow: "Elección contextual", lead: "Una decisión de proceso es una hipótesis argumentada, no una preferencia personal.", body: `<div class="table-like"><div class="row"><strong>Contexto</strong><span>¿Qué cambia?</span><span>¿Qué exige?</span></div><div class="row"><strong>Pagos y fondos</strong><span>Daño potencial</span><span>Pruebas y controles</span></div><div class="row"><strong>Tasas variables</strong><span>Aprendizaje</span><span>Iteración y revisión</span></div><div class="row"><strong>Roles múltiples</strong><span>Autorización</span><span>Escenarios negativos</span></div></div>`, visual: `<div class="visual-title">Decisión mínima</div><p>“Elegimos una estrategia incremental con revisiones frecuentes porque necesitamos aprender del dominio y controlar riesgos de autorización.”</p><span class="tag">Supuesto explícito</span> <span class="tag warn">Riesgo registrado</span>`, note: "La clase no busca cerrar la decisión de proceso. Busca enseñar a justificarla y revisarla." },
  { title: "Agilidad es adaptación con disciplina", eyebrow: "Enfoques ágiles", lead: "Adaptar no significa abandonar documentación, diseño, pruebas ni responsabilidad.", body: `<div class="cards"><div class="card"><h3>Feedback</h3><p>Aprender temprano con personas y evidencia.</p></div><div class="card"><h3>Prioridad</h3><p>Entregar primero lo que más valor y riesgo concentra.</p></div><div class="card"><h3>Calidad</h3><p>Mantener criterios verificables en cada incremento.</p></div><div class="card"><h3>Transparencia</h3><p>Hacer visibles supuestos, cambios y pendientes.</p></div></div>`, visual: `<div class="visual-title">Ciclo de adaptación</div><div class="process"><span>Hipótesis</span><i>→</i><span>Incremento</span><i>→</i><span>Evidencia</span><i>→</i><span>Revisión</span><i>↺</i></div><div class="callout"><strong>Agilidad con trazabilidad.</strong><p>Cambiar no borra el motivo ni el impacto.</p></div>`, note: "Relacionar con el Manifiesto Ágil sin convertir sus valores en una receta de implementación." },
  { title: "Global Exchange: un sistema sociotécnico", eyebrow: "Caso conductor", lead: "El sistema conecta actores, reglas, servicios y decisiones con efectos fuera de la interfaz.", body: `<div class="actors"><div class="actor"><b>Usuario</b><small>Consulta o actúa en nombre de un cliente.</small></div><div class="actor"><b>Cliente</b><small>Persona física o jurídica.</small></div><div class="actor"><b>Administrador</b><small>Asocia usuarios y configura el sistema.</small></div><div class="actor"><b>Analista</b><small>Modifica tasas y monitorea ganancias.</small></div><div class="actor"><b>Proveedor de pagos</b><small>Resultado de una integración.</small></div><div class="actor"><b>Correo / fondos</b><small>Servicios externos por validar.</small></div></div>`, visual: `<div class="visual-title">Regla clave</div><div class="callout"><strong>Un usuario sin cliente sólo consulta.</strong><p>Si tiene más de un cliente, debe seleccionar el contexto antes de operar.</p></div><span class="tag warn">Autorización ≠ verificación de identidad</span>`, note: "Subrayar que los actores externos son parte del contexto, aunque el enunciado no complete sus contratos." },
  { title: "Leer el enunciado con método", eyebrow: "Del relato a la evidencia", lead: "Antes de modelar, separamos lo que está dicho, lo que suponemos y lo que necesitamos preguntar.", body: `<div class="cards"><div class="card"><h3>Hechos</h3><p>El usuario asociado puede comprar y vender; el no asociado sólo consulta.</p><span class="tag">Fuente: enunciado</span></div><div class="card"><h3>Supuestos</h3><p>Una posible forma de validar una operación o registrar una tasa.</p><span class="tag warn">Explicitar</span></div><div class="card"><h3>Preguntas abiertas</h3><p>¿Cómo se audita una reversión? ¿Qué retención aplica?</p><span class="tag warn">Por validar</span></div></div>`, visual: `<div class="visual-title">Regla de lectura</div><p><strong>No completar silenciosamente.</strong></p><p>Una especificación inicial gana calidad cuando muestra sus límites.</p>`, note: "Tomar una frase del enunciado y clasificarla en conjunto. Evitar convertir una interpretación docente en requisito del sistema." },
  { title: "Ética profesional: responsabilidad visible", eyebrow: "No es un apartado final", lead: "El juicio profesional protege el interés público cuando las decisiones tienen consecuencias.", body: `<div class="cards"><div class="card"><h3>Interés público</h3><p>Anticipar daños y evitar usos peligrosos.</p></div><div class="card"><h3>Juicio</h3><p>Comunicar límites, incertidumbre y conflictos.</p></div><div class="card"><h3>Confidencialidad</h3><p>Tratar la información con cuidado y propósito.</p></div><div class="card"><h3>Competencia y trato justo</h3><p>Reconocer límites y no discriminar decisiones o acceso.</p></div></div>`, visual: `<div class="visual-title">Pregunta ética</div><div class="callout"><strong>¿Quién puede resultar perjudicado?</strong><p>El análisis debe incluir personas usuarias, clientes, operadores y terceros.</p></div>`, note: "Usar los principios del código ACM/IEEE-CS como marco de discusión, no como lista para memorizar." },
  { title: "Privacidad y seguridad desde el inicio", eyebrow: "Riesgos del caso", lead: "Datos financieros, autorización y estados deben aparecer en requisitos y escenarios tempranos.", body: `<div class="cards"><div class="card"><h3>Datos</h3><p>Identidad, cuentas, operaciones e historial.</p></div><div class="card"><h3>Autorización</h3><p>Qué puede hacer cada actor y en qué contexto.</p></div><div class="card"><h3>Separación de roles</h3><p>Analista operativo no equivale a administrador.</p></div><div class="card"><h3>Daño potencial</h3><p>Operación indebida, exposición o pérdida.</p></div></div><div class="callout"><strong>Por validar</strong><p>Pagos, auditoría, reversión, regulación, disponibilidad y retención requieren decisiones explícitas.</p></div>`, visual: `<div class="visual-title">Escenario negativo</div><p>Un usuario sin cliente intenta comprar divisas.</p><p><span class="tag">Se rechaza</span> <span class="tag">Se informa sin exponer datos</span> <span class="tag warn">Se registra evidencia: por validar</span></p>`, note: "Aclarar que verificación de correo no otorga automáticamente permiso para operar." },
  { title: "SWEBOK hoy: guía, no receta", eyebrow: "Marco de conocimiento", lead: "SWEBOK ayuda a organizar conocimiento generalmente aceptado; no prescribe un proceso ni reemplaza el juicio.", body: `<div class="cards"><div class="card"><h3>Guía</h3><p>Mapa de áreas y prácticas de ingeniería.</p></div><div class="card"><h3>No es norma</h3><p>No impone una implementación única.</p></div><div class="card"><h3>No es currículo</h3><p>No decide qué debe evaluar este curso.</p></div><div class="card"><h3>No es receta</h3><p>El contexto define cómo aplicar el conocimiento.</p></div></div>`, visual: `<div class="visual-title">Referencia principal</div><h3>SWEBOK Guide v4.0</h3><p>IEEE Computer Society, 2024; página oficial actualizada como v4.0a en 2025.</p><p class="source">Las versiones históricas se distinguen como antecedentes, no como vigentes.</p>`, note: "Evitar presentar el borrador local de 2004 como autoridad actual. La clase usa SWEBOK para orientar vocabulario y alcance." },
  { title: "Puente T1 → T3: ficha trazable", eyebrow: "Primer instrumento", lead: "Un requisito útil conserva su origen, su tipo, su riesgo y la forma en que se verificará.", body: `<div class="card"><div class="table-like"><div class="row"><strong>ID</strong><span>GE-RF-01</span><span>estable</span></div><div class="row"><strong>Requisito</strong><span>Consultar tasas y evolución</span><span>funcional</span></div><div class="row"><strong>Fuente</strong><span>Enunciado inicial</span><span>cita</span></div><div class="row"><strong>Actor / prioridad</strong><span>Usuario / provisional</span><span>revisar</span></div><div class="row"><strong>Verificación</strong><span>Escenario de consulta</span><span>observable</span></div></div></div>`, visual: `<div class="visual-title">La ficha también pregunta</div><ul class="compact"><li>¿Qué supuesto estamos agregando?</li><li>¿Qué riesgo ético o de seguridad aparece?</li><li>¿Qué queda Por validar?</li><li>¿Con qué modelo y hito se conecta?</li></ul>`, note: "Mostrar la ficha como plantilla mínima para T3. El identificador del ejemplo proviene de la matriz de alineación." },
  { title: "Actividad grupal: ¿qué puede salir mal?", eyebrow: "30–40 minutos · equipos de 3–5", lead: "Analicen una operación de cambio digital y conviertan un riesgo en una decisión verificable.", body: `<div class="cards"><div class="card"><span class="number">1</span><h3>Elegir escenario</h3><p>Compra, venta, consulta, pago o administración.</p></div><div class="card"><span class="number">2</span><h3>Mapear</h3><p>Actor, acción, dato, daño potencial.</p></div><div class="card"><span class="number">3</span><h3>Formular</h3><p>Requisito, criterio y pregunta abierta.</p></div><div class="card"><span class="number">4</span><h3>Compartir</h3><p>Una decisión y un pendiente por equipo.</p></div></div>`, visual: `<div class="visual-title">Producto de la actividad</div><p><strong>Una ficha trazable</strong> + un riesgo ético + una pregunta Por validar.</p><div class="callout"><strong>No usar datos reales.</strong><p>Trabajamos con escenarios ficticios del enunciado.</p></div>`, note: "Dar 5 minutos para formar equipos, 20–25 para análisis y 10 para puesta en común. Circular preguntando por la fuente del requisito." },
  { title: "Salida individual", eyebrow: "3 minutos de síntesis", lead: "Antes de cerrar, cada persona deja una evidencia breve de comprensión.", body: `<div class="cards"><div class="card"><h3>Un RF</h3><p>Redactá un requisito funcional de Global Exchange con actor y resultado.</p></div><div class="card"><h3>Un RNF</h3><p>Proponé un requisito no funcional con escenario o marcá la medida Por validar.</p></div><div class="card"><h3>Un riesgo ético</h3><p>Identificá quién podría sufrir un daño y por qué.</p></div><div class="card"><h3>Una pregunta abierta</h3><p>Escribí algo que el equipo debe confirmar.</p></div></div>`, visual: `<div class="visual-title">Criterio de calidad</div><p>Si otra persona puede entender qué se pide, de dónde surge y cómo revisarlo, la salida es trazable.</p>`, note: "Recolectar la salida para diagnosticar el pasaje de T1 a T3. No calificar por extensión." },
  { title: "Cinco ideas clave", eyebrow: "Cierre", lead: "La ingeniería de software hace visibles decisiones, riesgos y evidencias.", body: `<div class="cards"><div class="card"><span class="number">01</span><p>Software es producto y contexto, no sólo código.</p></div><div class="card"><span class="number">02</span><p>Calidad necesita criterios verificables.</p></div><div class="card"><span class="number">03</span><p>El proceso se adapta y se revisa.</p></div><div class="card"><span class="number">04</span><p>Global Exchange es un enunciado inicial.</p></div><div class="card"><span class="number">05</span><p>Ética, privacidad y autorización atraviesan el trabajo.</p></div></div>`, visual: `<div class="visual-title">Próximo paso</div><h3>T3: requisitos</h3><p>Transformar el relato en un inventario con identificadores, fuentes, tipos, riesgos y preguntas abiertas.</p><span class="tag">Trazabilidad desde el primer borrador</span>`, note: "Cerrar retomando la pregunta disparadora y pedir que la respondan ahora con una razón y una evidencia." },
  { title: "Referencias principales", eyebrow: "Para continuar leyendo", lead: "Las referencias se seleccionan por autoridad, vigencia y relación directa con la clase.", body: `<div class="table-like"><div class="row"><strong>SWEBOK Guide v4.0</strong><span>IEEE Computer Society, 2024</span><a href="https://www.computer.org/education/bodies-of-knowledge/software-engineering">Fuente oficial</a></div><div class="row"><strong>ISO/IEC/IEEE 12207:2026</strong><span>Procesos de ciclo de vida</span><a href="https://www.iso.org/standard/90219.html">Fuente ISO</a></div><div class="row"><strong>ISO 9000:2015</strong><span>Fundamentos de calidad</span><a href="https://www.iso.org/standard/45481.html">Fuente ISO</a></div><div class="row"><strong>Código ACM/IEEE-CS</strong><span>Ética profesional</span><a href="https://www.acm.org/code-of-ethics/software-engineering-code">Fuente ACM</a></div><div class="row"><strong>Manifiesto Ágil</strong><span>Valores y adaptación</span><a href="https://agilemanifesto.org/iso/es/manifesto.html">Fuente primaria</a></div></div>`, visual: `<div class="visual-title">Fuentes del curso</div><p>Programa oficial, matriz de alineación y enunciado Global Exchange del repositorio de la asignatura.</p><details><summary>Nota de vigencia</summary><p>SWEBOK 2004, ISO 9126 e IEEE 830 aparecen sólo como antecedentes históricos en los materiales; no se presentan como referencias vigentes.</p></details>`, note: "Indicar que las URL son referencias de lectura, no dependencias de la presentación. La presentación funciona sin conexión." }
];

const stage = document.querySelector('#stage');
const indexPanel = document.querySelector('#index-panel');
const notesPanel = document.querySelector('#notes-panel');
const index = document.querySelector('#slide-index');
const notes = document.querySelector('#speaker-notes');
let current = 0;

function render() {
  const slide = slides[current];
  stage.innerHTML = `<article class="slide${slide.full ? ' full' : ''}" aria-labelledby="slide-title"><div><p class="eyebrow">${slide.eyebrow}</p><h1 id="slide-title">${slide.title}</h1><p class="lede">${slide.lead}</p>${slide.body}</div><div>${slide.visual}</div><span class="slide-number">${String(current + 1).padStart(2, '0')}</span></article>`;
  document.querySelector('#counter').textContent = `${String(current + 1).padStart(2, '0')} / ${String(slides.length).padStart(2, '0')}`;
  const progress = document.querySelector('#progress');
  progress.style.width = `${((current + 1) / slides.length) * 100}%`;
  progress.setAttribute('aria-valuenow', current + 1);
  notes.innerHTML = `<div class="note"><strong>Vista ${current + 1}: ${slide.title}</strong><p>${slide.note}</p></div>`;
  document.querySelectorAll('.index-item').forEach((button, i) => button.classList.toggle('active', i === current));
  history.replaceState(null, '', `#slide-${current + 1}`);
}
function goTo(position) { current = Math.max(0, Math.min(slides.length - 1, position)); render(); document.querySelector('#main-content').focus({ preventScroll: true }); }
function toggle(panel) { const open = panel.classList.toggle('open'); panel.setAttribute('aria-hidden', String(!open)); const control = document.querySelector(`[aria-controls="${panel.id}"]`); if (control) control.setAttribute('aria-expanded', String(open)); }
slides.forEach((slide, i) => { const button = document.createElement('button'); button.className = 'index-item'; button.textContent = `${String(i + 1).padStart(2, '0')} · ${slide.title}`; button.addEventListener('click', () => { goTo(i); toggle(indexPanel); }); index.append(button); });
document.querySelector('#next').addEventListener('click', () => goTo(current + 1));
document.querySelector('#index-toggle').addEventListener('click', () => toggle(indexPanel));
document.querySelector('#notes-toggle').addEventListener('click', () => toggle(notesPanel));
document.querySelectorAll('.close-panel').forEach(button => button.addEventListener('click', () => toggle(document.querySelector(`#${button.dataset.close}`))));
document.querySelector('#fullscreen').addEventListener('click', () => document.documentElement.requestFullscreen?.());
document.addEventListener('keydown', event => { if (['ArrowRight', 'PageDown', ' '].includes(event.key)) { event.preventDefault(); goTo(current + 1); } if (['ArrowLeft', 'PageUp'].includes(event.key)) { event.preventDefault(); goTo(current - 1); } if (event.key === 'Home') { event.preventDefault(); goTo(0); } if (event.key === 'End') { event.preventDefault(); goTo(slides.length - 1); } if (event.key.toLowerCase() === 'n') toggle(notesPanel); if (event.key.toLowerCase() === 'i') toggle(indexPanel); });
window.addEventListener('hashchange', () => { const match = location.hash.match(/slide-(\d+)/); if (match) goTo(Number(match[1]) - 1); });
const initial = location.hash.match(/slide-(\d+)/); if (initial) current = Number(initial[1]) - 1; render();
