const slides = [
  {
    "title": "Ingeniería de Software I",
    "eyebrow": "01 · Apertura",
    "body": "<div class=\"card card--hero\">\n  <p class=\"lede\">PRESENTACIÓN DE LA MATERIA</p>\n  <p>Prof. Lic. Guillermo Jacobo González Rodas Mst. PMP</p>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Ingeniería de Software I:** esta asignatura estudia cómo producir y sostener software, no solamente cómo programarlo; por ejemplo, en un sistema de turnos hospitalarios, primero hay que organizar decisiones, roles y controles antes de escribir código. **PRESENTACIÓN DE LA MATERIA:** este título abre el curso y sirve para ubicar la unidad y el contexto de trabajo que se desarrollará durante todo el semestre; por ejemplo, en un proyecto de facturación electrónica, la presentación define qué problemas de negocio se van a abordar. **Prof. Lic. Guillermo Jacobo González Rodas Mst. PMP:** el docente que dicta la materia presenta su trayectoria para dar contexto a la cursada; por ejemplo, en un sistema de biblioteca, conocer quién coordina ayuda a entender qué perspectivas y criterios orientarán el trabajo. <br><br><strong>Reflexión docente:</strong> La profesión exige ampliar la mirada: una solución técnicamente interesante puede fallar si no responde al contexto de uso.<br><br><strong>Pregunta desafío:</strong> ¿qué diferencia esperan encontrar entre programar y ejercer Ingeniería de Software?<br><br><strong>Respuestas posibles:</strong> 1. Programar implementa una solución; la Ingeniería de Software organiza todo su ciclo de vida. 2. La Ingeniería de Software incorpora requisitos, calidad, coordinación, riesgos y mantenimiento. 3. Una persona puede programar correctamente y aun así no resolver el problema completo del sistema.<br><br><strong>Advertencia:</strong> esta apertura contextualiza; todavía no define conceptos técnicos."
  },
  {
    "title": "Sobre el Docente",
    "eyebrow": "02 · Contexto",
    "body": "<article class=\"card card--blog\">\n  <header style=\"display:flex; gap:1.2rem; align-items:center; margin-bottom:.8rem;\">\n    <img class=\"avatar\" src=\"assets/foto-docente.png\" alt=\"Foto del docente\">\n    <div>\n      <h3>Prof. Lic. Guillermo Jacobo González Rodas Mst. PMP</h3>\n      <span class=\"badge\">ggonzalez@pol.una.py</span>\n    </div>\n  </header>\n  <p>Paraguayo, Profesional, egresado de la carrera de Licenciatura en Análisis de Sistemas Informáticos de la Facultad Politécnica de la Universidad Nacional de Asunción. Ha realizado un Máster en Ingeniería del Software por la Universidad Politécnica de Catalunya, Barcelona - España. Tiene la certificación de PMP (Project Management Professional) del PMI (Project Management Institute).</p>\n  <p>Es Consultor de TICs, especializado en Gestión de Proyectos e Implementación de sistemas de información empresariales (ERP). Es docente universitario en el Departamento de Informática, en el Departamento de Gestión y Director de la Unidad de Gestión de Proyectos de Investigación de la Facultad Politécnica de la Universidad Nacional de Asunción.</p>\n</article>",
    "note": "<strong>Desarrollo:</strong> **Sobre el Docente:** el slide presenta la trayectoria profesional de quien dicta la materia, combinando Ingeniería de Software, gestión de proyectos y consultoría; por ejemplo, en una plataforma educativa, una persona puede relevar necesidades de docentes y estudiantes, y otra organizar la entrega con el equipo. **Paraguayo, egresado de la Licenciatura en Análisis de Sistemas Informáticos de la Facultad Politécnica:** la formación académica local aporta la base de análisis de sistemas; por ejemplo, en un sistema de comercio electrónico, saber modelar requisitos evita construir funciones que nadie usa. **Máster en Ingeniería del Software y certificación PMP del PMI:** estos estudios y la certificación de gestión de proyectos aportan herramientas para dirigir el trabajo; por ejemplo, en un proyecto de logística, coordinar alcance, plazos y riesgos evita que la entrega se retrase. **Consultor de TICs especializado en ERP y docente universitario:** la experiencia en implementación de sistemas empresariales y la docencia muestran perspectivas distintas sobre un mismo trabajo; por ejemplo, en un banco, implementar un sistema empresarial exige alinear procesos de negocio y software. **E-mail: ggonzalez@pol.una.py:** el contacto institucional permite consultar dudas del curso; por ejemplo, en cualquier materia, saber a quién escribir y por qué canal forma parte de la organización del trabajo. <br><br><strong>Reflexión docente:</strong> La colaboración entre roles reduce puntos ciegos, aunque también exige acordar vocabulario y responsabilidades.<br><br><strong>Pregunta desafío:</strong> ¿qué decisiones tomaría un analista funcional que no tomaría un programador?<br><br><strong>Respuestas posibles:</strong> 1. Aclarar necesidades y reglas del negocio con las personas involucradas. 2. Analizar alternativas de alcance y priorizar requisitos antes de implementarlos. 3. Un programador puede aportar viabilidad técnica, pero no debería asumir automáticamente la decisión del negocio.<br><br><strong>Advertencia:</strong> presento la trayectoria como contexto docente, no como contenido evaluable."
  },
  {
    "title": "Sobre la Asignatura",
    "eyebrow": "03 · Organización",
    "body": "<div class=\"card-grid card-grid--3\">\n  <div class=\"card\"><strong style=\"color:var(--fpuna-blue);\">Turno/Sección</strong><p>Tarde-Q</p></div>\n  <div class=\"card card--num\"><span class=\"number\">36</span><p>Clases teóricas</p></div>\n  <div class=\"card card--num\"><span class=\"number\">54</span><p>Clases prácticas</p></div>\n</div>\n<p style=\"margin-top:1rem;\">Horas cátedras semanales</p>",
    "note": "<strong>Desarrollo:</strong> **Sobre La Asignatura:** el slide resume los datos organizativos de la cursada; por ejemplo, en un sistema de reservas, conocer el horario y la carga ayuda a planificar el trabajo. **Turno/Sección: Tarde-Q:** identifica en qué turno y sección se dicta la materia; por ejemplo, en una institución educativa, la sección define el grupo, el docente y el calendario de entregas. **Horas cátedras semanales:** la carga total de la materia se reparte entre teoría y práctica; por ejemplo, en un hospital, la jornada del personal se reparte entre formación y atención. **Clases teóricas: 36:** las horas de teoría ayudan a construir conceptos; por ejemplo, en una clase teórica se puede analizar cómo se modelan los requisitos de un sistema de turnos. **Clases prácticas: 54:** las horas de práctica permiten aplicar y revisar lo aprendido; por ejemplo, en logística, una actividad práctica puede representar el flujo de un pedido y detectar dónde falta información. <br><br><strong>Reflexión docente:</strong> El aprendizaje se vuelve visible cuando una idea puede convertirse en una decisión o artefacto revisable.<br><br><strong>Pregunta desafío:</strong> ¿qué actividad práctica demostraría que una idea fue comprendida?<br><br><strong>Respuestas posibles:</strong> 1. Aplicar el concepto a un caso y explicar por qué la decisión es adecuada. 2. Elaborar un modelo, prueba o documento que otra persona pueda revisar. 3. Comparar una alternativa correcta con otra y justificar el trade-off.<br><br><strong>Advertencia:</strong> no confundan la distribución horaria con una garantía de dedicación total."
  },
  {
    "title": "Metodología",
    "eyebrow": "04 · Cómo trabajamos",
    "body": "<div class=\"card-grid card-grid--2\">\n  <div class=\"card card--num\"><span class=\"number\">01</span><p>Las clases teóricas se desarrollarán en clases magistrales a cargo del docente y trabajo práctico a ser realizado por los estudiantes.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">02</span><p>Los estudiantes realizarán los trabajos prácticos en grupos y serán supervisados por los docentes.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">03</span><p>Presentación y defensa de trabajos prácticos relacionados con el área en cuestión.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">04</span><p>En la plataforma virtual se realizarán foros de discusión.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">05</span><p>Tutorías a distancia: individuales y/o grupales.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Metodología:** el slide describe cómo se desarrollará el aprendizaje, combinando exposición, práctica, equipo, defensa, foro y tutoría; por ejemplo, en un curso de análisis de datos, esta combinación permite que una idea se convierta en un artefacto revisable. **Clases magistrales a cargo del docente y trabajo práctico de los estudiantes:** la teoría la expone el docente y los estudiantes producen el trabajo práctico; por ejemplo, en banca, un grupo podría justificar el flujo de una transferencia y responder qué controles aplicaría antes de liberarla. **Trabajos prácticos en grupos supervisados por los docentes:** los estudiantes trabajan en equipo y los docentes los acompañan; por ejemplo, en un proyecto de comercio electrónico, el grupo reparte tareas y revisa las decisiones de cada integrante. **Presentación y defensa de trabajos prácticos:** los equipos presentan y defienden su trabajo; por ejemplo, en logística, defender un modelo de rutas hace visible el razonamiento detrás de cada decisión. **Foros de discusión en la plataforma virtual:** el foro permite debatir y revisar ideas de forma asincrónica; por ejemplo, en una biblioteca digital, los foros ayudan a consensuar criterios entre usuarios y responsables. **Tutorías a distancia individuales o grupales:** las tutorías resuelven dudas y ajustan el trabajo; por ejemplo, en una universidad, una tutoría puede aclarar un requisito ambiguo antes de codificar. <br><br><strong>Reflexión docente:</strong> Defender una solución hace visible el razonamiento y puede revelar supuestos que una entrega aislada no muestra.<br><br><strong>Pregunta desafío:</strong> ¿qué evidencia mostraría que un grupo colaboró realmente?<br><br><strong>Respuestas posibles:</strong> 1. Un producto integrado, con decisiones y aportes trazables de sus integrantes. 2. La capacidad de explicar y defender el trabajo como equipo, no solo repartir diapositivas. 3. Cambios incorporados a partir de revisiones, foros o tutorías.<br><br><strong>Advertencia:</strong> participar no equivale solo a asistir; requiere producir y justificar decisiones."
  },
  {
    "title": "Aula Virtual",
    "eyebrow": "05 · Acceso",
    "body": "<div class=\"ficha\">\n  <div class=\"ficha-row\"><strong>Plataforma</strong><span>Educa</span></div>\n  <div class=\"ficha-row\"><strong>Nombre corto del aula virtual</strong><span>ingsof1-av 2024</span></div>\n  <div class=\"ficha-row\"><strong>Link de acceso al aula virtual</strong><a href=\"https://grado.pol.una.py/course/view.php?id=6508\">https://grado.pol.una.py/course/view.php?id=6508</a></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Aula Virtual:** el slide indica dónde funciona el espacio de trabajo en línea del curso; por ejemplo, en una organización, el aula virtual centraliza anuncios, materiales y entregas. **Plataforma: Educa:** es la plataforma que aloja el aula; por ejemplo, en una empresa, la plataforma de gestión define dónde se guardan los documentos y cómo se accede a ellos. **Nombre corto del aula virtual: ingsof1-av 2024:** identifica el aula para buscarla y reconocerla sin ambigüedad; por ejemplo, en un sistema de biblioteca, el código de una colección permite ubicarla fácilmente. **Link de acceso al aula virtual:** el enlace dirige al espacio concreto de trabajo; por ejemplo, en un servicio web, una URL de administración puede documentarse para que el equipo llegue al panel correcto. **Contraseña:** el aula exige una credencial que en el material original se registra como dato sensible y no se publica; por ejemplo, en un servicio gestionado, los secretos de acceso deben manejarse por un canal seguro y fuera del repositorio, porque una exposición accidental convierte un recurso académico en un incidente de seguridad. <br><br><strong>Reflexión docente:</strong> Una exposición accidental de credenciales convierte un recurso académico en un incidente de seguridad; la prevención forma parte de la práctica profesional.<br><br><strong>Pregunta desafío:</strong> ¿qué harían si una contraseña aparece en un repositorio?<br><br><strong>Respuestas posibles:</strong> 1. Avisar al responsable y revocar o cambiar la credencial de inmediato. 2. Retirar el secreto del historial y revisar quién pudo acceder. 3. Registrar el incidente y evitar volver a publicar el valor en documentación o capturas.<br><br><strong>Advertencia:</strong> nunca expongan credenciales en notas, repositorios ni capturas públicas."
  },
  {
    "title": "Sobre el Contenido",
    "eyebrow": "06 · Recorrido",
    "body": "<div class=\"card-grid card-grid--2\">\n  <div class=\"card card--num\"><span class=\"number\">I</span><p>Unidad I: Introducción a la Ingeniería de Software</p></div>\n  <div class=\"card card--num\"><span class=\"number\">II</span><p>Unidad II: Modelos de Proceso del Software</p></div>\n  <div class=\"card card--num\"><span class=\"number\">III</span><p>Unidad III: Ingeniería de Requerimientos</p></div>\n  <div class=\"card card--num\"><span class=\"number\">IV</span><p>Unidad IV: Diseño del Software</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Sobre el Contenido:** el slide presenta el recorrido del curso como un mapa de cuatro unidades; por ejemplo, en un proyecto de historias clínicas, conviene relevar necesidades antes de diseñar. **Unidad I: Introducción a la Ingeniería de Software:** introduce la disciplina y su vocabulario básico; por ejemplo, en salud, entender qué es el software permite hablar de productos y procesos con precisión. **Unidad II: Modelos de Proceso del Software:** estudia cómo organizar el trabajo de desarrollo; por ejemplo, en un banco, elegir un modelo de proceso ayuda a controlar plazos y riesgos de una migración. **Unidad III: Ingeniería de Requerimientos:** se ocupa de acordar qué debe hacer el sistema; por ejemplo, en comercio electrónico, los requerimientos expresan qué problema resuelve el catálogo o el proceso de compra. **Unidad IV: Diseño del Software:** decide cómo construir la solución; por ejemplo, en logística, el diseño define la arquitectura del seguimiento de paquetes. La secuencia va de comprender el problema y organizar el trabajo a decidir cómo construir la solución, porque saltar etapas puede producir modelos elegantes para un problema mal entendido. <br><br><strong>Reflexión docente:</strong> Saltar etapas puede producir modelos elegantes para un problema mal entendido; el orden ayuda a reducir retrabajo.<br><br><strong>Pregunta desafío:</strong> ¿por qué conviene estudiar requerimientos antes del diseño?<br><br><strong>Respuestas posibles:</strong> 1. Porque los requerimientos expresan qué problema debe resolver el sistema. 2. Porque el diseño debe responder a restricciones y necesidades ya comprendidas. 3. Porque diseñar antes puede fijar una solución que luego contradiga al usuario o al negocio.<br><br><strong>Advertencia:</strong> el mapa anticipa temas; no reemplaza el desarrollo de cada unidad."
  },
  {
    "title": "Sobre las Evaluaciones",
    "eyebrow": "07 · Evaluación",
    "body": "<div class=\"table-like\">\n  <div class=\"row\"><strong>Parciales</strong><span>Examen escrito</span><b>30%</b></div>\n  <div class=\"row\"><strong>Parciales</strong><span>Trabajo práctico</span><b>70%</b></div>\n  <div class=\"row\"><strong>Final</strong><span>Examen escrito (Caso práctico)</span><b>100%</b></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Sobre las Evaluaciones:** el slide describe cómo se evalúa la materia, combinando conocimiento y aplicación; por ejemplo, en un sistema de reservas, evaluar solo definiciones no demuestra si se puede diseñar una solución. **Parciales:** durante la cursada hay exámenes parciales que combinan dos componentes; por ejemplo, en educación, un parcial suele repartirse entre teoría y práctica. **Examen escrito 30%:** el examen escrito aporta el 30% de la nota de los parciales; por ejemplo, en una universidad, un examen puede pedir justificar una decisión de diseño frente a un requisito. **Trabajo práctico 70%:** el trabajo práctico aporta el 70%, el peso mayor de la evaluación; por ejemplo, en transporte, un caso de asignación de viajes puede exigir explicar requisitos, riesgos y decisiones de diseño. **Final:** al cierre hay un examen final; por ejemplo, en un proyecto de facturación, el final evalúa el caso completo. **Examen escrito (Caso práctico) 100%:** el final es un examen escrito sobre un caso práctico que vale el 100%; por ejemplo, en un banco, resolver un caso de conciliación obliga a conectar conceptos, decisiones y justificaciones, no solo a repetir definiciones. <br><br><strong>Reflexión docente:</strong> La evaluación combina conocimiento y aplicación; prepararse solo para memorizar deja sin demostrar una parte central del trabajo profesional.<br><br><strong>Pregunta desafío:</strong> ¿cómo justificarían una decisión de diseño frente a un requisito?<br><br><strong>Respuestas posibles:</strong> 1. Vinculando la decisión con el requisito y con la necesidad que lo origina. 2. Explicando alternativas descartadas, riesgos y consecuencias. 3. Mostrando evidencia, como un modelo, prueba o criterio de aceptación.<br><br><strong>Advertencia:</strong> conserven exactamente los porcentajes del material."
  },
  {
    "title": "Trabajos Prácticos",
    "eyebrow": "08 · Hitos",
    "body": "<div class=\"card-grid card-grid--2\" style=\"gap: 2.25rem;\">\n  <div class=\"card\"><span class=\"badge\">H1–H3</span><ul><li>Requerimientos (H1)</li><li>Casos de Uso (H2)</li><li>Especificación de Casos de Uso (H3)</li></ul></div>\n  <div class=\"card\"><span class=\"badge\">H4–H8</span><ul><li>Diagrama de Clases (H4)</li><li>Diagrama de Secuencia (H5)</li><li>Diagrama de Estados (H6)</li><li>Diagrama de Actividades (H7)</li><li>Diagrama de Despliegue (H8)</li></ul></div>\n</div>\n<div class=\"card\" style=\"margin-top: 1.75rem;\"><p><strong>H</strong> - Hito</p><ul><li>Formar equipos hasta 4 integrantes</li><li>Caso Práctico o Proyecto</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> **Trabajos Prácticos:** el slide describe cómo se construye el caso práctico o proyecto de la materia; por ejemplo, en un proyecto de logística, se puede pasar de requisitos de despacho a casos de uso y diagramas del seguimiento de paquetes. **Formar equipos hasta 4 integrantes:** los estudiantes trabajan en equipos reducidos; por ejemplo, en un desarrollo de software real, un equipo pequeño facilita coordinar aportes y responsabilidades. **Caso Práctico o Proyecto:** la modalidad de trabajo es construir un caso o proyecto completo; por ejemplo, en comercio electrónico, el proyecto puede ir de los requisitos del carrito hasta su despliegue. **Requerimientos (H1), Casos de Uso (H2), Especificación de Casos de Uso (H3):** los primeros hitos capturan qué debe hacer el sistema y cómo se usará; por ejemplo, en un hospital, H1 aclara los requisitos de turnos y H2 describe las interacciones del paciente con el sistema. **Diagrama de Clases (H4), Secuencia (H5), Estados (H6), Actividades (H7), Despliegue (H8):** los siguientes hitos modelan la estructura y el comportamiento de la solución; por ejemplo, en banca, el diagrama de secuencia describe cómo se procesa una transferencia paso a paso. **H - Hito:** la H significa hito, un punto de control para revisar una parte del trabajo antes de avanzar; por ejemplo, en un proyecto de facturación, cada hito evita descubrir al final que las decisiones iniciales estaban mal orientadas. <br><br><strong>Reflexión docente:</strong> Trabajar incrementalmente reduce el riesgo de descubrir al final que todas las decisiones iniciales estaban mal orientadas, aunque cada hito requiere revisión real.<br><br><strong>Pregunta desafío:</strong> ¿qué riesgo aparece si se salta el hito de requerimientos?<br><br><strong>Respuestas posibles:</strong> 1. Diseñar o codificar funciones que no resuelven la necesidad real. 2. Generar inconsistencias entre casos de uso y diagramas posteriores. 3. Aumentar el retrabajo porque los errores se descubren tarde.<br><br><strong>Advertencia:</strong> un hito es un punto de control, no solo una fecha de entrega."
  },
  {
    "title": "Bibliografía de Referencia",
    "eyebrow": "09 · Lecturas",
    "body": "<div class=\"card-grid card-grid--2\">\n  <div class=\"card card--blog\"><h3>SOMMERVILLE, Ian</h3><p>Ingeniería de Software 6 y 7º Edición. Addison Wesley. 2002-2005.</p></div>\n  <div class=\"card card--blog\"><h3>PRESSMAN, Roger</h3><p>5º y 6º, 7º Edición. Ingeniería del Software. Un enfoque práctico. McGraw-Hill. 2002-2005-2010.</p></div>\n  <div class=\"card card--blog\"><h3>McCONNELL, Steve</h3><p>Desarrollo y gestión de proyectos informáticos. McGraw-Hill. 1997.</p></div>\n  <div class=\"card card--blog\"><h3>PIATTINI, Mario</h3><p>Calidad de Sistemas Informáticos. Alfaomega - Ra-Ma. 2007.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Bibliografía de Referencia:** el slide reúne las fuentes para ampliar conceptos y contrastar explicaciones; por ejemplo, para un sistema gubernamental legado, distintas fuentes ayudan a comparar mantenibilidad, riesgos y gestión del proyecto. **SOMMERVILLE, Ian. Ingeniería de Software, 6 y 7º Edición. Addison Wesley, 2002-2005:** es la referencia clásica sobre el ciclo de vida del software; por ejemplo, en un curso, sirve para verificar una definición de proceso. **PRESSMAN, Roger 5º y 6º, 7º Edición. Ingeniería del Software. Un enfoque práctico. McGraw-Hill, 2002-2005-2010:** ofrece una visión práctica de métodos y prácticas de desarrollo; por ejemplo, en un proyecto de comercio electrónico, ayuda a fundamentar decisiones de diseño. **McCONNELL, Steve. Desarrollo y gestión de proyectos informáticos. McGraw-Hill, 1997:** se centra en la gestión y estimación de proyectos; por ejemplo, en logística, ayuda a planificar plazos y recursos de un sistema de despacho. **PIATTINI, Mario. Calidad de Sistemas Informáticos. Alfaomega-Ra-Ma, 2007:** aborda la calidad de los sistemas; por ejemplo, en banca, sirve para definir criterios de confiabilidad y trazabilidad. Respetemos la edición, editorial y año del material: una actualización bibliográfica debe identificarse como tal. <br><br><strong>Reflexión docente:</strong> Consultar fuentes no significa acumular citas: significa verificar conceptos y reconocer el alcance de cada afirmación.<br><br><strong>Pregunta desafío:</strong> ¿qué afirmación del slide buscarían verificar en una fuente?<br><br><strong>Respuestas posibles:</strong> 1. Una definición de Ingeniería de Software o de proceso. 2. Una comparación entre productos genéricos y hechos a medida. 3. Una recomendación cuya aplicabilidad dependa del contexto.<br><br><strong>Advertencia:</strong> no presenten una edición o año actualizado como si perteneciera al material original."
  },
  {
    "title": "Unidad I – Introducción a la Ingeniería de Software",
    "eyebrow": "10 · Cambio de bloque",
    "body": "<div class=\"card card--hero\">\n  <p class=\"lede\">INGENIERÍA DE SOFTWARE I</p>\n  <p>Prof. Lic. Guillermo Jacobo González Rodas Mst. PMP</p>\n</div>",
    "note": "<strong>Desarrollo:</strong> **INGENIERÍA DE SOFTWARE I:** este separador marca el paso de la organización del curso a la Unidad I, donde se construirá el vocabulario para hablar de productos, procesos, costos, retos y responsabilidad profesional; por ejemplo, un sistema de transporte permite estudiar problemas similares de requisitos, operación, mantenimiento y evolución, y en un banco ayuda a analizar cómo una disciplina organiza decisiones más allá del código. **Prof. Lic. Guillermo Jacobo González Rodas Mst. PMP:** la presencia del docente en el separador recuerda quién conduce la unidad y qué perspectiva aporta al dictado; por ejemplo, en un proyecto de facturación, saber quién coordina ayuda a orientar las consultas y las decisiones del equipo. Este cambio de registro importa: comprender el curso ayuda a participar, pero comprender la disciplina permite tomar mejores decisiones profesionales, como decidir qué producir primero o cómo equilibrar las necesidades del negocio con las restricciones técnicas. <br><br><strong>Reflexión docente:</strong> Este cambio de registro importa: comprender el curso ayuda a participar, pero comprender la disciplina permite tomar mejores decisiones profesionales.<br><br><strong>Pregunta desafío:</strong> ¿qué problema profesional esperan que la unidad ayude a comprender?<br><br><strong>Respuestas posibles:</strong> 1. Cómo producir software confiable y mantenible. 2. Cómo organizar un proceso para reducir errores y retrabajo. 3. Cómo equilibrar necesidades del negocio, restricciones técnicas y responsabilidad.<br><br><strong>Advertencia:</strong> no adelanten conclusiones antes de presentar los conceptos."
  },
  {
    "title": "Objetivos",
    "eyebrow": "11 · Resultados esperados",
    "body": "<div class=\"card-grid card-grid--3\">\n  <div class=\"card card--num\"><span class=\"number\">01</span><p>Definir la Ingeniería de Software y explicar su importancia.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">02</span><p>Discutir los conceptos de Producto de Software y Proceso de Software.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">03</span><p>Introducir la noción de responsabilidad profesional de un ingeniero de software.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **OBJETIVOS:** los objetivos del slide funcionan como criterios de aceptación de la unidad; por ejemplo, en un proyecto de una plataforma educativa, saber qué se debe lograr evita entregar funciones que nadie usa. **Definir la Ingeniería de Software y explicar su importancia:** al cierre, deberemos definir la disciplina con palabras propias y justificar por qué importa; por ejemplo, en un sistema de biblioteca, explicar qué es la Ingeniería de Software ayuda a distinguirla de simplemente programar. **Discutir los conceptos de Producto de Software y Proceso de Software:** distinguir producto de proceso permite razonar sobre un caso; por ejemplo, en una plataforma de evaluaciones, el producto es el sistema y el proceso, la forma de construirlo y mantenerlo. **Introducir la noción de responsabilidad profesional de un ingeniero de software:** la unidad introduce los deberes profesionales de quien construye software; por ejemplo, en un hospital, un sistema que maneja datos de pacientes exige pensar en privacidad y en las consecuencias de los fallos. Un objetivo se demuestra con evidencia: repetir una frase no alcanza si no podemos usarla para razonar sobre un caso. <br><br><strong>Reflexión docente:</strong> Un objetivo se demuestra con evidencia: repetir una frase no alcanza si no podemos usarla para razonar sobre un caso.<br><br><strong>Pregunta desafío:</strong> ¿cómo demostrarían que pueden definir y no solo repetir un término?<br><br><strong>Respuestas posibles:</strong> 1. Explicándolo con palabras propias y distinguiéndolo de conceptos cercanos. 2. Aplicándolo a un caso y justificando qué elementos lo muestran. 3. Comparando ejemplos y contraejemplos.<br><br><strong>Advertencia:</strong> distingan conocer una definición de aplicarla a un caso."
  },
  {
    "title": "Contenido",
    "eyebrow": "12 · Mapa de la unidad",
    "body": "<div class=\"sequence-card\" aria-label=\"Secuencia temática de la unidad\">\n  <div class=\"sequence-step\"><span class=\"sequence-index\">01</span><strong>La Ingeniería de Software</strong><small>Disciplina</small></div>\n  <div class=\"sequence-step\"><span class=\"sequence-index\">02</span><strong>Productos Software</strong><small>Qué construimos</small></div>\n  <div class=\"sequence-step\"><span class=\"sequence-index\">03</span><strong>Costos del Software</strong><small>Qué debemos controlar</small></div>\n  <div class=\"sequence-step\"><span class=\"sequence-index\">04</span><strong>Proceso de Software</strong><small>Cómo lo desarrollamos</small></div>\n  <div class=\"sequence-step\"><span class=\"sequence-index\">05</span><strong>Retos de la Ingeniería de Software</strong><small>Qué exige la profesión</small></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **CONTENIDO:** el slide presenta el mapa de temas de la unidad; por ejemplo, en un sistema de comercio electrónico, mantenimiento, volumen de usuarios y entregas pueden modificar tanto el proceso como el costo. **La Ingeniería de Software:** se estudia la disciplina como punto de partida; por ejemplo, en un banco, entender la disciplina permite conectar decisiones con sus consecuencias. **Productos Software:** se analizan los productos como resultado del trabajo; por ejemplo, en una biblioteca digital, el producto incluye programas y documentación asociada. **Costos del Software:** se estudia cuánto cuesta producir y mantener software; por ejemplo, en logística, un sistema difícil de cambiar encarece cada modificación futura. **Proceso de Software:** se analiza cómo se organizan las actividades de desarrollo; por ejemplo, en facturación, un proceso con controles puede requerir más esfuerzo inicial y reducir retrabajo. **Retos de la Ingeniería de Software:** se cierra con los desafíos profesionales; por ejemplo, en salud, integrar plataformas distintas y entregar a tiempo condiciona cada decisión. El orden organiza la conversación, pero los temas están conectados: el proceso influye en costos y los retos condicionan las decisiones. <br><br><strong>Reflexión docente:</strong> Pensar cada tema de forma aislada oculta trade-offs; la ingeniería consiste en conectar decisiones con sus consecuencias.<br><br><strong>Pregunta desafío:</strong> ¿cómo se relacionan costo y proceso?<br><br><strong>Respuestas posibles:</strong> 1. Un proceso con controles puede requerir más esfuerzo inicial y reducir retrabajo. 2. Un proceso poco claro puede abaratar el inicio, pero aumentar fallos y mantenimiento. 3. El contexto determina qué inversión produce una mejora razonable.<br><br><strong>Advertencia:</strong> el orden organiza la explicación, pero los temas están conectados."
  },
  {
    "title": "¿Qué es la Ingeniería de Software?",
    "eyebrow": "13 · Definición",
    "body": "<div class=\"quote\">La ingeniería del software es una disciplina que comprende todos los aspectos de la producción del software desde las etapas iniciales de la especificación del sistema hasta el mantenimiento de éste después de que se utiliza. <em>(Definición de Ian Somerville)</em></div><div class=\"card-grid card-grid--3\"><div class=\"card\"><h3>Disciplina</h3><p>La Ingeniería de Software es una disciplina de la Ingeniería que concierne a todos los aspectos de la producción de software.</p></div><div class=\"card\"><h3>Principios</h3><p>Establecimiento y uso de principios con caracteres de ingeniería apropiados para obtener software confiable, que opere eficaz y eficientemente en máquinas reales.</p></div><div class=\"card\"><h3>Métodos</h3><p>Establecimiento y uso de métodos, herramientas y procedimientos, orientados a obtener software económico que sea fiable y funcione de manera eficiente.</p></div></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 7ª ed. Addison Wesley, 2005.</p>",
    "note": "<strong>Desarrollo:</strong> **¿Qué es la Ingeniería de Software?:** el slide plantea la pregunta central de la unidad y ofrece una definición amplia con formulaciones complementarias; por ejemplo, una aplicación de turnos médicos necesita las mismas actividades para operar confiablemente y adaptarse a nuevas necesidades. **Definición de Ian Sommerville:** la ingeniería del software es una disciplina que comprende todos los aspectos de la producción del software, desde las etapas iniciales de la especificación del sistema hasta el mantenimiento después de que se utiliza; por ejemplo, en una plataforma educativa, hay que especificar reglas, producir la solución, verificarla y mantenerla. **Disciplina de la Ingeniería que concierne a la producción de software:** la segunda formulación destaca que es una disciplina de la ingeniería aplicada a todos los aspectos de la producción; por ejemplo, en comercio electrónico, la producción no termina al lanzar la tienda, continúa con su operación y sus ajustes. **Establecimiento y uso de principios de ingeniería apropiados:** se busca obtener software confiable que opere eficaz y eficientemente en máquinas reales; por ejemplo, en un sistema de control industrial, los principios evitan fallos costosos. **Establecimiento y uso de métodos, herramientas y procedimientos:** se orienta a obtener software económico, fiable y eficiente; por ejemplo, en banca, usar métodos probados reduce el costo de los errores. <br><br><strong>Reflexión docente:</strong> La mirada profesional distribuye la prevención a lo largo del ciclo; esperar al final para descubrir fallos suele limitar las alternativas.<br><br><strong>Pregunta desafío:</strong> ¿en qué etapa se puede prevenir un fallo costoso?<br><br><strong>Respuestas posibles:</strong> 1. Desde la especificación, aclarando necesidades y restricciones. 2. Durante diseño y desarrollo, revisando decisiones antes de hacerlas más costosas de cambiar. 3. En validación, detectando evidencia insuficiente antes de la operación.<br><br><strong>Advertencia:</strong> Ingeniería de Software no es únicamente escribir código."
  },
  {
    "title": "¿Qué es el Software?",
    "eyebrow": "14 · Definiciones",
    "body": "<div class=\"card-grid card-grid--2\">\n  <div class=\"card\"><h3>Sommerville:</h3><p>“Programas de cómputo y su documentación asociada.”</p><p class=\"reference\">Sommerville, I. Ingeniería de Software, 7ª ed. Addison Wesley, 2005.</p></div>\n  <div class=\"card\"><h3>Pressman:</h3><p>“Elemento del sistema de información que es lógico, con características considerablemente distintas a las del hardware.”</p><p class=\"reference\">Pressman, R. Ingeniería del Software: Un enfoque práctico, 7ª ed. McGraw-Hill, 2010.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **¿Qué es el Software?:** el slide contrasta dos definiciones de software para mostrar miradas complementarias; por ejemplo, en un sistema legado de gobierno, entender qué es el software ayuda a decidir qué documentar antes de modificarlo. **Sommerville:** define el software como programas de cómputo y su documentación asociada; por ejemplo, además del programa de una biblioteca, se documentan reglas, operación y errores. **Programas de cómputo y su documentación asociada:** la documentación sostiene el uso, la operación y el mantenimiento del producto; por ejemplo, un sistema legado puede seguir funcionando, pero sin documentación su mantenimiento depende de conocimiento difícil de transferir. **Pressman:** define el software como un elemento del sistema de información que es lógico; por ejemplo, una aplicación de reservas es lógica, no se desgasta como una máquina física. **Elemento lógico con características distintas a las del hardware:** el software no se fabrica ni se desgasta de la misma forma, pero igual afecta la operación física; por ejemplo, en un hospital, el software controla equipos aunque sea intangible. <br><br><strong>Reflexión docente:</strong> Tratar la documentación como un accesorio aumenta la dependencia de personas y el riesgo de operar o cambiar el sistema sin comprenderlo.<br><br><strong>Pregunta desafío:</strong> ¿qué documento asociarían a un sistema real?<br><br><strong>Respuestas posibles:</strong> 1. Manual de usuario o procedimiento operativo. 2. Especificación de requisitos, diseño o interfaz de integración. 3. Instrucciones de despliegue, mantenimiento y recuperación ante fallos.<br><br><strong>Advertencia:</strong> lógico no significa intangible o irrelevante para la operación física."
  },
  {
    "title": "Productos de Software",
    "eyebrow": "15 · Tipos",
    "body": "<div class=\"table-like\">\n  <div class=\"row\"><strong>Genéricos</strong><span>Productos producidos por una organización para ser comercializados.</span></div>\n  <div class=\"row\"><strong>A medida</strong><span>Sistemas desarrollados bajo pedido a un desarrollador específico.</span></div>\n</div>\n<div class=\"card\"><p>La mayor parte del gasto del software se realiza en productos genéricos, pero existe un mayor esfuerzo en el desarrollo de los sistemas hechos a medida.</p></div>\n<p class=\"reference\">Sommerville, I. Ingeniería de Software, 7ª ed. Addison Wesley, 2005. Cap. 1.</p>",
    "note": "<strong>Desarrollo:</strong> **Productos de Software:** el slide clasifica los productos según su origen y compara gasto y esfuerzo; por ejemplo, un hospital puede comprar un producto estándar o encargar un sistema adaptado a sus circuitos y regulaciones. **Productos genéricos:** son producidos por una organización para ser comercializados a varias organizaciones; por ejemplo, una aplicación de facturación genérica puede servir a varias empresas mediante configuración. **Productos hechos a medida:** son sistemas desarrollados bajo pedido para un cliente específico; por ejemplo, un sistema de logística diseñado para una empresa integra reglas y sistemas particulares de esa empresa. **La mayor parte del gasto del software se realiza en productos genéricos, pero existe un mayor esfuerzo en el desarrollo de los sistemas hechos a medida:** el slide distingue gasto de esfuerzo, una comparación del material que no debe tomarse como ley universal; por ejemplo, en banca, comprar un producto estándar reduce el gasto inicial, pero integrarlo a la operación exige esfuerzo considerable. <br><br><strong>Reflexión docente:</strong> Pasar de un cliente a muchos amplía la necesidad de configurar, documentar y sostener variaciones; la reutilización trae oportunidades y restricciones.<br><br><strong>Pregunta desafío:</strong> ¿qué decisión cambia al pasar de un cliente a muchos?<br><br><strong>Respuestas posibles:</strong> 1. Qué requisitos se consideran parte del producto común y cuáles serán configurables. 2. Cómo se priorizan cambios que afectan a varios clientes. 3. Qué estrategia de soporte, documentación y evolución se necesita.<br><br><strong>Advertencia:</strong> no conviertan la comparación del slide en una regla para todos los mercados."
  },
  {
    "title": "Características de Productos Software",
    "eyebrow": "16 · Calidad del producto",
    "body": "<div class=\"card-grid card-grid--2\">\n  <div class=\"card\"><h3>Mantenibles</h3><p>El software debe evolucionar y seguir cumpliendo con sus especificaciones.</p></div>\n  <div class=\"card\"><h3>Confiabilidad</h3><p>El software no debe causar daños físicos o económicos en el caso de fallos.</p></div>\n  <div class=\"card\"><h3>Eficiencia</h3><p>El software no debe desperdiciar los recursos del sistema.</p></div>\n  <div class=\"card\"><h3>Utilización adecuada</h3><p>El software debe contar con una interfaz de usuario y documentación adecuada.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Características de Productos Software:** el slide presenta los atributos que debe observar un producto de software, no como etiquetas decorativas sino como condiciones que verificar; por ejemplo, en un sistema de salud, confiabilidad y utilización adecuada son especialmente visibles en alertas, permisos y documentación para el personal. **Mantenibles:** el software debe evolucionar y seguir cumpliendo con sus especificaciones; por ejemplo, una aplicación de facturación debe adaptarse a nuevos impuestos sin rehacerla. **Confiabilidad:** el software no debe causar daños físicos o económicos en caso de fallos; por ejemplo, en un hospital, un sistema de dosificación no puede fallar sin consecuencias. **Eficiencia:** el software no debe desperdiciar los recursos del sistema; por ejemplo, en un sistema de cómputo distribuido, un algoritmo ineficiente encarece la infraestructura. **Utilización adecuada:** el software debe contar con interfaz de usuario y documentación adecuada; por ejemplo, en una biblioteca, una interfaz confusa y sin manual genera errores de uso. Cada atributo expresa una condición que observar, y mejorar uno puede exigir costos o compromisos en otros. <br><br><strong>Reflexión docente:</strong> Mejorar un atributo puede exigir costos o compromisos en otros; la prioridad debe justificarse por el contexto y el impacto.<br><br><strong>Pregunta desafío:</strong> ¿qué atributo priorizarían en un sistema crítico y por qué?<br><br><strong>Respuestas posibles:</strong> 1. Confiabilidad, si un fallo puede causar daño económico o físico. 2. Mantenibilidad, si el entorno cambia y el sistema deberá evolucionar durante años. 3. Eficiencia, si los recursos son limitados y afectan la operación. 4. Utilización adecuada, si errores de comprensión pueden comprometer el servicio.<br><br><strong>Advertencia:</strong> mejorar un atributo puede exigir costos o compromisos en otros."
  },
  {
    "title": "Importancia de las Características",
    "eyebrow": "17 · Contexto",
    "body": "<div class=\"card-grid card-grid--3\">\n  <div class=\"card\"><h3>Depende del contexto</h3><p>La importancia relativa de las características depende del tipo de producto y del ambiente en el que será utilizado.</p></div>\n  <div class=\"card\"><h3>Predominio</h3><p>En algunos casos, algunos atributos pueden predominar. En sistemas de seguridad críticos de tiempo real, los atributos clave pueden ser la confiabilidad y la eficiencia.</p></div>\n  <div class=\"card\"><h3>Costos</h3><p>Los costos tienden a crecer exponencialmente si son requeridos altos niveles de alguna característica.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Importancia de las Características:** el slide explica que los atributos no tienen un valor absoluto, sino relativo al contexto; por ejemplo, un sistema de control médico puede priorizar confiabilidad de forma distinta que una aplicación de entretenimiento. **La importancia relativa de las características depende del tipo de producto y del ambiente:** las prioridades cambian según dónde y para qué se usa el sistema; por ejemplo, en un banco, una operación financiera puede priorizar confiabilidad y trazabilidad, mientras una consulta pública de tasas tolera otra combinación de atributos. **En sistemas de seguridad críticos de tiempo real, los atributos clave pueden ser la confiabilidad y la eficiencia:** cuando un fallo puede ser peligroso y el tiempo es decisivo, estos atributos predominan; por ejemplo, en un sistema de control de tráfico, la confiabilidad es prioridad absoluta. **Los costos tienden a crecer exponencialmente si se requieren altos niveles de alguna característica:** exigir niveles muy altos encarece el desarrollo; por ejemplo, en un sistema de vigilancia industrial, alcanzar disponibilidad casi total multiplica la inversión. El slide expresa una tendencia cualitativa; no aporta una fórmula de costos. <br><br><strong>Reflexión docente:</strong> No existe una prioridad profesional fuera de contexto: sacrificar un atributo puede ser razonable en un caso y peligroso en otro.<br><br><strong>Pregunta desafío:</strong> ¿qué atributo sacrificarían menos en cada caso?<br><br><strong>Respuestas posibles:</strong> 1. En control médico, confiabilidad, porque el impacto de un fallo puede ser crítico. 2. En una aplicación de entretenimiento, quizá eficiencia o disponibilidad según el uso, sin ignorar seguridad. 3. En una operación financiera, confiabilidad y trazabilidad antes que una mejora superficial de velocidad.<br><br><strong>Advertencia:</strong> el slide expresa una tendencia cualitativa; no aporta una fórmula de costos."
  },
  {
    "title": "Clasificación de Productos Software",
    "eyebrow": "18 · Taxonomía",
    "body": "<div class=\"card-grid card-grid--3\">\n  <div class=\"card\"><h3>Por su estructura:</h3><ul><li>Funcionales.</li><li>Orientados a objetos.</li><li>Orientados a listas.</li><li>Orientados a componentes.</li></ul></div>\n  <div class=\"card\"><h3>Por su función:</h3><ul><li>Programas o Sistemas de Usuario.</li><li>Herramientas de Software.</li><li>Librerías.</li><li>Sistemas de uso genérico: Compiladores, S.O's, Procesadores de Texto, etc.</li><li>Bases de Datos.</li><li>Sistemas basados en Web.</li></ul></div>\n  <div class=\"card\"><h3>Por su plataforma de cómputo:</h3><ul><li>Sistemas embebidos o empotrados.</li><li>Sistemas de cómputo distribuido.</li><li>Sistemas de tiempo real.</li><li>Sistemas basados en Chips.</li><li>Sistemas de cómputo ubicuos.</li></ul></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Clasificación de Productos Software:** el slide organiza los productos según tres ejes distintos: estructura, función y plataforma de cómputo; por ejemplo, una aplicación móvil de logística puede combinar una interfaz de usuario, bases de datos, servicios distribuidos y funciones de ubicación. **Por su estructura:** clasifica según la organización interna del software; por ejemplo, un sistema puede ser funcional, orientado a objetos, orientado a listas u orientado a componentes. **Funcionales, orientados a objetos, orientados a listas, orientados a componentes:** cada estilo define cómo se estructuran módulos y datos; por ejemplo, en un banco, el software suele estructurarse por componentes para reutilizar funciones. **Por su función:** clasifica según el papel que cumple el software; por ejemplo, en un hospital, conviven sistemas de usuario, herramientas y bases de datos. **Programas de usuario, herramientas, librerías, sistemas de uso genérico, bases de datos y sistemas basados en Web:** los sistemas de uso genérico incluyen compiladores, sistemas operativos y procesadores de texto; por ejemplo, en comercio electrónico, una tienda web combina una aplicación de usuario con una base de datos. **Por su plataforma de cómputo:** clasifica según el tipo de hardware donde corre el software; por ejemplo, un sistema de riego agrícola puede correr sobre un sistema embebido. **Sistemas embebidos, distribuidos, de tiempo real, basados en chips y ubicuos:** cada plataforma impone restricciones distintas; por ejemplo, un sistema de tiempo real responde dentro de plazos estrictos, mientras uno ubicuo acompaña al usuario en distintos dispositivos. No mezclemos criterios como si fueran categorías excluyentes. <br><br><strong>Reflexión docente:</strong> Clasificar con varios ejes ayuda a describir mejor un sistema; forzar una sola etiqueta oculta decisiones técnicas importantes. <br><br><strong>Pregunta desafío:</strong> ¿qué clasificaciones aplicarían a una aplicación móvil? <br><br><strong>Respuestas posibles:</strong> 1. Por función, como programa de usuario o sistema basado en web si expone servicios web. 2. Por plataforma, como sistema distribuido o ubicuo según su arquitectura y uso. 3. Por estructura, según use objetos, componentes u otra organización indicada por el material. <br><br><strong>Advertencia:</strong> no mezclen criterios como si fueran categorías excluyentes."
  },
  {
    "title": "Costos del Software",
    "eyebrow": "19 · Eficiencia",
    "body": "<div class=\"card-grid card-grid--2\" style=\"gap: 2.5rem; align-items: stretch;\">\n  <div style=\"display: grid; gap: 1.25rem; align-content: start;\">\n    <div class=\"card\"><p>Los costos del software a menudo dominan al costo del sistema.</p></div>\n    <div class=\"card\"><p>Cuesta más mantener el software que desarrollarlo.</p></div>\n    <div class=\"card\"><p>La Ingeniería de Software concierne a un desarrollo efectivo en cuanto a costos del software.</p></div>\n  </div>\n  <div style=\"display: flex; align-items: center; justify-content: center;\">\n    <img class=\"figure-img\" src=\"assets/costos-software.png\" alt=\"Gráfico de Costos frente a Eficiencia - curva ascendente\" style=\"max-width: 100%; height: auto;\">\n  </div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Costos del Software:** el slide presenta afirmaciones sobre los costos y las acompaña con un gráfico que relaciona costos y eficiencia; por ejemplo, un sistema legado de transporte puede requerir más mantenimiento que desarrollo cuando cada cambio rompe integraciones antiguas. **Los costos del software a menudo dominan al costo del sistema:** el software suele ser la parte más cara de un sistema completo; por ejemplo, en un sistema de facturación, el hardware se amortiza, pero el software exige inversión continua. **Cuesta más mantener el software que desarrollarlo:** el mantenimiento puede superar el costo del desarrollo inicial; por ejemplo, una arquitectura difícil de cambiar vuelve costoso adaptar un sistema de reservas a nuevas reglas. **La Ingeniería de Software concierne a un desarrollo efectivo en cuanto a costos:** la disciplina busca que el desarrollo sea efectivo en costos; por ejemplo, en un banco, aclarar requisitos temprano reduce el retrabajo. **Gráfico de Costos frente a Eficiencia:** la curva ascendente del gráfico muestra cómo los costos se elevan con rapidez hacia la derecha a medida que se exige más eficiencia; por ejemplo, en comercio electrónico, exigir niveles muy altos de respuesta encarece la infraestructura. El gráfico expresa una relación cualitativa; no permite inferir valores ni una fórmula. <br><br><strong>Reflexión docente:</strong> La eficiencia profesional incluye pensar el costo futuro; ahorrar hoy sin cuidar mantenibilidad puede trasladar el problema a toda la vida del sistema.<br><br><strong>Pregunta desafío:</strong> ¿qué decisión temprana reduciría el costo futuro?<br><br><strong>Respuestas posibles:</strong> 1. Aclarar requisitos y restricciones antes de comprometer una solución. 2. Diseñar puntos de cambio y registrar decisiones para facilitar mantenimiento. 3. Validar temprano las integraciones o riesgos que podrían generar retrabajo.<br><br><strong>Advertencia:</strong> el gráfico expresa una relación cualitativa; no permite inferir valores ni una fórmula."
  },
  {
    "title": "Proceso de Software",
    "eyebrow": "20 · Actividades",
    "body": "<div class=\"card\"><p><strong>Conjunto estructurado de actividades requeridas para desarrollar un sistema de software.</strong></p></div>\n<div class=\"sequence-card\" aria-label=\"Flujo de actividades del proceso de software\">\n  <div class=\"sequence-step\"><span class=\"sequence-index\">01</span><strong>Especificación</strong><small>Qué debe hacer el software y cuáles son sus especificaciones de desarrollo.</small></div>\n  <div class=\"sequence-step\"><span class=\"sequence-index\">02</span><strong>Desarrollo</strong><small>Producción del sistema de software.</small></div>\n  <div class=\"sequence-step\"><span class=\"sequence-index\">03</span><strong>Validación</strong><small>Verificar que el software hace lo que el cliente pide.</small></div>\n  <div class=\"sequence-step\"><span class=\"sequence-index\">04</span><strong>Evolución</strong><small>Cambiar/adaptar el software a las demandas.</small></div>\n</div>\n<div class=\"card-grid card-grid--2\">\n  <div class=\"card\"><p>Las actividades varían dependiendo de la organización y del tipo de sistema a desarrollarse.</p></div>\n  <div class=\"card\"><p>Debe estar explícitamente modelado si va a ser bien administrado.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Proceso de Software:** el slide define el proceso y enumera sus actividades centrales; por ejemplo, un sistema de turnos puede adaptar su proceso según la criticidad, la privacidad y la cantidad de integraciones. **Conjunto estructurado de actividades requeridas para desarrollar un sistema de software:** el proceso organiza las actividades necesarias para producir el sistema; por ejemplo, en facturación, especificar, desarrollar, validar y evolucionar forman el ciclo. **Especificación:** establece qué debe hacer el software y cuáles son sus especificaciones de desarrollo; por ejemplo, en un hospital, la especificación fija requisitos, restricciones y criterios de aceptación. **Desarrollo:** es la producción del sistema de software; por ejemplo, en comercio electrónico, el desarrollo incluye diseño, código y decisiones de construcción. **Validación:** verifica que el software hace lo que el cliente pide; por ejemplo, en logística, las pruebas confirman que el seguimiento de paquetes cumple lo pedido. **Evolución:** cambia o adapta el software a las demandas; por ejemplo, en banca, las nuevas regulaciones obligan a evolucionar el sistema. **Las actividades varían dependiendo de la organización y del tipo de sistema:** no existe una receta única; por ejemplo, una biblioteca pequeña y un banco estructuran su proceso de forma distinta. **Debe estar explícitamente modelado si va a ser bien administrado:** modelar el proceso mejora la visibilidad sin volverlo rígido; por ejemplo, en un proyecto de software, un proceso modelado permite detectar cuellos de botella. <br><br><strong>Reflexión docente:</strong> Modelar el proceso mejora la visibilidad, pero no debe convertir el trabajo en una secuencia rígida incapaz de responder a evidencia nueva.<br><br><strong>Pregunta desafío:</strong> ¿qué evidencia ubicarían en cada actividad?<br><br><strong>Respuestas posibles:</strong> 1. Especificación: requisitos, restricciones y criterios de aceptación. 2. Desarrollo: diseño, código y decisiones de construcción. 3. Validación: pruebas, revisiones y evidencia de que se cumple lo pedido. 4. Evolución: cambios priorizados, incidentes y nuevas necesidades.<br><br><strong>Advertencia:</strong> modelar el proceso no significa volverlo rígido."
  },
  {
    "title": "Proceso Genérico",
    "eyebrow": "21 · Secuencia",
    "body": "<div class=\"card-grid card-grid--2\">\n  <div class=\"card card--num\"><span class=\"number\">01</span><h3>Especificación</h3><p>Establecer los requerimientos y restricciones del sistema.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">02</span><h3>Diseño</h3><p>Producir un modelo del sistema.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">03</span><h3>Codificación</h3><p>Construir el sistema.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">04</span><h3>Prueba</h3><p>Verificar que el sistema cumpla con las especificaciones requeridas.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">05</span><h3>Instalación</h3><p>Entregar el sistema al usuario y asegurar su operacionalidad.</p></div>\n  <div class=\"card card--num\"><span class=\"number\">06</span><h3>Mantenimiento</h3><p>Reparar fallos en el sistema cuando sean descubiertos.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Proceso Genérico:** el slide presenta las seis actividades básicas de un proceso de desarrollo, cada una con un propósito distinto; por ejemplo, en comercio electrónico, probar el proceso de compra antes de instalarlo evita que una ambigüedad de requerimientos llegue a producción. **Especificación:** establecer los requerimientos y restricciones del sistema; por ejemplo, en un hospital, acordar qué datos de pacientes se registran antes de construir. **Diseño:** producir un modelo del sistema; por ejemplo, en logística, el diseño define la arquitectura del seguimiento de paquetes. **Codificación:** construir el sistema; por ejemplo, en banca, implementar el módulo de transferencias según el diseño acordado. **Prueba:** verificar que el sistema cumpla con las especificaciones requeridas; por ejemplo, en facturación, probar que los cálculos de impuestos sean correctos. **Instalación:** entregar el sistema al usuario y asegurar su operacionalidad; por ejemplo, en una biblioteca, instalar el sistema de préstamos y capacitar al personal. **Mantenimiento:** reparar fallos en el sistema cuando sean descubiertos; por ejemplo, en comercio electrónico, corregir errores del carrito de compras cuando aparecen. La secuencia ordena el trabajo, pero el trabajo real puede requerir retrocesos con nueva evidencia. <br><br><strong>Reflexión docente:</strong> La secuencia ordena el trabajo, pero no elimina la incertidumbre; el riesgo crece cuando se confunde avanzar con comprender.<br><br><strong>Pregunta desafío:</strong> ¿qué error aparece si se codifica antes de acordar el requerimiento?<br><br><strong>Respuestas posibles:</strong> 1. Construir una solución técnicamente válida para una necesidad equivocada. 2. Aumentar cambios, discusiones y retrabajo cuando el requerimiento se aclare. 3. Dificultar la prueba porque no existe un criterio acordado contra el cual comparar.<br><br><strong>Advertencia:</strong> la secuencia ayuda a organizar, pero el trabajo real puede requerir retrocesos."
  },
  {
    "title": "Características del Proceso",
    "eyebrow": "22 · Lista de comprobación",
    "body": "<div class=\"card-grid card-grid--2\">\n  <div class=\"card\"><h3>Entendible</h3><p>¿Se encuentra el proceso bien definido y es entendible?</p></div>\n  <div class=\"card\"><h3>Visible</h3><p>¿El proceso es visible al exterior?</p></div>\n  <div class=\"card\"><h3>Soportable</h3><p>¿Puede el proceso ser soportado por herramientas CASE?</p></div>\n  <div class=\"card\"><h3>Aceptable</h3><p>¿El proceso es aceptado por aquellos involucrados en él?</p></div>\n  <div class=\"card\"><h3>Confiable</h3><p>¿Errores del proceso son descubiertos antes de que se conviertan en errores del producto?</p></div>\n  <div class=\"card\"><h3>Robusto</h3><p>¿Puede continuar el proceso a pesar de problemas inesperados?</p></div>\n  <div class=\"card\"><h3>Mantenible</h3><p>¿Puede el proceso evolucionar para cumplir con los objetivos organizacionales?</p></div>\n  <div class=\"card\"><h3>Rapidez</h3><p>¿Qué tan rápido puede producirse el sistema?</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Características del Proceso:** el slide presenta ocho características formuladas como preguntas de evaluación; por ejemplo, en logística, un proceso puede ser rápido pero frágil si no hace visibles excepciones, dependencias o pruebas de entregas. **Entendible:** ¿está el proceso bien definido y es entendible?; por ejemplo, en una biblioteca, un proceso claro permite que cualquier integrante sepa qué hacer. **Visible:** ¿el proceso es visible al exterior?; por ejemplo, en un banco, mostrar el estado de una migración permite detectar demoras. **Soportable:** ¿puede el proceso ser soportado por herramientas CASE?; por ejemplo, en un proyecto de software, usar herramientas de modelado facilita el seguimiento. **Aceptable:** ¿el proceso es aceptado por quienes están involucrados?; por ejemplo, en un hospital, un proceso de turnos rechazado por el personal no funciona. **Confiable:** ¿se descubren los errores del proceso antes de que se conviertan en errores del producto?; por ejemplo, en comercio electrónico, las revisiones tempranas evitan fallos en producción. **Robusto:** ¿puede continuar el proceso a pesar de problemas inesperados?; por ejemplo, en logística, un proceso robusto sigue operando si un transporte falla. **Mantenible:** ¿puede el proceso evolucionar para cumplir con los objetivos organizacionales?; por ejemplo, en facturación, el proceso debe adaptarse a nuevas leyes. **Rapidez:** ¿qué tan rápido puede producirse el sistema?; por ejemplo, en una startup, la rapidez es atractiva, pero un proceso que produce errores velozmente no es profesionalmente eficaz. <br><br><strong>Reflexión docente:</strong> La rapidez es atractiva, pero un proceso que produce velozmente errores o retrabajo no es profesionalmente eficaz.<br><br><strong>Pregunta desafío:</strong> ¿qué indicador revelaría primero un proceso frágil?<br><br><strong>Respuestas posibles:</strong> 1. Requisitos que cambian sin trazabilidad ni aceptación clara. 2. Errores del proceso que se descubren recién durante la operación. 3. Bloqueos ante problemas inesperados o dependencia de una sola persona. 4. Entregas rápidas acompañadas de defectos y retrabajo frecuentes.<br><br><strong>Advertencia:</strong> rapidez aislada no equivale a calidad."
  },
  {
    "title": "Problemas en el Proceso",
    "eyebrow": "23 · Riesgos habituales",
    "body": "<div class=\"card\"><p><strong>Normalmente…</strong></p></div>\n<div class=\"card-grid card-grid--2\">\n  <div class=\"card\"><p>Las especificaciones son incompletas o anómalas.</p></div>\n  <div class=\"card\"><p>No existe una distinción precisa entre la especificación, el diseño y la codificación.</p></div>\n  <div class=\"card\"><p>Solo hasta que el sistema se ha producido se puede probar.</p></div>\n  <div class=\"card\"><p>El software no siempre se puede remplazar durante el mantenimiento.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Problemas en el Proceso:** el slide describe riesgos habituales del desarrollo, no resultados inevitables; por ejemplo, si en un sistema de facturación no se aclara una regla de cálculo y se prueba recién al final, se puede descubrir tarde un error que afecta los montos. **Normalmente:** la palabra indica que estos son problemas frecuentes; por ejemplo, en un proyecto de comercio electrónico, los retrasos suelen originarse en requisitos mal comprendidos. **Las especificaciones son incompletas o anómalas:** los requisitos suelen quedar ambiguos o con contradicciones; por ejemplo, en un hospital, dos áreas pueden pedir lo mismo de formas distintas. **No existe una distinción precisa entre la especificación, el diseño y la codificación:** las etapas se mezclan sin controles claros; por ejemplo, en una biblioteca, codificar sin separar el modelo de diseño produce inconsistencias. **Solo hasta que el sistema se ha producido se puede probar:** la prueba tardía concentra los errores al final; por ejemplo, en logística, probar todo el sistema de despacho al final encarece las correcciones. **El software no siempre se puede reemplazar durante el mantenimiento:** algunas piezas antiguas no pueden sustituirse sin romper el resto; por ejemplo, en un sistema gubernamental legado, una pieza antigua no puede reemplazarse sin interrumpir servicios esenciales. La prevención temprana conserva más opciones y reduce el impacto de corregir. <br><br><strong>Reflexión docente:</strong> La prevención temprana no elimina todos los problemas, pero conserva más opciones y reduce el impacto de corregirlos.<br><br><strong>Pregunta desafío:</strong> ¿qué revisión temprana habría reducido el impacto?<br><br><strong>Respuestas posibles:</strong> 1. Revisar requisitos con usuarios y responsables del negocio. 2. Separar y revisar el modelo de diseño antes de codificar. 3. Probar riesgos e integraciones antes de completar todo el sistema.<br><br><strong>Advertencia:</strong> estos son problemas habituales, no afirmaciones inevitables."
  },
  {
    "title": "Retos de los Ingenieros de Software",
    "eyebrow": "24 · Contexto profesional",
    "body": "<div class=\"card-grid card-grid--2\">\n  <div class=\"card\"><h3>Legados</h3><p>Mantener y tratar con sistemas legados; sistemas antiguos que deben ser mantenidos y mejorados.</p></div>\n  <div class=\"card\"><h3>Heterogeneidad</h3><p>Sistemas que incluyen distintas plataformas de software y hardware.</p></div>\n  <div class=\"card\"><h3>Entrega</h3><p>Existe una presión incremental por una entrega a tiempo de los productos de software.</p></div>\n  <div class=\"card\"><h3>Formalidad</h3><p>Existe una gran demanda de que exista formalidad en el proceso de desarrollo de software.</p></div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Retos de los Ingenieros de Software:** el slide cierra la unidad con cuatro retos que combinan restricciones técnicas, organizacionales y profesionales; por ejemplo, un sistema de transporte legado puede tener que convivir con una aplicación móvil nueva sin detener la operación. **Mantener y tratar con sistemas legados:** sistemas antiguos que deben mantenerse y mejorarse; por ejemplo, en banca, el sistema central de cuentas sigue operando mientras se agregan servicios nuevos. **Heterogeneidad:** sistemas que incluyen distintas plataformas de software y hardware; por ejemplo, en comercio electrónico, la tienda web se integra con pasarelas de pago, bases de datos y servicios externos. **Entrega:** existe una presión incremental por una entrega a tiempo de los productos de software; por ejemplo, en logística, lanzar el seguimiento de paquetes antes de una temporada alta obliga a cumplir plazos. **Formalidad:** existe una gran demanda de formalidad en el proceso de desarrollo de software; por ejemplo, en salud, documentar cada cambio es obligatorio para poder auditar. Estos retos no se resuelven solo agregando código; la presión por entregar no elimina la responsabilidad de hacer visibles los riesgos y los límites. <br><br><strong>Reflexión docente:</strong> La presión por entregar puede empujar atajos, pero no elimina la responsabilidad de hacer visibles riesgos y límites.<br><br><strong>Pregunta desafío:</strong> ¿qué riesgo investigarían primero?<br><br><strong>Respuestas posibles:</strong> 1. Dependencias del sistema legado que podrían romperse con el cambio. 2. Incompatibilidades entre plataformas, datos o integraciones. 3. Un requisito crítico que no pueda validarse dentro del plazo. 4. La ausencia de evidencia y formalidad para justificar la entrega.<br><br><strong>Advertencia:</strong> la presión por entregar no elimina la responsabilidad profesional."
  },
  {
    "title": "Muchas Gracias",
    "eyebrow": "25 · Cierre",
    "body": "<div class=\"card card--hero\">\n  <div class=\"quote\" style=\"border-left:0;\">“Pues al igual que un arquitecto es esencial para construir una casa que no se venga abajo, un ingeniero del software es esencial para construir software eficiente, seguro y mantenible (que es el que la gente querrá usar).”</div>\n</div>",
    "note": "<strong>Desarrollo:</strong> **Muchas gracias:** el cierre agradece y retoma los temas centrales de la clase; por ejemplo, en una plataforma educativa, mantener confianza requiere cuidar disponibilidad, datos y facilidad de evolución. **“Pues al igual que un arquitecto es esencial para construir una casa que no se venga abajo, un ingeniero del software es esencial para construir software eficiente, seguro y mantenible (que es el que la gente querrá usar).”:** la cita usa la arquitectura como analogía para recordar que las decisiones estructurales afectan la estabilidad, la evolución y la forma de uso del software; por ejemplo, un sistema de reservas bien diseñado es claro, seguro y fácil de mantener, y por eso la gente sigue usándolo. La ingeniería busca que el software funcione hoy y siga siendo confiable mañana; la calidad profesional se mide también por el impacto en quienes dependen del sistema, no solo por si el código compila o la entrega llega a tiempo. <br><br><strong>Reflexión docente:</strong> La calidad profesional se mide también por el impacto en quienes dependen del sistema, no solo por si el código compila o la entrega llega a tiempo.<br><br><strong>Pregunta desafío:</strong> ¿qué decisión de ingeniería hace que las personas quieran seguir usando el sistema?<br><br><strong>Respuestas posibles:</strong> 1. Diseñar una experiencia comprensible y adecuada al contexto de uso. 2. Proteger datos y operaciones mediante controles proporcionales al riesgo. 3. Invertir en mantenibilidad para corregir y evolucionar sin degradar el servicio. 4. Validar con evidencia que el sistema cumple lo que las personas necesitan.<br><br><strong>Advertencia:</strong> la analogía orienta la comprensión, pero no equipara literalmente ambas profesiones."
  }
];

const stage = document.querySelector('#stage');
const indexPanel = document.querySelector('#index-panel');
const notesPanel = document.querySelector('#notes-panel');
const index = document.querySelector('#slide-index');
const notes = document.querySelector('#speaker-notes');
const printAll = new URLSearchParams(location.search).get('print') === 'all';
const presenterView = new URLSearchParams(location.search).get('view') === 'presenter';
let current = 0;

function slideMarkup(slide, position, headingId = 'slide-title') {
  return `<article class="slide slide-${position + 1}" aria-labelledby="${headingId}"><header class="slide-header"><p class="eyebrow">${slide.eyebrow}</p><h1 id="${headingId}">${slide.title}</h1></header><div class="content">${slide.body}</div></article>`;
}

function render() {
  const slide = slides[current];
  stage.innerHTML = slideMarkup(slide, current);
  document.querySelector('#counter').textContent = `${String(current + 1).padStart(2, '0')} / ${String(slides.length).padStart(2, '0')}`;
  const progress = document.querySelector('#progress');
  progress.style.width = `${((current + 1) / slides.length) * 100}%`;
  progress.setAttribute('aria-valuenow', current + 1);
  notes.innerHTML = `<div class="note"><strong>Slide ${current + 1}: ${slide.title}</strong><p>${slide.note}</p></div>`;
  document.querySelectorAll('.index-item').forEach((button, i) => button.classList.toggle('active', i === current));
  history.replaceState(null, '', `#slide-${current + 1}`);
}
function renderAllForPrint() {
  const total = slides.length;
  stage.innerHTML = slides.map((slide, position) => {
    const pageNum = String(position + 1).padStart(2, '0');
    const totalNum = String(total).padStart(2, '0');
    const header = `<div class="print-header"><div class="print-header-left"><img class="print-header-logo" src="assets/fpuna_logo_institucional.svg" alt="Logo FP-UNA"><div class="print-header-text"><span class="print-header-title">Ingeniería del Software I</span><span class="print-header-subtitle">FP-UNA / Licenciatura en Ciencias Informáticas (LCiK)</span></div></div><span class="print-header-page">${pageNum} / ${totalNum}</span></div>`;
    return `<div class="print-slide">${header}${slideMarkup(slide, position)}</div>`;
  }).join('');
  fitSlidesForPrint();
}
function fitSlidesForPrint() {
  // Mantiene la disposición exacta de cada slide: si el contenido desborda
  // la hoja, lo escala uniformemente (zoom out) en vez de comprimirlo.
  // El wrapper .print-slide maneja altura/overflow/paginación; el slide
  // interior conserva altura natural y recibe el scale. Se mide con un
  // clon en dimensiones de impresión porque en beforeprint el media print
  // aún no está activo y el slide crecería con su contenido.
  const PAGE_W = 1123; // 297mm a 96dpi
  const PAGE_H = 631;  // 167mm a 96dpi
  const HEADER_H = 56; // altura del print-header (logo 36px + padding 20px)
  const PADDING_SIDE = 56, PADDING_TOP = 10, PADDING_BOTTOM = 32; // reglas print de .slide
  const GAP_ROW = 22.5, GAP_COL = 56; // clamp() print con viewport 1123px
  const probe = document.createElement('div');
  probe.style.cssText = `position: fixed; top: 0; left: -20000px; width: ${PAGE_W}px; visibility: hidden; pointer-events: none;`;
  document.body.appendChild(probe);
  stage.querySelectorAll('.print-slide').forEach((wrap) => {
    const slide = wrap.querySelector('.slide');
    const clone = slide.cloneNode(true);
    clone.style.cssText = `display: grid; grid-template-columns: 1fr; grid-template-areas: "header" "content"; gap: ${GAP_ROW}px; align-content: start; align-items: start; width: ${PAGE_W}px; height: auto; min-height: 0; max-height: none; overflow: visible; padding: ${PADDING_TOP}px ${PADDING_SIDE}px ${PADDING_BOTTOM}px; animation: none;`;
    const h1 = clone.querySelector('.slide-header h1');
    if (h1) h1.style.fontSize = '36px'; // clamp(1.6rem, 3.2vw, 2.8rem) reducido 20%
    probe.appendChild(clone);
    const naturalHeight = clone.getBoundingClientRect().height;
    const scale = Math.min(1, (PAGE_H - HEADER_H) / naturalHeight);
    probe.innerHTML = '';
    if (scale < 1) {
      slide.style.transformOrigin = 'top left';
      slide.style.transform = `scale(${scale})`;
    }
  });
  probe.remove();
}
window.addEventListener('beforeprint', fitSlidesForPrint);
function goTo(position, options = {}) {
  current = Math.max(0, Math.min(slides.length - 1, position));
  render();
  if (!options.silent && presenterWindow && !presenterWindow.closed) {
    presenterWindow.postMessage({ type: 'presentation:navigate', index: current }, '*');
  }
  if (options.focus !== false) document.querySelector('#main-content')?.focus({ preventScroll: true });
}
function toggle(panel, force) { const open = typeof force === 'boolean' ? force : !panel.classList.contains('open'); panel.classList.toggle('open', open); panel.setAttribute('aria-hidden', String(!open)); const control = document.querySelector(`[aria-controls="${panel.id}"]`); if (control) control.setAttribute('aria-expanded', String(open)); if (open) panel.querySelector('button, [href]')?.focus(); }

let presenterWindow = null;
function showNotice(message) {
  const notice = document.querySelector('#popup-notice, #presenter-notice');
  if (!notice) return;
  notice.textContent = message;
  notice.hidden = false;
  window.setTimeout(() => { notice.hidden = true; }, 7000);
}
function openPresenter() {
  presenterWindow = window.open(`${location.pathname}?view=presenter#slide-${current + 1}`, 'fpuna-presenter', 'popup,width=1440,height=900,resizable=yes,scrollbars=yes');
  if (!presenterWindow) { showNotice('El navegador bloqueó la ventana del modo presentador. Permití las ventanas emergentes para este sitio e intentá nuevamente.'); return; }
  presenterWindow.focus();
}

function initAudience() {
  slides.forEach((slide, i) => { const button = document.createElement('button'); button.className = 'index-item'; button.type = 'button'; button.textContent = `${String(i + 1).padStart(2, '0')} · ${slide.title}`; button.addEventListener('click', () => { goTo(i); toggle(indexPanel, false); }); index.append(button); });
  document.querySelector('#next').addEventListener('click', () => goTo(current + 1));
  document.querySelector('#previous').addEventListener('click', () => goTo(current - 1));
  document.querySelector('#index-toggle').addEventListener('click', () => toggle(indexPanel));
  document.querySelector('#notes-toggle').addEventListener('click', () => toggle(notesPanel));
  document.querySelectorAll('.close-panel').forEach(button => button.addEventListener('click', () => toggle(document.querySelector(`#${button.dataset.close}`), false)));
  document.querySelector('#presenter-mode').addEventListener('click', openPresenter);
  document.querySelector('#fullscreen').addEventListener('click', () => document.documentElement.requestFullscreen?.());
  document.addEventListener('keydown', event => { if (event.key === 'Escape') { toggle(indexPanel, false); toggle(notesPanel, false); } if (['ArrowRight', 'PageDown', ' '].includes(event.key)) { event.preventDefault(); goTo(current + 1); } if (['ArrowLeft', 'PageUp'].includes(event.key)) { event.preventDefault(); goTo(current - 1); } if (event.key === 'Home') { event.preventDefault(); goTo(0); } if (event.key === 'End') { event.preventDefault(); goTo(slides.length - 1); } if (event.key.toLowerCase() === 'n') toggle(notesPanel); if (event.key.toLowerCase() === 'i') toggle(indexPanel); });
  window.addEventListener('hashchange', () => { const match = location.hash.match(/slide-(\d+)/); if (match) goTo(Number(match[1]) - 1); });
  window.addEventListener('message', event => { if (event.source !== presenterWindow) return; if (event.data?.type === 'presenter:ready') presenterWindow.postMessage({ type: 'presentation:state', index: current }, '*'); if (event.data?.type === 'presenter:navigate') goTo(event.data.index, { silent: true }); if (event.data?.type === 'presenter:fullscreen') { const request = document.documentElement.requestFullscreen?.(); request?.catch(() => showNotice('El navegador no permitió activar pantalla completa desde la ventana presentador. Activala con el botón Pantalla completa de esta ventana.')); } });
  const initial = location.hash.match(/slide-(\d+)/); if (initial) current = Number(initial[1]) - 1;
  if (printAll) renderAllForPrint(); else render();
}

function fitPresenterSlide(frame) {
  const slide = frame.querySelector('.slide'); if (!slide) return;
  slide.style.transform = 'none'; slide.style.width = '100%';
  const width = slide.scrollWidth; const height = slide.scrollHeight;
  const scale = Math.min(1, frame.clientWidth / width, frame.clientHeight / height);
  slide.style.width = `${100 / scale}%`; slide.style.transformOrigin = 'top left'; slide.style.transform = `scale(${scale})`;
  frame.style.setProperty('--slide-scale', scale);
}

function initPresenter() {
  document.body.innerHTML = `<main class="presenter-shell"><header class="presenter-header"><div><p class="presenter-kicker">FP-UNA · Ingeniería del Software I</p><h1>Modo presentador</h1></div><div class="presenter-meta"><span id="presenter-counter">01 / ${String(slides.length).padStart(2, '0')}</span><time id="presenter-clock"></time></div></header><section class="presenter-workspace" aria-label="Vista del presentador"><section class="presenter-notes"><h2>Notas docentes</h2><div id="presenter-notes-content" tabindex="0"></div></section><div class="presenter-stack"><div class="presenter-current"><div class="presenter-label">Slide actual</div><div id="presenter-current-frame" class="presenter-slide-frame"></div></div><section class="presenter-next"><h2>Siguiente slide</h2><div id="presenter-next-frame" class="presenter-slide-frame presenter-slide-frame--next"></div></section></div></section><footer class="presenter-controls"><button id="presenter-previous" type="button">← Anterior</button><button id="presenter-next" type="button">Siguiente →</button><span class="presenter-spacer"></span><button id="presenter-public" type="button">Pantalla completa del público</button><button id="presenter-close" type="button">Cerrar</button></footer><div id="presenter-notice" class="popup-notice" role="status" aria-live="polite" hidden></div></main>`;
  const currentFrame = document.querySelector('#presenter-current-frame'); const nextFrame = document.querySelector('#presenter-next-frame');
  function renderPresenter() { const slide = slides[current]; const next = current + 1; currentFrame.innerHTML = slideMarkup(slide, current, 'presenter-current-title'); nextFrame.innerHTML = next < slides.length ? slideMarkup(slides[next], next, 'presenter-next-title') : '<p class="presenter-end-message">Fin de la presentación</p>'; document.querySelector('#presenter-notes-content').innerHTML = slide.note; document.querySelector('#presenter-counter').textContent = `${String(current + 1).padStart(2, '0')} / ${String(slides.length).padStart(2, '0')}`; requestAnimationFrame(() => { fitPresenterSlide(currentFrame); fitPresenterSlide(nextFrame); }); }
  function presenterGoTo(position, silent = false) { current = Math.max(0, Math.min(slides.length - 1, position)); renderPresenter(); if (!silent && window.opener && !window.opener.closed) window.opener.postMessage({ type: 'presenter:navigate', index: current }, '*'); history.replaceState(null, '', `#slide-${current + 1}`); }
  document.querySelector('#presenter-previous').addEventListener('click', () => presenterGoTo(current - 1)); document.querySelector('#presenter-next').addEventListener('click', () => presenterGoTo(current + 1));
  document.querySelector('#presenter-public').addEventListener('click', () => { if (window.opener && !window.opener.closed) window.opener.postMessage({ type: 'presenter:fullscreen' }, '*'); else showNotice('La pantalla pública no está vinculada a esta ventana.'); });
  document.querySelector('#presenter-close').addEventListener('click', () => window.close());
  document.addEventListener('keydown', event => { if (['ArrowRight', 'PageDown', ' '].includes(event.key)) { event.preventDefault(); presenterGoTo(current + 1); } if (['ArrowLeft', 'PageUp'].includes(event.key)) { event.preventDefault(); presenterGoTo(current - 1); } if (event.key === 'Home') presenterGoTo(0); if (event.key === 'End') presenterGoTo(slides.length - 1); });
  window.addEventListener('resize', () => { fitPresenterSlide(currentFrame); fitPresenterSlide(nextFrame); });
  window.addEventListener('message', event => { if (event.source !== window.opener) return; if (event.data?.type === 'presentation:state') presenterGoTo(event.data.index, true); });
  const initial = location.hash.match(/slide-(\d+)/); if (initial) current = Math.max(0, Math.min(slides.length - 1, Number(initial[1]) - 1)); renderPresenter();
  if (window.opener && !window.opener.closed) window.opener.postMessage({ type: 'presenter:ready' }, '*');
  setInterval(() => { document.querySelector('#presenter-clock').textContent = new Intl.DateTimeFormat('es-PY', { hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(new Date()); }, 1000);
}

if (presenterView) initPresenter(); else initAudience();
