const slides = [
  ['Ingeniería de Software I / Unidad II', 'Apertura', '<p class="lede">MODELOS DE DESARROLLO DE SOFTWARE Y DESARROLLO RÁPIDO DEL SOFTWARE</p><p>Prof. Ing. Julia Talavera</p>', 'Unidad II', 'Presentar el foco de la unidad: modelos de desarrollo y desarrollo rápido del software.'],
  ['Objetivos', 'Resultados', '<ul><li>Entender las diferencias entre métodos tradicionales y ágiles.</li><li>Conocer principios, prácticas y limitaciones de los métodos ágiles.</li><li>Entender cómo un enfoque iterativo e incremental conduce a una entrega más rápida.</li></ul>', 'objectives', 'Leer los tres resultados como contrato de la clase y retomarlos en el cierre.'],
  ['Contenido', 'Mapa', '<ul><li>Introducción</li><li>Características</li><li>Manifiesto ágil</li><li>Principales metodologías ágiles: Adaptive Software Development (ASD), Scrum, XP</li></ul>', 'roadmap', 'Anticipar el recorrido desde el contexto hasta las tres metodologías principales.'],
  ['Ingeniería de Software', 'Contexto', '<p>La calidad del software, las metodologías y la madurez de los entornos de desarrollo siguen siendo temas de discusión y estudio.</p><p><strong>Objetivos:</strong> maximizar calidad, maximizar productividad, minimizar riesgos.</p>', 'triad', 'Enmarcar la unidad como respuesta a problemas persistentes de producción, no como una colección de recetas.'],
  ['Ingeniería de Software: implicancias', 'Contexto', '<ul><li>Constructores básicos más poderosos</li><li>Mejores técnicas de control de calidad</li><li>Mejores herramientas y métodos</li></ul><p>Todo en la forma de procesos adecuados al tipo de problema y que permitan gestionar los principales riesgos.</p>', 'layers', 'Relacionar herramientas y técnicas con la necesidad de un proceso ajustado al problema.'],
  ['Dificultades en producción de software', 'Problema', '<p><strong>Esencia:</strong></p><ul><li>Complejidad</li><li>Conformidad</li><li>Necesidad de cambios</li><li>Invisibilidad</li></ul>', 'four', 'Explicar que estas dificultades son propias del software y justifican estudiar modelos de proceso.'],
  ['Proceso de Software', 'Definición', '<blockquote>“Conjunto relacionado de actividades y tareas implicadas en el desarrollo y evolución de un sistema software”</blockquote><p class="source">Sommerville</p>', 'quote', 'Fijar la definición operativa de proceso antes de comparar modelos.'],
  ['Modelos de Procesos de Software', 'Familias', '<div class="split-list"><section><strong>Modelos Tradicionales (MTs)</strong><p>Cascada · Prototipación · Desarrollo en Fases · Espiral · RUP</p></section><section><strong>Métodos Ágiles (MAs)</strong><p>ASD · Scrum · XP</p></section></div>', 'families', 'Diferenciar la familia tradicional de la ágil y ubicar los modelos que se verán.'],
  ['Modelo en Cascada', 'Tradicional', '<p>Es el más antiguo. Debe completarse un estado antes de comenzar el siguiente. Es útil para visualizar qué hacer. Su principal problema es que no refleja la realidad.</p>', 'waterfall', 'Mostrar la secuencia como una planificación ordenada y señalar la crítica explícita de la fuente.'],
  ['Modelo en Cascada: en la práctica', 'Tradicional', '<p><strong>En la práctica…</strong></p>', 'waterfall-loop', 'Contrastar el modelo ideal con la realidad de retrocesos y ajustes, sin agregar etapas nuevas.'],
  ['Modelo de Prototipación', 'Tradicional', '<ul><li>Permite la construcción rápida del sistema o parte de éste.</li><li>Usuario y desarrollador tienen una visión común.</li><li>Se reduce el riesgo y la incertidumbre.</li></ul>', 'benefits', 'Presentar el prototipo como instrumento de aprendizaje compartido y reducción de incertidumbre.'],
  ['Modelo de Prototipación: flujo', 'Tradicional', '<p>Requerimientos del prototipo · diseño del prototipo · sistema prototipo · testing · revisión · requerimientos del sistema · sistema entregado.</p>', 'prototype', 'Destacar que las revisiones alimentan la maduración de requerimientos antes de la entrega.'],
  ['Modelo de Desarrollo en Fases', 'Tradicional', '<p>El valor es aproximado. Hoy el mercado no acepta grandes retardos. Desarrollar en fases reduce los retardos y permite entregar el sistema por partes.</p><p>El usuario tiene funcionalidad mientras se desarrolla el resto. Producción y desarrollo funcionan en paralelo.</p>', 'parallel', 'Explicar la entrega parcial y la convivencia entre versión operativa y próxima versión.'],
  ['Modelo de Desarrollo en Fases: versiones', 'Tradicional', '<p><strong>Desarrolladores:</strong> construir versión 1, 2 y 3.</p><p><strong>Usuarios:</strong> usar versión 1, 2 y 3.</p>', 'versions', 'Mostrar cómo el desarrollo incremental permite que usuarios y desarrolladores avancen en paralelo.'],
  ['Modelo en Espiral', 'Tradicional', '<p>Combina actividades de desarrollo con análisis de riesgo. Es iterativo: planificación, análisis de riesgo, ingeniería y evaluación.</p><p>En cada iteración se evalúan alternativas; los gestores intentan minimizar el riesgo.</p>', 'spiral', 'Asociar cada vuelta con decisiones y reducción de riesgo, sin convertir el esquema en una métrica cuantitativa.'],
  ['Modelo en Espiral: esquema de Boehm', 'Tradicional', '<p>Requerimientos y planificación inicial; comentarios y evaluación del cliente; análisis de riesgo; prototipos; sistema de ingeniería; decisión de seguir/no seguir.</p><p class="source">Boehm (1986)</p>', 'spiral-detail', 'Leer la espiral como un ciclo de aprendizaje con cliente, riesgo y decisión explícita de continuar.'],
  ['RUP — Rational Unified Process', 'Tradicional', '<p>Es un <em>framework</em> para describir procesos específicos. Cada ciclo abarca: concepción/planificación, elaboración, construcción y transición.</p><p>Su esencia es la iteración y cada iteración resulta en un entregable preferentemente ejecutable.</p>', 'rup', 'Introducir RUP como framework adaptable y enfatizar el entregable ejecutable por iteración.'],
  ['RUP — esquema visual', 'Tradicional', '<p class="lede">Rational Unified Process</p>', 'rup', 'Usar el diagrama para reforzar que las fases se atraviesan con intensidad variable y con iteraciones.'],
  ['Problemas de los Modelos Tradicionales', 'Límite', '<ul><li>Incumplimiento de plazos de entrega</li><li>Reducción de funcionalidades previstas</li><li>Difícil adaptación a cambios</li><li>Excesiva documentación</li></ul>', 'risks', 'Recapitular las limitaciones que preparan el cambio hacia métodos ágiles.'],
  ['Métodos Ágiles', 'Origen', '<p>En febrero de 2001, tras una reunión en Utah-EEUU, 17 expertos impulsaron el término “Ágil” aplicado al desarrollo.</p><p>Se buscaban valores y principios para desarrollar rápidamente y responder a cambios, como alternativa a procesos tradicionales.</p>', 'timeline', 'Dar contexto histórico sin presentar la reunión como una metodología única.'],
  ['Métodos Ágiles: definición', 'Origen', '<p>Las MAs promueven prácticas adaptativas en lugar de predictivas, como las MTs. Promueven adaptabilidad a cambios por sobre planeamiento estricto.</p>', 'adapt', 'Fijar la diferencia conceptual entre adaptación y predicción estricta.'],
  ['Métodos Ágiles: manifiesto', 'Valores', '<p class="lede">Según el manifiesto ágil se valora:</p>', 'manifesto', 'Presentar este slide como transición; los valores se detallan en los slides siguientes.'],
  ['Individuos e interacciones', 'Valores', '<p>Individuos e interacciones sobre proceso y herramientas.</p><p>La gente es el principal factor de éxito. Es más importante construir un buen equipo que el entorno; el equipo configura su entorno según sus necesidades.</p>', 'people', 'Conversar sobre la primacía del equipo y evitar interpretarlo como rechazo de procesos o herramientas.'],
  ['Software que funciona', 'Valores', '<p>Desarrollar software que funciona más que conseguir buena documentación.</p><p>No producir documentos salvo que sean necesarios de forma inmediata para una decisión importante; deben ser breves y fundamentales.</p>', 'working', 'Aclarar que el valor prioriza software funcionando, no que elimina toda documentación.'],
  ['Colaboración con el cliente', 'Valores', '<p>La colaboración con el cliente más que la negociación de un contrato.</p><p>La interacción constante marca la marcha del proyecto y asegura su éxito.</p>', 'collab', 'Enfatizar la colaboración continua como mecanismo de dirección del proyecto.'],
  ['Responder a los cambios', 'Valores', '<p>Responder a cambios más que seguir estrictamente un plan.</p><p>Los cambios pueden aparecer en requisitos, tecnología o equipo. La planificación debe ser flexible y abierta.</p>', 'change', 'Diferenciar flexibilidad de ausencia de planificación.'],
  ['Agilidad vs. proceso', 'Equilibrio', '<ul><li>CMM/CMMI y XP pueden complementarse.</li><li>Los métodos ágiles coinciden con la esencia del mejoramiento de procesos bajo una interpretación menos literal.</li><li>Enfatizan gestión de proyectos, no gestión de procesos.</li></ul>', 'balance', 'Evitar la falsa dicotomía: agilidad y mejora de procesos pueden complementarse.'],
  ['Interrogantes', 'Equilibrio', '<ul><li>¿Resuelven los métodos ágiles todos los problemas?</li><li>¿Son aplicables a todo desarrollo?</li><li>¿Cuánta agilidad? ¿Cuánto proceso?</li></ul><p><strong>Desafío:</strong> encontrar equilibrio.</p><p>Modelos balanceados y mecanismos para selección, adaptación, implantación y adopción.</p>', 'questions', 'Usar las preguntas para introducir juicio contextual y evitar respuestas absolutas.'],
  ['Metodologías Ágiles', 'Panorama', '<p>Adaptive Software Development (ASD) · Programación Extrema (XP) · SCRUM</p>', 'methods', 'Anunciar el estudio de ASD, XP y Scrum como ejemplos con alcances distintos.'],
  ['Adaptive Software Development', 'ASD', '<p>Desarrollado por J. Highsmith en 2000.</p><blockquote>“Balancearse en el borde del Caos”</blockquote><p>Equilibrio entre creatividad e innovación y administración.</p>', 'asd', 'Explicar la metáfora como equilibrio operativo, no como invitación al desorden.'],
  ['Proceso del ASD', 'ASD', '<p class="lede">Ciclo adaptativo</p>', 'asd-cycle', 'Señalar el carácter cíclico del proceso ASD y vincularlo con la idea de adaptación.'],
  ['Uso actual del ASD', 'ASD', '<p>Casi no se utiliza porque no especifica en detalle pautas de desarrollo y gestión. Puede complementarse con otra metodología mejor definida.</p><p>Provee conceptos sobre sistemas complejos, trabajo colaborativo y agilidad administrativa.</p>', 'asd-use', 'Presentar la limitación de especificidad y el valor conceptual que conserva.'],
  ['Programación Extrema (XP)', 'XP', '<p>Desarrollada por K. Beck en 1999. Probablemente la metodología ágil más conocida y utilizada.</p><p>Combina prácticas conocidas de manera innovadora y las lleva a niveles extremos.</p>', 'xp', 'Introducir XP desde su origen, popularidad y combinación intensiva de prácticas.'],
  ['Programación Extrema: esquema', 'XP', '<p class="lede">Mapa de prácticas XP</p>', 'xp-map', 'Usar el esquema como mapa antes de detallar las prácticas en los slides siguientes.'],
  ['Prácticas de XP I', 'XP', '<div class="practice-grid"><b>Planificación incremental</b><b>Entregas pequeñas</b><b>Diseño simple</b><b>Desarrollo previamente probado</b><b>Refactorización</b></div><p>Historias en tarjetas, tareas, valor temprano, pruebas automatizadas y mejora continua del código.</p>', 'practices', 'Recorrer las prácticas como un sistema coherente de feedback, entrega temprana y código mantenible.'],
  ['Prácticas de XP II', 'XP', '<div class="practice-grid"><b>Programación en pares</b><b>Propiedad colectiva</b><b>Integración continua</b><b>Ritmo sostenible</b><b>Cliente presente</b></div><p>Revisión entre pares, código compartido, integración frecuente, límites a horas extra y cliente como miembro del equipo.</p>', 'practices', 'Destacar que XP distribuye conocimiento, integra pronto y mantiene contacto directo con el cliente.'],
  ['Uso actual de XP', 'XP', '<p>El 38% del mercado “ágil” utiliza XP. Esto se atribuye a prácticas bien definidas. En Agile Alliance existe amplia mayoría de usuarios de XP.</p>', 'stat', 'Presentar el dato exactamente como aparece, sin extenderlo a una afirmación actualizada.'],
  ['SCRUM', 'Scrum', '<p>Scrum es la metodología más utilizada por equipos ágiles. Es una manera de trabajar en equipo con resultado incremental: un entregable.</p><p>Los periodos cortos se denominan <em>sprints</em> y son la base del método.</p>', 'scrum', 'Introducir Scrum desde la cadencia corta, el trabajo en equipo y el entregable incremental.'],
  ['SCRUM — actividades', 'Scrum', '<p>Sprint Planning · Daily · Sprint Review · Sprint Retrospective</p>', 'scrum-cycle', 'Explicar cada actividad como preparación, sincronización, inspección y mejora.'],
  ['SCRUM — herramientas', 'Scrum', '<p>Product Backlog · Sprint Backlog · Burn Down</p>', 'scrum-tools', 'Diferenciar el inventario de producto, el compromiso del sprint y la visualización de trabajo restante.'],
  ['SCRUM — roles', 'Scrum', '<p>Product Owner · Scrum Master · Team (equipo de desarrollo)</p>', 'scrum-roles', 'Presentar las responsabilidades como roles complementarios, sin agregar definiciones externas al material.'],
  ['SCRUM — esquema visual', 'Scrum', '<p class="lede">Actividades, herramientas y roles en un mismo ciclo.</p>', 'scrum-board', 'Utilizar el esquema como integración visual de actividades, herramientas y roles ya explicados.'],
  ['Uso actual de SCRUM', 'Scrum', '<p>Después de XP, Scrum es uno de los enfoques más utilizados, aunque lejos de XP.</p><p>Se investiga integrar XP y Scrum: Scrum provee marco de gestión y XP prácticas bien definidas.</p>', 'scrum-xp', 'Presentar la complementariedad propuesta por la fuente y no convertirla en prescripción universal.'],
  ['Ventajas de las MAs', 'Evaluación', '<ul><li>Iteraciones en ciclos cortos</li><li>Límites de tiempo de dos a ocho semanas</li><li>Adaptable a nuevos riesgos</li><li>Orientación hacia las personas</li><li>Estilo de trabajo en equipo</li></ul>', 'advantages', 'Recorrer las ventajas y subrayar la relación entre ciclos cortos, feedback y adaptación.'],
  ['Desventajas de las MAs', 'Evaluación', '<ul><li>Adaptarse al cambio puede llevar al caos.</li><li>Es difícil mantener el interés de clientes.</li><li>Las prioridades pueden ser difíciles con múltiples actores.</li><li>La simplicidad implica trabajo extra.</li><li>Los contratos pueden ser un problema.</li></ul>', 'risks', 'Equilibrar la presentación mostrando límites y costos de adopción.'],
  ['Métodos Ágiles vs. Tradicionales', 'Comparación', '<div class="comparison"><strong>Ágiles</strong><span>Tradicionales</span><p>Heurísticas · cambios · imposición interna · proceso menos controlado · contrato flexible · cliente en el equipo · grupos pequeños · menor énfasis en arquitectura</p><p>Normas · resistencia a cambios · imposición externa · proceso más controlado · contrato prefijado · cliente en reuniones · grupos grandes/distribuidos · arquitectura esencial y modelada</p></div>', 'comparison', 'Leer cada fila como contraste de énfasis, no como regla sin excepciones.'],
  ['Conclusiones', 'Cierre', '<p>Las ventajas de las MAs proveen un marco aplicable a entornos sin procesos definidos o vagos, en desarrollo y aseguramiento de calidad.</p><p>Se ajustan a sistemas pequeños y medianos o productos PC, adecuados a proyectos habituales de la región.</p>', 'conclusion', 'Cerrar con la aplicabilidad contextual que declara la fuente y retomar el objetivo de elegir un balance.'],
  ['Muchas gracias', 'Cierre', '<p class="lede">Muchas gracias</p>', 'end', 'Abrir el espacio para preguntas y pedir que los estudiantes expresen diferencias entre modelos tradicionales y ágiles.']
].map(([title, eyebrow, body, visual, note]) => ({ title, eyebrow, body, visual, note }));

const stage = document.querySelector('#stage');
const index = document.querySelector('#slide-index');
const notes = document.querySelector('#speaker-notes');
let current = 0;

function visualMarkup(kind) {
  const labels = {
    objectives: ['Entender', 'Conocer', 'Entregar'], roadmap: ['Introducción', 'Características', 'Manifiesto', 'ASD · Scrum · XP'], triad: ['Calidad', 'Productividad', 'Riesgos'], layers: ['Capacidades', 'Calidad', 'Herramientas', 'Proceso'], four: ['Complejidad', 'Conformidad', 'Cambios', 'Invisibilidad'], families: ['TRADICIONALES', 'ÁGILES'], benefits: ['Construcción rápida', 'Visión común', 'Menos incertidumbre'], risks: ['Plazos', 'Funcionalidad', 'Cambios', 'Documentación'], methods: ['ASD', 'XP', 'SCRUM'], practices: ['Práctica 01', 'Práctica 02', 'Práctica 03', 'Práctica 04', 'Práctica 05'], advantages: ['Ciclos cortos', 'Riesgos', 'Personas', 'Equipo']
  };
  if (kind === 'quote') return '<div class="quote-mark">“</div><div class="visual-quote">Proceso = actividades + tareas + evolución</div><small>Sommerville</small>';
  if (kind === 'stat') return '<div class="stat">38<span>%</span></div><p>dato visible en la fuente para el uso actual de XP</p>';
  if (kind === 'timeline') return '<div class="timeline"><b>2001</b><span>Utah · 17 expertos</span><strong>Ágil</strong></div>';
  if (kind === 'waterfall' || kind === 'waterfall-loop') return '<div class="flow">' + ['Análisis', 'Diseño', 'Código', 'Testing', 'Operación'].map((x, i) => `<span>${String(i + 1).padStart(2, '0')} ${x}</span>`).join('') + '</div><small>flujo lineal · en la práctica aparecen retornos</small>';
  if (kind === 'prototype') return '<div class="cycle"><span>Requerimientos</span><span>Prototipo</span><span>Testing</span><span>Revisión</span><span>Entrega</span></div>';
  if (kind === 'parallel' || kind === 'versions') return '<div class="lanes"><b>DESARROLLO</b><span>V1 → V2 → V3</span><b>PRODUCCIÓN</b><span>Usar V1 → V2 → V3</span></div>';
  if (kind.startsWith('spiral')) return '<svg class="diagram" viewBox="0 0 420 280" role="img" aria-label="Ciclo espiral de planificación, riesgo, ingeniería y evaluación"><path d="M210 140c0-42 66-42 66 0s-132 70-132 0 198-108 198 0-264 150-264 0"/><g><text x="178" y="38">RIESGO</text><text x="285" y="150">INGENIERÍA</text><text x="154" y="260">EVALUACIÓN</text><text x="22" y="150">PLANIFICACIÓN</text></g></svg>';
  if (kind === 'rup' || kind === 'asd-cycle' || kind === 'scrum-cycle') return '<div class="orbit"><i>01</i><i>02</i><i>03</i><i>04</i><strong>' + (kind === 'rup' ? 'RUP' : kind === 'asd-cycle' ? 'ASD' : 'SPRINT') + '</strong></div>';
  if (kind === 'xp-map') return '<div class="map"><b>XP</b><span>Feedback</span><span>Calidad</span><span>Entrega</span><span>Equipo</span></div>';
  if (kind === 'scrum-board') return '<div class="board"><b>BACKLOG</b><b>SPRINT</b><b>ENTREGABLE</b><span>PLAN · DAILY · REVIEW · RETRO</span></div>';
  if (kind === 'comparison') return '<div class="compare-visual"><b>ÁGILES</b><b>TRADICIONALES</b><span>adaptación</span><span>predicción</span><span>cliente cerca</span><span>cliente por reuniones</span></div>';
  if (kind === 'end') return '<div class="end-mark">II</div>';
  if (kind === 'asd') return '<div class="edge"><span>CREATIVIDAD</span><strong>BORDE DEL CAOS</strong><span>ADMINISTRACIÓN</span></div>';
  if (kind === 'scrum') return '<div class="sprint"><strong>SPRINT</strong><span>trabajo en equipo</span><span>entregable</span></div>';
  if (kind === 'scrum-tools' || kind === 'scrum-roles' || kind === 'scrum-xp') return '<div class="stack">' + labels.methods.map(x => `<span>${x}</span>`).join('') + '</div>';
  const items = labels[kind] || [kind.replace('-', ' '), 'Iteración', 'Feedback'];
  return `<div class="visual-grid">${items.map((x, i) => `<span><b>${String(i + 1).padStart(2, '0')}</b>${x}</span>`).join('')}</div>`;
}

function render() {
  const slide = slides[current];
  stage.innerHTML = `<article class="slide slide-${current + 1}" aria-labelledby="slide-title"><div class="slide-copy"><p class="eyebrow">${String(current + 1).padStart(2, '0')} · ${slide.eyebrow}</p><h1 id="slide-title">${slide.title}</h1><div class="content">${slide.body}</div></div><div class="visual"><p class="visual-label">UNIDAD II / REGISTRO ${String(current + 1).padStart(2, '0')}</p>${visualMarkup(slide.visual)}</div><span class="slide-number">${String(current + 1).padStart(2, '0')}</span></article>`;
  document.querySelector('#counter').textContent = `${String(current + 1).padStart(2, '0')} / ${String(slides.length).padStart(2, '0')}`;
  document.querySelector('#progress').style.width = `${((current + 1) / slides.length) * 100}%`;
  document.querySelector('#progress').setAttribute('aria-valuenow', current + 1);
  notes.innerHTML = `<div class="note"><strong>Slide ${current + 1}: ${slide.title}</strong><p>${slide.note}</p></div>`;
  document.querySelectorAll('.index-item').forEach((button, i) => button.classList.toggle('active', i === current));
  history.replaceState(null, '', `#slide-${current + 1}`);
}
function goTo(position) { current = Math.max(0, Math.min(slides.length - 1, position)); render(); document.querySelector('#main-content').focus({ preventScroll: true }); }
function toggle(id, force) { const panel = document.querySelector(id); const open = typeof force === 'boolean' ? force : !panel.classList.contains('open'); panel.classList.toggle('open', open); panel.setAttribute('aria-hidden', String(!open)); if (open) panel.querySelector('button, [href]')?.focus(); }
slides.forEach((slide, i) => { const button = document.createElement('button'); button.className = 'index-item'; button.type = 'button'; button.textContent = `${String(i + 1).padStart(2, '0')} · ${slide.title}`; button.addEventListener('click', () => { goTo(i); toggle('#index-panel', false); }); index.append(button); });
document.querySelector('#next').addEventListener('click', () => goTo(current + 1));
document.querySelector('#previous').addEventListener('click', () => goTo(current - 1));
document.querySelector('#index-toggle').addEventListener('click', () => toggle('#index-panel'));
document.querySelector('#notes-toggle').addEventListener('click', () => toggle('#notes-panel'));
document.querySelectorAll('.close-panel').forEach(button => button.addEventListener('click', () => toggle(`#${button.dataset.close}`, false)));
document.querySelector('#fullscreen').addEventListener('click', () => document.documentElement.requestFullscreen?.());
document.addEventListener('keydown', event => { if (event.key === 'Escape') { toggle('#index-panel', false); toggle('#notes-panel', false); } if (['ArrowRight', 'PageDown', ' '].includes(event.key)) { event.preventDefault(); goTo(current + 1); } if (['ArrowLeft', 'PageUp'].includes(event.key)) { event.preventDefault(); goTo(current - 1); } if (event.key === 'Home') { event.preventDefault(); goTo(0); } if (event.key === 'End') { event.preventDefault(); goTo(slides.length - 1); } if (event.key.toLowerCase() === 'n') toggle('#notes-panel'); if (event.key.toLowerCase() === 'i') toggle('#index-panel'); });
window.addEventListener('hashchange', () => { const match = location.hash.match(/slide-(\d+)/); if (match) goTo(Number(match[1]) - 1); });
const initial = location.hash.match(/slide-(\d+)/); if (initial) current = Number(initial[1]) - 1; render();
