const slides = [
  {
    "title": "Ingeniería de Software I",
    "eyebrow": "01 · Apertura",
    "body": "<div class=\"card card--hero\"><p class=\"lede\">Unidad II · T3 - Requerimientos de Software</p><p>Prof. Lic. Guillermo Jacobo González Rodas Mst. PMP</p></div>",
    "note": "<strong>Desarrollo:</strong> **Ingeniería de Software I:** se presenta la materia dentro del contexto de la carrera y se anuncia la unidad de la sesión. **Unidad II · T3 - Requerimientos de Software:** el tema central es qué necesita realmente un sistema antes de construirlo; por ejemplo, un sistema de reservas de hotel necesita saber qué habitaciones hay, en qué fechas y qué servicios se contratan. **Presentación del docente:** la portada identifica a quien dicta la unidad, se presenta e invita a pensar en qué debe hacer un sistema antes de diseñarlo. <br><br><strong>Reflexión docente:</strong> los requerimientos son la base de todo el proyecto: un error aquí se multiplica en las fases posteriores. <br><br><strong>Pregunta desafío:</strong> ¿qué pasa si construimos un sistema sin definir bien sus requerimientos? <br><br><strong>Respuestas posibles:</strong> 1. Se construye algo que el cliente no pidió. 2. Se descubren errores tarde y el retrabajo es costoso. 3. Se superan plazos y presupuesto. <br><br><strong>Advertencia:</strong> no confundir requerimientos con diseño; los requerimientos describen el QUÉ, no el CÓMO."
  },
  {
    "title": "Objetivos",
    "eyebrow": "02 · Objetivos",
    "body": "<div class=\"card-grid card-grid--3\"><div class=\"card card--num\"><span class=\"number\">01</span><p>Comprender qué son los requerimientos de software y por qué son importantes.</p></div><div class=\"card card--num\"><span class=\"number\">02</span><p>Familiarizarse con los diferentes tipos de requerimientos.</p></div><div class=\"card card--num\"><span class=\"number\">03</span><p>Aprender técnicas y herramientas para la obtención, análisis y gestión de requerimientos.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> **Comprender qué son los requerimientos de software y por qué son importantes:** al terminar la unidad el estudiante explica qué es un requerimiento y justifica su impacto; por ejemplo, en un sistema de biblioteca, saber que \"registrar préstamos\" es un requerimiento evita construir módulos innecesarios. **Familiarizarse con los diferentes tipos de requerimientos:** distinguir los funcionales (qué hace el sistema) de los no funcionales (cómo debe comportarse); por ejemplo, en un portal de pagos, \"procesar el pago\" (funcional) frente a \"cifrar los datos de la tarjeta\" (no funcional). **Aprender técnicas y herramientas para la obtención, análisis y gestión de requerimientos:** por ejemplo, usar entrevistas para relevar el trabajo actual de una empresa de repartos y herramientas como JIRA para registrar, priorizar y seguir los requerimientos. <br><br><strong>Reflexión docente:</strong> estos objetivos estructuran el recorrido de la unidad y dan criterio para evaluar el avance. <br><br><strong>Pregunta desafío:</strong> ¿cuál de los tres objetivos les parece más difícil de lograr y por qué? <br><br><strong>Respuestas posibles:</strong> 1. La obtención, porque los usuarios no siempre saben qué quieren. 2. El análisis, por la cantidad de fuentes y prioridades. 3. La gestión, porque los cambios son constantes. <br><br><strong>Advertencia:</strong> los objetivos son de aprendizaje; no describen aún contenido técnico."
  },
  {
    "title": "Contenido",
    "eyebrow": "03 · Recorrido",
    "body": "<div class=\"sequence-card\" aria-label=\"Recorrido de la unidad\"><div class=\"sequence-step\"><span class=\"sequence-index\">01</span><strong>Requerimientos de Software</strong></div><div class=\"sequence-step\"><span class=\"sequence-index\">02</span><strong>Tipos de Requerimientos</strong></div><div class=\"sequence-step\"><span class=\"sequence-index\">03</span><strong>Ingeniería de Requerimientos</strong></div><div class=\"sequence-step\"><span class=\"sequence-index\">04</span><strong>Proceso de Requerimientos</strong><small>Obtención, Análisis, Especificación, Verificación y Validación de Requerimientos</small></div><div class=\"sequence-step\"><span class=\"sequence-index\">05</span><strong>Gestión de Requerimientos</strong></div></div>",
    "note": "<strong>Desarrollo:</strong> **Requerimientos de Software:** primer bloque del mapa de la unidad: qué es un requerimiento y por qué es la base del proyecto. **Tipos de Requerimientos:** su primera clasificación; por ejemplo, en un sistema de pedidos a domicilio, \"agregar productos al carrito\" (funcional) y \"responder en menos de 2 segundos\" (no funcional). **Ingeniería de Requerimientos:** la disciplina que reúne las actividades para descubrir, documentar y mantener los requisitos. **Proceso de Requerimientos:** agrupa las cinco actividades que lo componen: obtención (entrevistar al personal de cocina y de reparto), análisis (clasificar y priorizar lo pedido), especificación (redactar el documento ERS), verificación (comprobar que el documento es correcto) y validación (confirmar con el cliente que es lo que quiere). **Gestión de Requerimientos:** controlar los cambios; por ejemplo, cuando el restaurante incorpora un nuevo método de pago. <br><br><strong>Reflexión docente:</strong> el proceso no es lineal estricto; las actividades se solapan y retroalimentan. <br><br><strong>Pregunta desafío:</strong> ¿por qué la verificación y la validación son pasos distintos? <br><br><strong>Respuestas posibles:</strong> 1. Verificar es comprobar que se especificó bien; validar es confirmar que es lo que el cliente necesita. 2. Se verifican contra el documento; se valida contra el usuario. 3. Ambas se complementan en el proceso. <br><br><strong>Advertencia:</strong> la gestión atraviesa todo el proceso; no es una etapa final."
  },
  {
    "title": "¿Qué Es un Requerimiento de Software?",
    "eyebrow": "04 · Definición",
    "body": "<div class=\"card-grid card-grid--2\" style=\"gap: 2rem; align-items: stretch;\"><div class=\"card\"><p><strong>Definición (Swebok):</strong></p><p>«Propiedad que debe ser exhibida por un software para resolver un problema particular.»</p></div><div class=\"card\"><p><strong>Definición (usuario):</strong></p><p>«Condición o capacidad que necesita el usuario para resolver un problema o conseguir un objetivo determinado.»</p></div></div><div class=\"card\" style=\"margin-top: 1rem;\"><p><strong>ERS</strong> – Documento formal de Especificación de Requisitos Software</p><p style=\"margin-top: .25rem;\"><strong>SRS</strong> – Software Requirements Specification</p></div><p class=\"reference\">IEEE Computer Society. Guide to the Software Engineering Body of Knowledge (SWEBOK). IEEE, 2014.</p>",
    "note": "<strong>Desarrollo:</strong> **Definición (Swebok):** el software debe exhibir una propiedad que resuelve un problema particular; por ejemplo, en un sistema de facturación, \"el sistema debe calcular el IVA automáticamente\" es una propiedad que el software exhibe. **Definición (usuario):** es una condición o capacidad que el usuario necesita para resolver un problema; por ejemplo, en una biblioteca digital, el usuario necesita \"buscar un libro por título\". **ERS:** documento formal de Especificación de Requisitos Software. **SRS:** Software Requirements Specification; es el mismo documento con su nombre en inglés. <br><br><strong>Reflexión docente:</strong> la doble definición muestra que un requerimiento se puede ver desde el sistema y desde el negocio; ambos deben coincidir. <br><br><strong>Pregunta desafío:</strong> ¿un requerimiento describe lo que el sistema hace o lo que el usuario necesita? <br><br><strong>Respuestas posibles:</strong> 1. Ambas cosas, según la perspectiva. 2. Lo que el sistema hace para satisfacer la necesidad. 3. Lo que el usuario necesita, traducido a capacidad del sistema. <br><br><strong>Advertencia:</strong> Swebok es la guía del cuerpo de conocimiento de la ingeniería de software; es una referencia académica."
  },
  {
    "title": "Características de los Requerimientos",
    "eyebrow": "05 · Características",
    "body": "<div class=\"card\"><p>Los requisitos de un software suelen ser una <strong>combinación compleja</strong> de los requisitos de <strong>diferentes personas</strong> en diferentes niveles de una organización y del entorno en el cual operará el software.</p></div><div class=\"card-grid card-grid--2\" style=\"margin-top: 1rem;\"><div class=\"card card--num\"><span class=\"number\">01</span><p><strong>Verificable:</strong> es fundamental que un requisito pueda comprobarse.</p></div><div class=\"card card--num\"><span class=\"number\">02</span><p><strong>Prioridad:</strong> atributo que les caracteriza.</p></div><div class=\"card card--num\"><span class=\"number\">03</span><p><strong>Identificador único:</strong> atributo que les caracteriza.</p></div><div class=\"card card--num\"><span class=\"number\">04</span><p><strong>Claros y no ambiguos:</strong> lo más que se pueda.</p></div><div class=\"card card--num\"><span class=\"number\">05</span><p><strong>Cuantificables</strong> (si es posible).</p></div></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> **Combinación compleja:** los requisitos reúnen las necesidades de diferentes personas en distintos niveles de la organización y del entorno en el que operará el software; por ejemplo, en un hospital, el sistema de turnos combina lo que pide la administración (controlar tiempos de espera), el personal médico (acceso rápido al historial) y la ley (proteger los datos del paciente). **Verificable:** es fundamental que un requisito pueda comprobarse; por ejemplo, \"el sistema debe ser rápido\" no es verificable, pero \"la pasarela confirma el pago en menos de 3 segundos\" sí lo es. **Prioridad e identificador único:** atributos que caracterizan a cada requisito, permiten ordenar el desarrollo y rastrear su origen; por ejemplo, asignar prioridad \"alta\" a la facturación electrónica y un código como RF-001. **Claros y no ambiguos, y cuantificables (si es posible):** redactar de modo que haya una sola interpretación y expresar con números lo medible; por ejemplo, \"soporte hasta 1.000 usuarios concurrentes\" en lugar de \"muchos usuarios\". <br><br><strong>Reflexión docente:</strong> la verificabilidad es clave: un requerimiento que no se puede comprobar no se puede aceptar ni probar. <br><br><strong>Pregunta desafío:</strong> ¿cómo harían verificable el requerimiento \"el sistema debe ser fácil de usar\"? <br><br><strong>Respuestas posibles:</strong> 1. Definiendo métricas (tiempo de aprendizaje, tasa de error). 2. Con pruebas de usabilidad con usuarios. 3. Con criterios de aceptación concretos. <br><br><strong>Advertencia:</strong> la prioridad y el identificador único ayudan a gestionar cambios y trazabilidad."
  },
  {
    "title": "Tipos de Requerimientos",
    "eyebrow": "06 · Clasificación",
    "body": "<div class=\"card-grid card-grid--2\" style=\"gap: 2rem;\"><div class=\"card card--hero\"><h3>Requerimientos Funcionales</h3><p>Describen qué debe hacer el sistema.</p></div><div class=\"card card--hero\"><h3>Requerimientos No Funcionales</h3><p>Describen restricciones y calidad.</p></div></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> **Requerimientos Funcionales:** describen qué hace el sistema, sus servicios y su reacción ante las entradas; por ejemplo, en una biblioteca, \"el sistema presta un libro y reduce el stock disponible\". **Requerimientos No Funcionales:** describen restricciones y propiedades de calidad; por ejemplo, \"la consulta del catálogo responde en menos de 2 segundos\" o \"los datos de los socios se almacenan cifrados\". Ambos tipos conviven: un sistema con buenas funciones pero mala usabilidad o poca seguridad falla en la práctica. <br><br><strong>Reflexión docente:</strong> ambos tipos son necesarios; centrarse solo en los funcionales deja el sistema inusable. <br><br><strong>Pregunta desafío:</strong> ¿cuál de los dos tipos se suele olvidar en proyectos reales? <br><br><strong>Respuestas posibles:</strong> 1. Los no funcionales, por ser menos visibles. 2. Los funcionales, cuando el cliente describe restricciones. 3. Depende de cada proyecto. <br><br><strong>Advertencia:</strong> esta clasificación se profundizará en los slides siguientes."
  },
  {
    "title": "Requerimientos Funcionales",
    "eyebrow": "07 · Funcionales",
    "body": "<div class=\"card\"><p>Se refiere a las <strong>capacidades del sistema</strong>.</p><ul><li>Describen las <strong>funciones</strong> que lleva a cabo el software, cómo debe reaccionar ante ciertas entradas y cómo debe comportarse en situaciones particulares.</li><li>Describen la <strong>funcionalidad o los servicios</strong> que se espera que éste provea.</li><li>Son <strong>declaraciones de los servicios</strong> que proveerá el sistema, de la manera en que éste reaccionará a entradas particulares.</li><li>En algunos casos, los requerimientos funcionales de los sistemas también declaran explícitamente lo que el sistema <strong>NO debe hacer</strong>.</li></ul></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> **Capacidades del sistema:** los requerimientos funcionales expresan qué sabe hacer el software. **Reacción ante ciertas entradas y comportamiento en situaciones particulares:** describen cómo responde el sistema; por ejemplo, en un cajero automático, ante la entrada \"saldo insuficiente\" el sistema no dispensa dinero y muestra un mensaje. **Funcionalidad o servicios que se espera que provea:** declaran los servicios del sistema; por ejemplo, en un sistema de reservas, \"el sistema registra la reserva y envía una confirmación por correo\". **Lo que el sistema NO debe hacer:** también se declaran exclusiones; por ejemplo, en un sistema de préstamos, \"el sistema no permite aprobar un crédito sin verificación de identidad\". <br><br><strong>Reflexión docente:</strong> los requerimientos funcionales describen servicios, no la implementación interna. <br><br><strong>Pregunta desafío:</strong> ¿\"el sistema usa una base de datos MySQL\" es un requerimiento funcional? <br><br><strong>Respuestas posibles:</strong> 1. No, es una decisión de diseño. 2. Podría ser una restricción técnica (no funcional). 3. Solo es funcional si describe un comportamiento observable. <br><br><strong>Advertencia:</strong> no mezclar requerimientos con soluciones tecnológicas."
  },
  {
    "title": "Ejemplos de Requerimientos Funcionales",
    "eyebrow": "08 · Ejemplos",
    "body": "<div class=\"card\"><p><strong>RF1.</strong> El sistema controlará el acceso y lo permitirá solamente a usuarios autorizados. Los usuarios deben ingresar al sistema con un nombre de usuario y contraseña.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>RF2.</strong> El campo país consistirá en una lista de preselección. El país asociado a una dirección debe ser previamente registrado en el sistema.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>RF3.</strong> El campo estado, provincia o departamento consistirá en una lista de preselección. A los usuarios se les presentará únicamente los departamentos asociados al país seleccionado previamente.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>RF4.</strong> El sistema enviará un correo electrónico cuando se registre alguna de las siguientes transacciones: pedido de venta de cliente, emisión de factura a cliente y registro de pago de cliente.</p></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> **RF1. Control de acceso:** el sistema solo permite ingresar a usuarios autorizados con usuario y contraseña; por ejemplo, en un sistema bancario, \"solo los usuarios autenticados pueden ver su saldo\". **RF2. País de preselección:** el país asociado a una dirección debe estar previamente registrado; por ejemplo, en un comercio electrónico, \"el cliente elige el país desde una lista y no lo escribe a mano\". **RF3. Departamentos según el país:** solo se muestran los departamentos del país seleccionado; por ejemplo, \"al elegir Paraguay, la lista muestra únicamente los departamentos de Paraguay\". **RF4. Envío de correos por transacción:** el sistema notifica al registrarse pedidos, facturas y pagos; por ejemplo, \"el sistema envía un correo al cliente cuando su pedido pasa a estado enviado\". Todos siguen la forma \"el sistema + verbo + condición\", la redacción típica de un requerimiento funcional. <br><br><strong>Reflexión docente:</strong> los ejemplos muestran la redacción típica: \"el sistema + verbo + condición\". <br><br><strong>Pregunta desafío:</strong> ¿qué características comparten todos estos requerimientos? <br><br><strong>Respuestas posibles:</strong> 1. Están redactados en tercera persona. 2. Son verificables y específicos. 3. Describen una acción observable del sistema. <br><br><strong>Advertencia:</strong> no copiar estos ejemplos tal cual; adaptarlos al dominio de cada proyecto."
  },
  {
    "title": "Requerimientos No Funcionales",
    "eyebrow": "09 · No funcionales",
    "body": "<div class=\"card\"><p>Se refiere a las <strong>restricciones y requisitos de calidad</strong>.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p><strong>Restricciones sobre las funciones o servicios</strong> ofrecidos por el sistema. Incluyen restricciones de <strong>tiempo</strong>, sobre el <strong>proceso de desarrollo</strong>, <strong>estándares</strong>, etc.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p>Son aquellos requerimientos que <strong>no se refieren directamente</strong> a las funciones específicas que entrega el sistema, sino a las <strong>propiedades emergentes</strong> de éste como la fiabilidad, la respuesta en el tiempo y la capacidad de almacenamiento.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p>De forma alternativa, definen las <strong>restricciones del sistema</strong> como la capacidad de los dispositivos de entrada/salida y la representación de datos que se utiliza en la interface del sistema.</p></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> **Restricciones y requisitos de calidad:** los no funcionales no dicen qué hace el sistema, sino bajo qué condiciones; por ejemplo, en un sistema de reservas, \"el sistema no debe caerse durante el horario pico\". **Restricciones de tiempo, del proceso de desarrollo y estándares:** por ejemplo, \"cada pantalla debe responder en menos de 2 segundos\" o \"el código debe seguir el estándar interno de la organización\". **Propiedades emergentes:** fiabilidad, tiempo de respuesta y capacidad de almacenamiento son propiedades del sistema completo, no de una función puntual; por ejemplo, \"el sistema debe soportar 500.000 registros de historial\". **Restricciones de dispositivos de entrada/salida y representación de datos:** por ejemplo, \"la interfaz debe funcionar en pantallas táctiles\" o \"las fechas se representan en formato dd/mm/aaaa\". <br><br><strong>Reflexión docente:</strong> los no funcionales afectan propiedades emergentes del sistema, no funciones puntuales. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre una restricción y un requisito de calidad? <br><br><strong>Respuestas posibles:</strong> 1. La restricción limita (hardware, estándares); la calidad define propiedades (rendimiento, fiabilidad). 2. Ambas son no funcionales. 3. Se complementan. <br><br><strong>Advertencia:</strong> los no funcionales son difíciles de cuantificar; conviene hacerlo cuanto antes."
  },
  {
    "title": "Requerimientos No Funcionales",
    "eyebrow": "10 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/requerimientos-no-funcionales.png\" alt=\"Clasificación de los requerimientos no funcionales: del producto, organizacionales y externos\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> **Clasificación de los no funcionales:** el diagrama organiza los requerimientos no funcionales en tres grupos. **Producto:** propiedades del propio sistema; por ejemplo, tiempos de respuesta y seguridad en un portal de pagos. **Organizacionales:** políticas y estándares de la empresa; por ejemplo, \"los entregables seguirán la norma interna de desarrollo\". **Externos:** normativa legal y regulación; por ejemplo, \"la aplicación debe cumplir la ley de protección de datos personales\". El diagrama resume la clasificación y sirve de referencia durante toda la unidad. <br><br><strong>Reflexión docente:</strong> la imagen resume la clasificación y sirve de referencia durante toda la unidad. <br><br><strong>Pregunta desafío:</strong> ¿en qué categoría ubicarían \"el sistema debe usar estándares de la organización\"? <br><br><strong>Respuestas posibles:</strong> 1. Organizacionales. 2. De producto. 3. Externos. <br><br><strong>Advertencia:</strong> la clasificación es orientativa; algunos requisitos pueden pertenecer a más de una categoría."
  },
  {
    "title": "Ejemplos de Requerimientos No Funcionales",
    "eyebrow": "11 · Ejemplos",
    "body": "<div class=\"card\"><p><strong>Requerimientos del Producto</strong></p><p><strong>RNF1.</strong> La interfaz de usuario será implementada como HTML simple sin frames ni applets Java.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Requerimientos Organizacionales</strong></p><p><strong>RNF2.</strong> El proceso de desarrollo y los entregables serán conformes a lo establecido en METRICA v3.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Requerimientos Externos</strong></p><p><strong>RNF3.</strong> El sistema no registrará ninguna información personal de los clientes salvo su nombre y número de referencia, respetando lo establecido en la Ley Orgánica de Protección de Datos (LOPD).</p></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> **Requerimientos del Producto (RNF1):** la interfaz se implementará como HTML simple, sin frames ni applets Java; por ejemplo, en un sistema interno, esta restricción garantiza la compatibilidad con los navegadores de la organización. **Requerimientos Organizacionales (RNF2):** el proceso de desarrollo y los entregables serán conformes a lo establecido en METRICA v3; por ejemplo, en un proyecto gubernamental, cumplir la metodología oficial del organismo. **Requerimientos Externos (RNF3):** no se registrará información personal de los clientes salvo nombre y número de referencia, respetando la LOPD; por ejemplo, en un sistema de ventas, no se guardan datos innecesarios como la dirección completa si no hacen falta. Cada grupo condiciona al sistema desde una fuente distinta: el producto, la organización y la ley. <br><br><strong>Reflexión docente:</strong> los ejemplos muestran cómo la normativa y la organización condicionan el sistema. <br><br><strong>Pregunta desafío:</strong> ¿por qué un requerimiento externo puede ser obligatorio por ley? <br><br><strong>Respuestas posibles:</strong> 1. Porque violarlo implica sanciones. 2. Porque afecta a terceros (clientes, pacientes). 3. Porque limita qué datos se pueden almacenar. <br><br><strong>Advertencia:</strong> la LOPD y METRICA v3 son ejemplos concretos; cada proyecto tendrá su normativa."
  },
  {
    "title": "Ejemplo de Requerimientos",
    "eyebrow": "12 · Ejemplo",
    "body": "<img class=\"figure-img\" src=\"assets/ejemplo-requerimientos.jpg\" alt=\"Ejemplo ilustrado de requerimientos de software\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> **Ejemplo ilustrado:** la imagen muestra un caso concreto de cómo se describe un requerimiento con su contexto, sirviendo de apoyo para fijar el concepto. Se usa para mostrar que un requerimiento debe incluir el actor, la acción y la condición; por ejemplo, en un sistema de turnos, \"el recepcionista registra al paciente y el sistema asigna el siguiente número según la prioridad\". Es un slide de apoyo visual; el detalle técnico se desarrolla en los slides posteriores. <br><br><strong>Reflexión docente:</strong> los recursos visuales ayudan a conectar la teoría con casos concretos. <br><br><strong>Pregunta desafío:</strong> ¿qué información necesitaría un desarrollador para implementar el ejemplo de la imagen? <br><br><strong>Respuestas posibles:</strong> 1. El requerimiento funcional preciso. 2. Las restricciones no funcionales. 3. Los criterios de aceptación. <br><br><strong>Advertencia:</strong> la imagen es ilustrativa; el contenido técnico se desarrolla en slides posteriores."
  },
  {
    "title": "¿Qué Es la Ingeniería de Requisitos?",
    "eyebrow": "13 · Definición",
    "body": "<div class=\"quote\">«Conjunto de actividades para descubrir, documentar y mantener un conjunto de requisitos.»</div><div class=\"quote\">«Establecer los servicios que el cliente requiere de un sistema y las restricciones bajo las cuales opera y es desarrollado.»</div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> **Conjunto de actividades para descubrir, documentar y mantener requisitos:** la ingeniería de requisitos permite pasar de una idea vaga a un conjunto organizado; por ejemplo, en un sistema de inventario, descubrir que el encargado necesita alertas de stock mínimo, documentar ese requisito y mantenerlo actualizado cuando cambia el negocio. **Establecer los servicios que el cliente requiere y las restricciones bajo las cuales opera:** define qué pide el cliente y qué límites condicionan al sistema; por ejemplo, \"el sistema genera órdenes de compra\" (servicio) y \"solo el comprador autorizado puede generarlas\" (restricción). <br><br><strong>Reflexión docente:</strong> la ingeniería de requisitos es la primera disciplina del proceso; de ella depende el resto. <br><br><strong>Pregunta desafío:</strong> ¿por qué se dice que los requisitos son la etapa más cara de corregir? <br><br><strong>Respuestas posibles:</strong> 1. Porque un error se propaga al diseño y código. 2. Porque corregirlo al final requiere rehacer varias etapas. 3. Porque involucra a muchas personas. <br><br><strong>Advertencia:</strong> mantener requisitos no es solo documentar: incluye actualizarlos y gestionar su evolución."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "14 · Proceso",
    "body": "<div class=\"quote\">«Conjunto estructurado de actividades de cuya ejecución se obtiene, valida y mantiene un documento de requisitos del sistema (ERS).»</div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> **Conjunto estructurado de actividades:** el proceso organiza las actividades en pasos ordenados y relacionados. **Obtener, validar y mantener un ERS:** de su ejecución surge el documento de requisitos del sistema (ERS), que se valida con el cliente y se mantiene actualizado. Por ejemplo, en un sistema de logística, se obtienen los requisitos entrevistando a los repartidores, se validan con el responsable del depósito y se mantienen cuando cambian las rutas de entrega. El ERS es el artefacto central: todas las actividades convergen en él. <br><br><strong>Reflexión docente:</strong> el ERS es el artefacto central; todas las actividades convergen en él. <br><br><strong>Pregunta desafío:</strong> ¿qué significa que el ERS se \"valida y mantiene\"? <br><br><strong>Respuestas posibles:</strong> 1. Se confirma con el cliente y se actualiza ante cambios. 2. Es un documento vivo. 3. Deja de ser válido cuando cambian los requisitos. <br><br><strong>Advertencia:</strong> el proceso es iterativo, no una secuencia rígida."
  },
  {
    "title": "Participantes en el Proceso",
    "eyebrow": "15 · Participantes",
    "body": "<div class=\"card-grid card-grid--2\"><div class=\"card\"><h3>Cliente y Usuarios</h3><p>Conocen los requisitos adecuados a sus necesidades.</p></div><div class=\"card\"><h3>Diseñadores</h3><p>Comprender los requerimientos para lograr un diseño que los satisfaga.</p></div><div class=\"card\"><h3>Supervisores del Contrato</h3><p>Establecen los hitos de Control y cronogramas.</p></div><div class=\"card\"><h3>Gerentes del Negocio</h3><p>Entienden el impacto en la Organización.</p></div><div class=\"card\"><h3>Verificadores</h3><p>Comprender los requerimientos para poder verificar si el sistema los satisface.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> **Cliente y usuarios:** conocen los requisitos adecuados a sus necesidades; por ejemplo, en un sistema de salud, los médicos describen cómo quieren registrar la atención. **Diseñadores:** comprenden los requerimientos para lograr un diseño que los satisfaga; por ejemplo, el arquitecto decide cómo estructurar los módulos del sistema. **Supervisores del contrato:** establecen los hitos de control y los cronogramas; por ejemplo, definen cuándo se entrega el prototipo. **Gerentes del negocio:** entienden el impacto en la organización; por ejemplo, evalúan cómo el sistema de turnos afecta la atención al paciente. **Verificadores:** comprenden los requerimientos para poder verificar si el sistema los satisface; por ejemplo, diseñan las pruebas de aceptación. Cada participante ve los requisitos desde su rol; la ingeniería debe conciliar todas las visiones. <br><br><strong>Reflexión docente:</strong> cada participante ve los requisitos desde su rol; la ingeniería de requisitos debe conciliar todas las visiones. <br><br><strong>Pregunta desafío:</strong> ¿qué pasa si un participante no participa del proceso? <br><br><strong>Respuestas posibles:</strong> 1. Se pierden requisitos importantes. 2. Se diseñan soluciones incorrectas. 3. La verificación falla. <br><br><strong>Advertencia:</strong> los verificadores necesitan entender los requisitos para poder comprobar si el sistema los satisface."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "16 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos: actividades en el nivel superior (planificación, obtención, análisis, especificación, verificación y validación) y artefactos en el nivel inferior (documento de visión, documento de requisitos, modelo del sistema y especificación de requisitos), con flechas de flujo y de generación de documentos\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> **Diagrama del proceso:** el slide muestra el mapa con las actividades de la ingeniería de requerimientos. **Obtención:** se recogen las necesidades; por ejemplo, entrevistas al personal de una fábrica. **Análisis:** se clasifican y priorizan; por ejemplo, se decide qué módulos entran en la primera versión. **Especificación:** se redacta el ERS. **Verificación:** se comprueba que el documento no tiene errores ni omisiones. **Validación:** se confirma con el cliente que es lo que necesita. El diagrama es el mapa del proceso; conviene volver a él en cada fase. <br><br><strong>Reflexión docente:</strong> la imagen es el mapa del proceso; conviene volver a ella en cada fase. <br><br><strong>Pregunta desafío:</strong> ¿qué actividad del diagrama les parece que se repite más veces? <br><br><strong>Respuestas posibles:</strong> 1. La obtención, porque aparecen nuevos requisitos. 2. La validación, por las revisiones con el cliente. 3. La gestión, por los cambios. <br><br><strong>Advertencia:</strong> el diagrama es una simplificación; en la práctica las actividades se solapan."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "17 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-obtencion.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de obtención resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> **Repetición del diagrama:** se vuelve a mostrar el diagrama del proceso para fijar la secuencia de actividades. **Ejemplo de recorrido:** en un sistema de restaurante, obtener los requisitos hablando con cocina y mozos, analizarlos, especificarlos en el ERS, verificarlos y validarlos con el dueño. El slide es de apoyo visual: refuerza la memorización del proceso sin introducir contenido nuevo. <br><br><strong>Reflexión docente:</strong> la repetición del diagrama refuerza la memorización del proceso. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre este diagrama y el del slide anterior? <br><br><strong>Respuestas posibles:</strong> 1. Ninguna, es el mismo proceso. 2. Cambia el énfasis visual. 3. Se enfoca en otra actividad. <br><br><strong>Advertencia:</strong> son diapositivas de apoyo visual del mismo proceso."
  },
  {
    "title": "Obtención de Requerimientos: Fuentes",
    "eyebrow": "18 · Fuentes",
    "body": "<div class=\"card\"><p><strong>Fuente de los Requerimientos</strong></p><ul><li><strong>Cliente, usuario, otros interesados</strong> (necesidades).</li><li><strong>Modelos del dominio</strong>.</li><li><strong>Revisar la situación actual</strong>: organización actual y sistemas.</li><li><strong>Versión actual del sistema</strong> y desarrolladores de versión anterior.</li><li><strong>Documentos existentes</strong> (antecedentes).</li><li><strong>Sistemas análogos ya existentes</strong> (antecedentes).</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> **Cliente, usuario y otros interesados (necesidades):** la principal fuente de requerimientos; por ejemplo, en una farmacia, el farmacéutico describe cómo controlar el vencimiento de los medicamentos. **Modelos del dominio:** conocimiento estructurado del área de negocio; por ejemplo, el modelo de precios de una distribuidora. **Revisar la situación actual, la organización actual y los sistemas existentes:** entender cómo se trabaja hoy; por ejemplo, revisar las planillas manuales de un almacén. **Versión actual del sistema y desarrolladores de la versión anterior:** aportan lo que ya funciona y los problemas conocidos. **Documentos existentes (antecedentes):** manuales, reglamentos y actas. **Sistemas análogos ya existentes (antecedentes):** por ejemplo, estudiar el sistema de una sucursal que ya se informatizó. Cuantas más fuentes se consulten, menos requisitos se pierden. <br><br><strong>Reflexión docente:</strong> cuantas más fuentes se consulten, menos requisitos se pierden. <br><br><strong>Pregunta desafío:</strong> ¿qué fuente suele aportar los requisitos más completos? <br><br><strong>Respuestas posibles:</strong> 1. Los usuarios reales. 2. Los sistemas análogos. 3. La documentación existente. <br><br><strong>Advertencia:</strong> no confiar en una única fuente; los usuarios no siempre conocen todos los requisitos."
  },
  {
    "title": "Obtención de Requerimientos: Técnicas",
    "eyebrow": "19 · Técnicas",
    "body": "<div class=\"card\"><p><strong>Técnicas de Obtención</strong></p></div><div class=\"card-grid card-grid--2\" style=\"margin-top: 1rem;\"><div class=\"card card--num\"><span class=\"number\">01</span><h3>Reuniones / Entrevistas</h3></div><div class=\"card card--num\"><span class=\"number\">02</span><h3>Cuestionarios</h3></div><div class=\"card card--num\"><span class=\"number\">03</span><h3>Observación</h3></div><div class=\"card card--num\"><span class=\"number\">04</span><h3>Brainstorming</h3></div></div>",
    "note": "<strong>Desarrollo:</strong> **Reuniones / Entrevistas:** conversación guiada con los interesados; por ejemplo, entrevistar al responsable de cobranzas para conocer las reglas de descuento. **Cuestionarios:** encuestas que llegan a muchos usuarios; por ejemplo, encuestar a los vendedores de distintas sucursales. **Observación:** ver cómo se trabaja hoy; por ejemplo, observar cómo un operario registra pedidos en papel revela pasos que nadie mencionó. **Brainstorming:** generación de ideas en grupo; por ejemplo, una sesión con el equipo comercial para listar nuevas funciones. Cada técnica tiene ventajas; suelen combinarse según el contexto. <br><br><strong>Reflexión docente:</strong> cada técnica tiene ventajas; suelen combinarse. <br><br><strong>Pregunta desafío:</strong> ¿qué técnica conviene cuando los usuarios están dispersos geográficamente? <br><br><strong>Respuestas posibles:</strong> 1. Cuestionarios. 2. Entrevistas virtuales. 3. Observación remota. <br><br><strong>Advertencia:</strong> la observación directa revela lo que los usuarios hacen, no solo lo que dicen que hacen."
  },
  {
    "title": "Obtención de Requerimientos: Problemas Comunes",
    "eyebrow": "20 · Problemas",
    "body": "<div class=\"card\"><p><strong>Problemas Comunes</strong></p></div><div class=\"card-grid card-grid--2\" style=\"margin-top: 1rem;\"><div class=\"card card--num\"><span class=\"number\">01</span><p>No saben lo que quieren del sistema, sólo en términos generales; no conocen el costo de sus peticiones.</p></div><div class=\"card card--num\"><span class=\"number\">02</span><p>Los requisitos están en sus términos y con conocimiento implícito de su propio trabajo.</p></div><div class=\"card card--num\"><span class=\"number\">03</span><p>Distintos usuarios tienen distintos requisitos; se deben encontrar todas las fuentes.</p></div><div class=\"card card--num\"><span class=\"number\">04</span><p>Influyen factores políticos.</p></div><div class=\"card card--num\"><span class=\"number\">05</span><p>La prioridad que se da a los requisitos varía con el tiempo.</p></div><div class=\"card card--num\"><span class=\"number\">06</span><p>Aparecen nuevos requisitos.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> **No saben lo que quieren y no conocen el costo de sus peticiones:** los usuarios piden en términos generales sin medir el esfuerzo; por ejemplo, pedir \"que todo sea automático\" sin saber cuánto cuesta. **Requisitos en sus términos y con conocimiento implícito:** el usuario asume que ciertas tareas se entienden solas; por ejemplo, un contador da por sabido el cierre contable mensual. **Distintos usuarios tienen distintos requisitos:** hay que encontrar todas las fuentes; por ejemplo, ventas y almacén piden cosas distintas del mismo sistema. **Influyen factores políticos:** intereses de áreas o personas que condicionan las decisiones. **La prioridad varía con el tiempo:** lo urgente hoy puede no serlo mañana. **Aparecen nuevos requisitos:** el proyecto crece y cambia. Estos problemas son la razón de ser de la ingeniería de requisitos: ordenar el caos. <br><br><strong>Reflexión docente:</strong> estos problemas son la razón de ser de la ingeniería de requisitos: ordenar el caos. <br><br><strong>Pregunta desafío:</strong> ¿cómo se mitiga que el usuario no conozca el costo de sus peticiones? <br><br><strong>Respuestas posibles:</strong> 1. Estimando el impacto de cada requisito. 2. Mostrando prototipos. 3. Negociando prioridades. <br><br><strong>Advertencia:</strong> los factores políticos existen y deben gestionarse, no ignorarse."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "21 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-analisis.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de análisis resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> **Diagrama del proceso:** se repite el diagrama para situar la actividad de análisis. **Obtención y análisis dentro del flujo general:** primero se obtienen las necesidades y luego se analizan; por ejemplo, en un sistema de reservas, se obtiene \"reservar sala\" y se analiza qué datos mínimos necesita la reserva. El diagrama sirve de guía de navegación de la unidad; el avance por las etapas no es estrictamente secuencial. <br><br><strong>Reflexión docente:</strong> el diagrama sirve de guía de navegación de la unidad. <br><br><strong>Pregunta desafío:</strong> ¿en qué etapa del diagrama nos encontramos ahora? <br><br><strong>Respuestas posibles:</strong> 1. Obtención. 2. Análisis. 3. Especificación. <br><br><strong>Advertencia:</strong> el avance por las etapas no es estrictamente secuencial."
  },
  {
    "title": "Análisis de Requerimientos",
    "eyebrow": "22 · Análisis",
    "body": "<div class=\"card-grid card-grid--2\"><div class=\"card card--num\"><span class=\"number\">01</span><p>Analizar <strong>stakeholders</strong> / clientes / usuarios.</p></div><div class=\"card card--num\"><span class=\"number\">02</span><p>Crear <strong>vistas</strong>.</p></div><div class=\"card card--num\"><span class=\"number\">03</span><p><strong>Detallar</strong> y <strong>negociar prioridades</strong>.</p></div><div class=\"card card--num\"><span class=\"number\">04</span><p>Buscar <strong>requerimientos que faltan</strong>.</p></div><div class=\"card card--num\"><span class=\"number\">05</span><p>Evaluar <strong>factibilidad técnica</strong> – prototipos.</p></div><div class=\"card card--num\"><span class=\"number\">06</span><p>Evaluar <strong>riesgos</strong> de requerimientos.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> **Analizar stakeholders / clientes / usuarios:** identificar quién participa y qué espera cada uno; por ejemplo, en un sistema de nómina, separar lo que pide RRHH de lo que pide contabilidad. **Crear vistas:** representar el sistema desde distintas perspectivas; por ejemplo, una vista por rol de usuario. **Detallar:** precisar cada requerimiento; por ejemplo, definir los pasos exactos de \"registrar ausencia\". **Negociar prioridades:** decidir qué entra primero; por ejemplo, posponer el módulo de reportes avanzados. **Buscar requerimientos que faltan:** completar vacíos; por ejemplo, detectar que nadie pidió la recuperación de contraseña. **Evaluar factibilidad técnica con prototipos:** probar que lo pedido se puede construir; por ejemplo, un prototipo de pantalla valida la idea antes de desarrollarla. **Evaluar riesgos de los requerimientos:** anticipar problemas; por ejemplo, depender de un sistema externo de pagos. El análisis transforma necesidades dispersas en requisitos organizados y priorizados; no es diseño. <br><br><strong>Reflexión docente:</strong> el análisis transforma necesidades dispersas en requisitos organizados y priorizados. <br><br><strong>Pregunta desafío:</strong> ¿por qué son útiles los prototipos en el análisis? <br><br><strong>Respuestas posibles:</strong> 1. Porque aclaran lo que el usuario quiere. 2. Porque validan la factibilidad. 3. Porque reducen malentendidos. <br><br><strong>Advertencia:</strong> el análisis no es diseño; busca entender y organizar, no construir la solución."
  },
  {
    "title": "Análisis de Requerimientos: Modelos del Sistema",
    "eyebrow": "23 · Modelos",
    "body": "<div class=\"card\"><p><strong>Modelos o Vistas del Sistema</strong></p></div><div class=\"card-grid card-grid--2\" style=\"margin-top: 1rem;\"><div class=\"card\"><p>Glosario.</p></div><div class=\"card\"><p>Modelos gráficos y modelo conceptual.</p></div><div class=\"card\"><p>Diagramas de estado – para entidades complejas que pasen por distintos estados.</p></div><div class=\"card\"><p>Diagramas de Flujo de Datos (DFD).</p></div><div class=\"card\"><p>Prototipos de interfaz gráfica.</p></div><div class=\"card\"><p>Casos de Prueba y Tablas de Decisión.</p></div><div class=\"card\"><p>Casos de Uso.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> **Glosario:** definiciones comunes de los términos del dominio; por ejemplo, qué significa \"cliente activo\" en la organización. **Modelos gráficos y modelo conceptual:** representaciones visuales de la estructura; por ejemplo, el modelo conceptual de una biblioteca muestra libros, socios y préstamos. **Diagramas de estado:** para entidades que pasan por distintos estados; por ejemplo, un pedido (creado, pagado, enviado, entregado). **Diagramas de Flujo de Datos (DFD):** muestran cómo circulan los datos entre procesos; por ejemplo, el flujo de un pedido desde el cliente hasta el almacén. **Prototipos de interfaz gráfica:** maquetas de las pantallas para validar la interacción. **Casos de prueba:** situaciones concretas para comprobar el comportamiento. **Tablas de decisión:** combinan condiciones y acciones; por ejemplo, cuándo aplicar un descuento según el monto y el tipo de cliente. **Casos de uso:** describen la interacción entre un actor y el sistema; por ejemplo, \"registrar devolución\". Cada vista muestra una faceta del sistema; ninguna es suficiente por sí sola. <br><br><strong>Reflexión docente:</strong> cada vista muestra una faceta del sistema; ninguna es suficiente por sí sola. <br><br><strong>Pregunta desafío:</strong> ¿qué vista usarían para entender los estados de una entidad? <br><br><strong>Respuestas posibles:</strong> 1. Diagrama de estados. 2. DFD. 3. Tabla de decisión. <br><br><strong>Advertencia:</strong> estos modelos se estudian en profundidad en unidades posteriores."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "24 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-especificacion.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de especificación resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> **Diagrama del proceso:** se muestra nuevamente el diagrama, situando la especificación. **Análisis y especificación en el flujo:** tras analizar los requisitos se redactan; por ejemplo, en un sistema de inventario, después de priorizar qué productos requieren alertas de stock se escribe el requerimiento en el ERS. Es un apoyo visual; no introduce contenido nuevo. <br><br><strong>Reflexión docente:</strong> el diagrama mantiene el contexto del recorrido. <br><br><strong>Pregunta desafío:</strong> ¿qué actividad sigue al análisis en el proceso? <br><br><strong>Respuestas posibles:</strong> 1. Especificación. 2. Verificación. 3. Obtención. <br><br><strong>Advertencia:</strong> es un apoyo visual; no introduce contenido nuevo."
  },
  {
    "title": "Especificación de Requerimientos: Documentación",
    "eyebrow": "25 · Documentación",
    "body": "<div class=\"card-grid card-grid--2\" style=\"gap: 2.5rem; align-items: start;\"><div style=\"display: grid; gap: 1.25rem; align-content: start;\"><div class=\"card\"><p><strong>Qué documentar?</strong></p></div><div class=\"card\"><ul><li>Lo que hace el sistema actual.</li><li>Lo que el cliente pide.</li><li>Lo que el sistema va a hacer.</li><li>Criterios de aceptación.</li><li>Criterios de verificación.</li></ul></div></div><div style=\"display: grid; gap: 1.25rem; align-content: start;\"><div class=\"card\"><p><strong>Recomendaciones:</strong></p></div><div class=\"card\"><ul><li>Agrupar por temas.</li><li>Formular los requerimientos como requerimientos positivos y no negativos.</li><li>Expresarlos en voz activa y no pasiva.</li><li>Indicar si se está documentando solo lo que va en el alcance o todo lo que se pidió.</li><li>Representar requerimientos con múltiples vistas.</li></ul></div></div></div>",
    "note": "<strong>Desarrollo:</strong> **Qué documentar:** lo que hace el sistema actual, lo que el cliente pide, lo que el sistema va a hacer, y los criterios de aceptación y de verificación. Por ejemplo, en un sistema de inventario, documentar que hoy el conteo se hace en planillas, que el cliente pide lectura por código de barras, que el nuevo sistema hará el conteo en línea y cómo se comprobará cada punto. **Recomendaciones:** agrupar por temas (por ejemplo, por módulos), formular los requerimientos en positivo y no en negativo (\"el sistema valida el documento\" en lugar de \"no debe aceptar documentos inválidos\"), expresarlos en voz activa y no pasiva, indicar si se documenta solo el alcance o todo lo que se pidió, y representar los requerimientos con múltiples vistas. Redactar bien evita malentendidos y falsas expectativas. <br><br><strong>Reflexión docente:</strong> la documentación es la base del ERS; redactar bien ahorra malentendidos. <br><br><strong>Pregunta desafío:</strong> ¿por qué se recomienda formular requerimientos en positivo y en voz activa? <br><br><strong>Respuestas posibles:</strong> 1. Para reducir ambigüedad. 2. Para facilitar la verificación. 3. Para que el lector sepa exactamente qué hacer. <br><br><strong>Advertencia:</strong> indicar si se documenta solo el alcance o todo lo pedido evita falsas expectativas."
  },
  {
    "title": "Especificación de Requerimientos: Documento SRS",
    "eyebrow": "26 · Documento",
    "body": "<div class=\"card\"><p><strong>Documento de Especificación de requisitos</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><ul><li>Registrar los requisitos en los términos del cliente.</li><li>Delinear el propósito general del sistema: Incluir referencias a otros sistemas, glosario y abreviaciones.</li><li>Describir el contexto y objetivos del desarrollo del sistema.</li><li>Delinear visión global del sistema: Incluir restricciones generales.</li><li>Definir en detalle las características del sistema propuesto, definir el alcance del sistema e interfaces.</li><li>Discutir el ambiente en el que el sistema va a operar (hardware, comunicaciones, personal).</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> **Registrar los requisitos en los términos del cliente:** sin tecnicismos; por ejemplo, describir que \"la caja registradora se comunica con el sistema central\" en palabras del cajero. **Propósito general del sistema:** incluye referencias a otros sistemas, glosario y abreviaciones; por ejemplo, referirse al sistema de contabilidad que recibe las ventas. **Contexto y objetivos del desarrollo:** el porqué de construir el sistema. **Visión global del sistema:** incluye las restricciones generales; por ejemplo, \"solo se accede desde la red interna\". **Características del sistema propuesto, alcance e interfaces:** detallar funciones y límites; por ejemplo, \"el módulo de ventas incluye cobro y no incluye devoluciones\". **Ambiente de operación:** hardware, comunicaciones y personal; por ejemplo, \"se ejecuta en cajas con lector de código de barras y requiere un encargado de turno\". El SRS es el contrato técnico entre el cliente y los desarrolladores. <br><br><strong>Reflexión docente:</strong> el SRS es el contrato técnico entre cliente y desarrolladores. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre el propósito y la visión global del sistema? <br><br><strong>Respuestas posibles:</strong> 1. El propósito es el porqué; la visión, el qué general. 2. El propósito es corto; la visión, más detallada. 3. Ambos describen el sistema desde lo alto. <br><br><strong>Advertencia:</strong> el SRS se redacta en términos del cliente, sin tecnicismos innecesarios."
  },
  {
    "title": "Características de una Buena Especificación SRS (IEEE 830)",
    "eyebrow": "27 · SRS IEEE 830",
    "body": "<div class=\"card\"><p><strong>Correcta / Válida:</strong></p><ul><li>Todos los requerimientos son requeridos en el sistema.</li><li>No existe herramienta que asegure esto.</li><li>Validado por el cliente (que efectivamente refleje sus necesidades).</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>No Ambigua:</strong></p><ul><li>Todo requerimiento tiene una única interpretación.</li><li>Incluir glosario.</li><li>No ambigua para quienes lo crearon y para quienes lo usan.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Completa:</strong> debe incluir:</p><ul><li>Todos los requisitos asociados con funcionalidad, desempeño, restricciones de diseño, atributos o interfaces externas.</li><li>Definición de respuestas del sw a todo posible dato de entrada (válidos o inválidos) en toda clase de situaciones realizables.</li><li>No hay referencias sin definir en la especificación.</li><li>La frase «a determinar» indica que el SRS no está completa. Ocasionalmente necesaria; describir: condiciones que causan que no se sepa aún y qué se debe hacer para determinar lo que falta, con quién y cuándo.</li></ul></div><p class=\"reference\">IEEE. IEEE Std 830-1998, Recommended Practice for Software Requirements Specifications. IEEE, 1998.</p>",
    "note": "<strong>Desarrollo:</strong> **Correcta / Válida:** todos los requerimientos son requeridos por el sistema; no existe herramienta que lo asegure, lo valida el cliente. Por ejemplo, en un sistema de turnos, el cliente confirma que el requisito \"rechazar doble reserva\" refleja su necesidad real. **No ambigua:** cada requerimiento tiene una única interpretación; se incluye un glosario. Por ejemplo, \"cuenta corriente\" debe significar lo mismo para el cliente y para el desarrollador. **Completa:** incluye todos los requisitos de funcionalidad, desempeño, restricciones de diseño, atributos e interfaces externas; define la respuesta del software ante todo dato de entrada válido o inválido; no hay referencias sin definir, y la frase \"a determinar\" indica que el SRS no está completo (si aparece, se describe qué falta, con quién y cuándo se definirá). Por ejemplo, un ERS completo especifica qué sucede si el usuario ingresa un monto negativo. <br><br><strong>Reflexión docente:</strong> la completitud es difícil de lograr; requiere revisar funcionalidad, desempeño, restricciones e interfaces. <br><br><strong>Pregunta desafío:</strong> ¿qué implica que una especificación tenga la frase \"a determinar\"? <br><br><strong>Respuestas posibles:</strong> 1. Que no está completa. 2. Que falta definir un valor. 3. Que debe documentarse qué falta, con quién y cuándo se definirá. <br><br><strong>Advertencia:</strong> la correctitud no la garantiza ninguna herramienta; la valida el cliente."
  },
  {
    "title": "Características de una Buena Especificación SRS (IEEE 830)",
    "eyebrow": "28 · SRS IEEE 830",
    "body": "<div class=\"card\"><p><strong>Consistente internamente:</strong> los requisitos no son contradictorios entre sí.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Ordenados por grado de importancia y/o estabilidad:</strong> los requisitos deben tener un identificador.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Verificable:</strong></p><ul><li>Un requerimiento es verificable si existe un proceso finito de costo accesible para determinar que el sistema lo cumple.</li><li>Usar términos concretos y cantidades mesurables.</li><li>Preparar pruebas para demostrar que se cumplen. Si no se puede, eliminar o revisar el requisito.</li><li>Expresar cada req. separadamente.</li></ul></div><p class=\"reference\">IEEE. IEEE Std 830-1998, Recommended Practice for Software Requirements Specifications. IEEE, 1998.</p>",
    "note": "<strong>Desarrollo:</strong> **Consistente internamente:** los requisitos no se contradicen entre sí; por ejemplo, no puede decirse que el sistema acepta pagos sin conexión y, a la vez, que solo opera conectado. **Ordenados por grado de importancia y/o estabilidad:** los requisitos deben tener un identificador; por ejemplo, priorizar \"RF-005 facturación\" por encima de \"RF-012 reportes históricos\". **Verificable:** existe un proceso finito de costo accesible para determinar que el sistema cumple el requisito; se usan términos concretos y cantidades mesurables y se preparan pruebas. Por ejemplo, \"el sistema responde en menos de 2 segundos\" se verifica con una prueba de rendimiento. Si no se puede verificar, el requisito se revisa o se elimina, y cada requisito se expresa por separado. <br><br><strong>Reflexión docente:</strong> la verificabilidad exige usar términos concretos y cantidades mesurables. <br><br><strong>Pregunta desafío:</strong> ¿qué se hace si un requisito no es verificable? <br><br><strong>Respuestas posibles:</strong> 1. Revisarlo o eliminarlo. 2. Preparar pruebas. 3. Reformularlo con métricas. <br><br><strong>Advertencia:</strong> ordenar por importancia facilita priorizar el desarrollo y los cambios."
  },
  {
    "title": "Características de una Buena Especificación SRS (IEEE 830)",
    "eyebrow": "29 · SRS IEEE 830",
    "body": "<div class=\"card\"><p><strong>Trazables:</strong></p><ul><li>El origen de cada requerimiento es claro, y es posible seguirle la pista en futuros desarrollos o mejora de la documentación.</li><li>Trazabilidad hacia atrás: en versiones previas.</li><li>Trazabilidad hacia adelante: documentos posteriores.</li><li>Requiere IDENTIFICADOR ÚNICO.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Realistas / Factibles:</strong></p><ul><li>Ej.: tiempo de respuesta local = remoto.</li><li>Ej.: el cliente quiere adelantarse a la tecnología.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Entendibles:</strong> tanto por los usuarios como por los desarrolladores.</p></div><p class=\"reference\">IEEE. IEEE Std 830-1998, Recommended Practice for Software Requirements Specifications. IEEE, 1998.</p>",
    "note": "<strong>Desarrollo:</strong> **Trazables:** el origen de cada requerimiento es claro y es posible seguirle la pista en desarrollos futuros. Trazabilidad hacia atrás: hacia versiones previas. Trazabilidad hacia adelante: hacia documentos posteriores (diseño, pruebas). Ambas requieren identificador único; por ejemplo, el requisito RF-010 se rastrea desde su origen en un acta de reunión hasta su implementación en el código. **Realistas / Factibles:** deben poder implementarse con la tecnología y los recursos disponibles; por ejemplo, exigir \"tiempo de respuesta local igual al remoto\" puede no ser factible, y un cliente que quiere adelantarse a la tecnología pide funcionalidades aún no maduras. **Entendibles:** comprensibles tanto por los usuarios como por los desarrolladores; por ejemplo, \"el sistema recuerda el idioma preferido\" en lugar de tecnicismos. <br><br><strong>Reflexión docente:</strong> la trazabilidad exige identificadores únicos desde el inicio. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre trazabilidad hacia atrás y hacia adelante? <br><br><strong>Respuestas posibles:</strong> 1. Hacia atrás: versiones previas; hacia adelante: documentos posteriores. 2. Una rastrea el origen; la otra la implementación. 3. Ambas requieren identificador único. <br><br><strong>Advertencia:</strong> los requisitos deben ser entendibles tanto por usuarios como por desarrolladores."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "30 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-verificacion.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de verificación resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> **Diagrama del proceso:** se muestra el diagrama situando la verificación. **Verificación tras la especificación:** una vez redactado el ERS se comprueba su calidad; por ejemplo, en un sistema de reservas, revisar que cada requisito sea verificable antes de pasar al diseño. Es un apoyo visual. <br><br><strong>Reflexión docente:</strong> el diagrama mantiene el contexto. <br><br><strong>Pregunta desafío:</strong> ¿qué viene después de especificar en el proceso? <br><br><strong>Respuestas posibles:</strong> 1. Verificar. 2. Validar. 3. Gestionar. <br><br><strong>Advertencia:</strong> es un apoyo visual."
  },
  {
    "title": "Verificación de Requerimientos Funcionales",
    "eyebrow": "31 · Verificación",
    "body": "<div class=\"card\"><p>Proceso por el cual se comprueba que los <strong>requisitos</strong> del documento estén correctamente definidos: <strong>consistentes, completos, sin ambigüedades, realistas, verificables, comprensibles, adaptables y trazables</strong>.</p></div><div class=\"card\" style=\"margin-top: 1rem;\"><p><strong>Se verifica en el documento de requisitos:</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><ul><li><strong>Consistencia:</strong> que no haya contradicciones.</li><li><strong>Completitud:</strong> que no falte nada. Chequear por: <em>Omisiones</em> (hacer árboles de decisión para ver que estén todas las opciones detalladas) y <em>Límites</em> (más claro con tabla, ahí se ve que no falta ninguno).</li><li><strong>Ambigüedades.</strong></li><li><strong>Realismo o Factibilidad:</strong> que se puedan implementar con la tecnología, presupuesto y calendario existentes.</li><li><strong>Verificabilidad:</strong> que se pueda diseñar un conjunto de pruebas para demostrar que el sistema cumple esos requisitos. Cuidado con adjetivos y adverbios.</li><li><strong>Comprensibilidad:</strong> que los usuarios finales lo entiendan.</li><li><strong>Adaptabilidad:</strong> que el requisito se pueda cambiar sin afectar a otros.</li><li><strong>Trazabilidad:</strong> que esté establecido el origen.</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> **Verificación de requisitos:** es el proceso de revisar el documento de requisitos para comprobar que los requisitos estén correctamente definidos, antes de pasar al diseño; por ejemplo, en un sistema de facturación, se verifica que el requisito \"el sistema aplica el 10% de IVA\" no contradiga a otro que defina un porcentaje distinto. **Consistencia:** que no haya contradicciones; por ejemplo, no permitir que dos requisitos definan plazos distintos para la misma entrega. **Completitud:** que no falte nada; se chequean las omisiones, se usan árboles de decisión para verificar que estén todas las opciones y tablas para revisar los límites; por ejemplo, una tabla que cruce tipo de cliente y forma de pago muestra si falta alguna combinación. **Ambigüedades:** detectar términos con más de una interpretación. **Realismo o Factibilidad:** que se pueda implementar con la tecnología, el presupuesto y el calendario existentes. **Verificabilidad:** que se pueda diseñar un conjunto de pruebas para demostrar el cumplimiento; cuidado con adjetivos y adverbios (\"rápido\", \"fácil\"). **Comprensibilidad:** que los usuarios finales lo entiendan. **Adaptabilidad:** que el requisito se pueda cambiar sin afectar a otros. **Trazabilidad:** que esté establecido el origen. La verificación comprueba la calidad del documento, no que el sistema esté bien construido. <br><br><strong>Reflexión docente:</strong> la verificación comprueba la calidad del documento, no que el sistema esté bien construido. <br><br><strong>Pregunta desafío:</strong> ¿qué se revisa con las tablas de decisión? <br><br><strong>Respuestas posibles:</strong> 1. Que no falten combinaciones (completitud). 2. Los límites. 3. Las ambigüedades. <br><br><strong>Advertencia:</strong> cuidado con adjetivos y adverbios en la verificación de requerimientos."
  },
  {
    "title": "Verificación de Requerimientos No Funcionales",
    "eyebrow": "32 · No funcionales",
    "body": "<img class=\"figure-img\" src=\"assets/verificacion-requerimientos.png\" alt=\"Verificación de los requerimientos no funcionales\" style=\"display: block; margin: 0 auto;\"><div class=\"card\" style=\"margin-top: 1rem;\"><p>Son <strong>difíciles de verificar</strong>.</p></div><div class=\"card\" style=\"margin-top: .5rem;\"><p>Se deben expresar de manera <strong>cuantitativa</strong> utilizando métricas que se puedan probar de forma objetiva (esto es IDEAL).</p></div><div class=\"card\" style=\"margin-top: .5rem;\"><p>Para los usuarios es <strong>difícil especificarlos</strong> en forma cuantitativa.</p></div>",
    "note": "<strong>Desarrollo:</strong> **Son difíciles de verificar:** los no funcionales no describen una acción puntual, por lo que cuesta comprobarlos. **Expresarlos de manera cuantitativa con métricas que se puedan probar de forma objetiva (ideal):** por ejemplo, \"el sistema debe ser confiable\" se reformula como \"disponibilidad del 99,9% anual\", y \"los datos deben estar protegidos\" como \"cifrado AES-256\". **A los usuarios les cuesta especificarlos en forma cuantitativa:** suelen pedir \"que sea rápido\" o \"que no se caiga\" sin números; el analista debe ayudar a convertirlos en métricas. Cuantificar es difícil pero necesario para poder probarlos. <br><br><strong>Reflexión docente:</strong> cuantificar los no funcionales es difícil pero necesario para poder probarlos. <br><br><strong>Pregunta desafío:</strong> ¿cómo cuantificarían \"el sistema debe ser fácil de usar\"? <br><br><strong>Respuestas posibles:</strong> 1. Tiempo máximo de aprendizaje. 2. Tasa de error permitida. 3. Satisfacción en una escala. <br><br><strong>Advertencia:</strong> la cuantificación es lo ideal; si no se logra, al menos definir criterios de aceptación claros."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "33 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-validacion.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de validación resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> **Diagrama del proceso:** se muestra el diagrama situando la validación. **Validación tras la verificación:** primero se comprueba el documento y luego se confirma con el cliente; por ejemplo, en un sistema de facturación, validar con el responsable que el ERS refleja las reglas fiscales de la empresa. Es un apoyo visual. <br><br><strong>Reflexión docente:</strong> el diagrama mantiene el contexto del proceso. <br><br><strong>Pregunta desafío:</strong> ¿qué actividad sigue a la verificación? <br><br><strong>Respuestas posibles:</strong> 1. Validación. 2. Especificación. 3. Gestión. <br><br><strong>Advertencia:</strong> es un apoyo visual."
  },
  {
    "title": "Validación de Requerimientos",
    "eyebrow": "34 · Validación",
    "body": "<div class=\"card\"><p>Proceso por el cual se determina si la <strong>especificación</strong> es consistente con las <strong>necesidades del cliente</strong>.</p></div><div class=\"card\" style=\"margin-top: 1rem;\"><p><strong>Se verifica en el documento de requisitos:</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><ul><li><strong>Validez:</strong> que el usuario valide qué es lo que quiere.</li><li>Planificar quién (qué stakeholder) va a validar qué artefacto y cómo (técnica).</li><li>Registrar – Reporte de validación / Firma.</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> **Proceso de validación:** se determina si la especificación es consistente con las necesidades del cliente. **Validez:** el usuario valida qué es lo que quiere; por ejemplo, en una biblioteca, el bibliotecario confirma que el requisito \"renovación de préstamos\" es lo que realmente necesita. **Planificación de la validación:** se define quién (qué stakeholder) valida qué artefacto y cómo (qué técnica); por ejemplo, el gerente valida el alcance y los operadores validan los casos de uso. **Registro:** se documenta un reporte de validación y se obtiene la firma, que compromete a las partes. Diferencia clave: verificar es contra el documento; validar es con el cliente. <br><br><strong>Reflexión docente:</strong> la validación es con el cliente; la verificación es contra el documento. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre verificar y validar? <br><br><strong>Respuestas posibles:</strong> 1. Verificar: el sistema cumple la especificación; validar: la especificación satisface al cliente. 2. Verificar es interno; validar es con el usuario. 3. Ambas son complementarias. <br><br><strong>Advertencia:</strong> la firma del reporte de validación compromete a las partes."
  },
  {
    "title": "Validación de Requerimientos: Revisiones",
    "eyebrow": "35 · Revisiones",
    "body": "<div class=\"card\"><p><strong>Proceso manual:</strong> se revisa el documento de requisitos buscando anomalías y omisiones.</p><ul><li><strong>Revisiones informales:</strong> discusión informal.</li><li><strong>Revisiones formales:</strong> se hace una «recorrida» del doc. de req. con el cliente, explicando implicancias de cada requisito.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Participan representantes:</strong></p><ul><li><strong>Del cliente:</strong> operadores, quienes realicen entradas, utilicen salidas, y sus gerentes.</li><li><strong>Del equipo de desarrollo:</strong> analistas de requisitos, diseñadores, encargados de pruebas y gestión de configuración.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Incluye:</strong></p><ul><li>Revisar objetivos del sistema.</li><li>Evaluar alineamiento de requisitos con los objetivos (necesidad).</li><li>Revisar el ambiente de operación y las interfaces con otros sistemas.</li><li>Funciones completas, restricciones realistas.</li><li>Evaluar riesgos.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Considerar:</strong> pruebas del sistema y cambios en los requisitos en el proyecto, su verificación y validación.</p></div>",
    "note": "<strong>Desarrollo:</strong> **Proceso manual:** se revisa el documento de requisitos buscando anomalías y omisiones. **Revisiones informales:** discusión sin estructura formal entre pares. **Revisiones formales:** se hace una \"recorrida\" del documento con el cliente explicando las implicancias de cada requisito; por ejemplo, en un sistema de facturación, recorrer requisito por requisito con el contador para confirmar cada regla fiscal. **Participantes:** del cliente (operadores, quienes realizan las entradas, quienes usan las salidas y sus gerentes) y del equipo de desarrollo (analistas de requisitos, diseñadores, encargados de pruebas y de gestión de configuración). **La revisión incluye:** revisar los objetivos del sistema, evaluar el alineamiento de los requisitos con esos objetivos (la necesidad), revisar el ambiente de operación y las interfaces con otros sistemas, verificar funciones completas y restricciones realistas, y evaluar riesgos. **Además se consideran:** las pruebas del sistema, los cambios en los requisitos del proyecto, su verificación y validación. <br><br><strong>Reflexión docente:</strong> la recorrida formal es una técnica efectiva para detectar anomalías tempranamente. <br><br><strong>Pregunta desafío:</strong> ¿qué se busca al evaluar la alineación de requisitos con los objetivos? <br><br><strong>Respuestas posibles:</strong> 1. Que cada requisito responda a una necesidad. 2. Que no haya requisitos innecesarios. 3. Que el alcance sea correcto. <br><br><strong>Advertencia:</strong> la validación debe considerar las pruebas del sistema y los cambios en los requisitos."
  },
  {
    "title": "Gestión de Requerimientos",
    "eyebrow": "36 · Gestión",
    "body": "<div class=\"card\"><p>Proceso de <strong>comprender y controlar</strong> los cambios en los requisitos del sistema; se hace <strong>en paralelo</strong> con el Proceso de Requisitos.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p><strong>Los requisitos cambian, debido a:</strong></p></div><div class=\"card\" style=\"margin-top: .5rem;\"><ul><li>Muchos usuarios.</li><li>Quienes pagan por el sistema y los usuarios no son las mismas personas.</li><li>Cambios en el negocio.</li><li>Cambios en la tecnología.</li></ul></div><div class=\"card\" style=\"margin-top: .8rem;\"><p><strong>Tres etapas:</strong></p><ul><li><strong>Planificación:</strong> se realiza al comenzar el análisis de requisitos.</li><li><strong>Administración del cambio:</strong> comienza una vez que se tiene una primera versión del documento de requisitos.</li><li><strong>Trazabilidad:</strong> se mantiene a lo largo del proceso de requisitos.</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> **Comprender y controlar los cambios:** la gestión maneja la evolución de los requisitos a lo largo del proyecto. **En paralelo con el proceso de requisitos:** acompaña a la obtención, el análisis y el resto de las actividades. **Los requisitos cambian porque:** hay muchos usuarios (cada uno pide algo), quienes pagan por el sistema y quienes lo usan no son las mismas personas (por ejemplo, el gerente lo compra pero el operario lo utiliza), y cambian el negocio y la tecnología (por ejemplo, una nueva ley impositiva obliga a modificar la facturación). **Tres etapas:** Planificación (se realiza al comenzar el análisis de requisitos), Administración del cambio (comienza cuando existe una primera versión del documento de requisitos) y Trazabilidad (se mantiene a lo largo de todo el proceso). La gestión evita que los cambios descontrolados destruyan el proyecto. <br><br><strong>Reflexión docente:</strong> la gestión evita que los cambios descontrolados destruyan el proyecto. <br><br><strong>Pregunta desafío:</strong> ¿por qué los cambios son inevitables en los proyectos de software? <br><br><strong>Respuestas posibles:</strong> 1. Porque el negocio y la tecnología cambian. 2. Porque los usuarios descubren nuevas necesidades. 3. Porque quien paga no siempre es quien usa. <br><br><strong>Advertencia:</strong> la trazabilidad se mantiene a lo largo de todo el proceso, no solo al final."
  },
  {
    "title": "Gestión de Requerimientos: Herramientas",
    "eyebrow": "37 · Herramientas",
    "body": "<div class=\"card\"><p><strong>JIRA:</strong> herramienta de gestión de proyectos ampliamente utilizada que también ofrece funcionalidades para la gestión de requerimientos. Permite la creación de historias de usuario, tareas, epics y otras unidades de trabajo, así como la asignación de prioridades, seguimiento de estado y colaboración en equipo.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Trello:</strong> herramienta de gestión de proyectos basada en tableros visuales que puede adaptarse para la gestión de requerimientos de software. Permite la creación de tarjetas para representar requerimientos, listas para organizarlos y tableros para visualizar el flujo de trabajo y el progreso del proyecto.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Confluence:</strong> plataforma de colaboración que también puede utilizarse para la gestión de requerimientos. Permite la creación de documentación estructurada, incluyendo especificaciones de requerimientos, casos de uso y otros artefactos.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>GitHub Issues:</strong> herramienta de seguimiento de problemas integrada en la plataforma de desarrollo colaborativo GitHub. Permite la creación y seguimiento de problemas, bugs y mejoras, y puede ser utilizada para gestionar los requerimientos de software.</p></div>",
    "note": "<strong>Desarrollo:</strong> **JIRA:** herramienta de gestión de proyectos ampliamente utilizada que también ofrece funcionalidades para la gestión de requerimientos; permite crear historias de usuario, tareas, épicas y otras unidades de trabajo, asignar prioridades, seguir el estado y colaborar en equipo. Por ejemplo, registrar la historia \"como cajero, quiero cobrar con tarjeta para agilizar la fila\". **Trello:** herramienta basada en tableros visuales, con tarjetas para representar requerimientos, listas para organizarlos y tableros para visualizar el flujo de trabajo; por ejemplo, organizar los requerimientos en columnas \"por hacer\", \"en análisis\" y \"validados\". **Confluence:** plataforma de colaboración para documentación estructurada, incluidas especificaciones de requerimientos y casos de uso; por ejemplo, publicar el SRS del proyecto. **GitHub Issues:** seguimiento de problemas, bugs y mejoras dentro de GitHub; por ejemplo, reportar un bug de la facturación como issue. Las herramientas apoyan la gestión, pero no reemplazan el proceso. <br><br><strong>Reflexión docente:</strong> las herramientas apoyan la gestión, pero no reemplazan el proceso. <br><br><strong>Pregunta desafío:</strong> ¿qué herramienta usarían para documentar la especificación SRS? <br><br><strong>Respuestas posibles:</strong> 1. Confluence. 2. JIRA. 3. GitHub Issues. <br><br><strong>Advertencia:</strong> la elección de herramienta depende de la organización; lo importante es el proceso."
  },
  {
    "title": "Ejemplos de Requerimientos",
    "eyebrow": "38 · Ejemplos",
    "body": "<div class=\"card\"><p><strong>Requerimientos funcionales:</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><a href=\"http://www.pmoinformatica.com/2017/02/requerimientos-funcionales-ejemplos.html\">http://www.pmoinformatica.com/2017/02/requerimientos-funcionales-ejemplos.html</a></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Requerimientos no funcionales:</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><a href=\"http://www.pmoinformatica.com/2015/05/requerimientos-no-funcionales-ejemplos.html\">http://www.pmoinformatica.com/2015/05/requerimientos-no-funcionales-ejemplos.html</a></div>",
    "note": "<strong>Desarrollo:</strong> **Referencias web de ejemplos:** el slide comparte dos enlaces con ejemplos de requerimientos funcionales y no funcionales para ampliar la práctica. **Requerimientos funcionales:** el primer enlace muestra redacciones de acciones del sistema, por ejemplo \"el sistema debe registrar al cliente y sus datos de contacto\". **Requerimientos no funcionales:** el segundo muestra restricciones y calidad, por ejemplo \"el sistema debe soportar 100 usuarios concurrentes\". Se recomienda usar estos ejemplos como modelo para redactar requerimientos propios y adaptarlos al dominio de cada proyecto; al ser referencias externas, conviene verificar su vigencia. <br><br><strong>Reflexión docente:</strong> los ejemplos externos complementan la teoría con casos reales. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia encontraron entre los ejemplos funcionales y no funcionales de las referencias? <br><br><strong>Respuestas posibles:</strong> 1. Los funcionales describen acciones; los no funcionales, restricciones. 2. Los no funcionales son más difíciles de cuantificar. 3. Ambos son necesarios. <br><br><strong>Advertencia:</strong> las referencias son externas; verificar su vigencia."
  },
  {
    "title": "Muchas Gracias",
    "eyebrow": "39 · Cierre",
    "body": "<div class=\"card card--hero\"><h2 style=\"color:var(--fpuna-blue);\">PREGUNTAS</h2></div>",
    "note": "<strong>Desarrollo:</strong> **Preguntas:** cierre de la unidad: se agradece y se abre el espacio para consultas. Se puede proponer un repaso rápido: definir qué es un requerimiento, distinguir los funcionales de los no funcionales y explicar la diferencia entre verificar y validar, usando como referencia un caso conocido, por ejemplo un sistema de reservas o de pedidos. La unidad sienta las bases para el diseño y desarrollo posteriores; no se introducen contenidos nuevos. <br><br><strong>Reflexión docente:</strong> la unidad sienta las bases para el diseño y desarrollo posteriores. <br><br><strong>Pregunta desafío:</strong> ¿qué concepto de la unidad les resultó más útil y por qué? <br><br><strong>Respuestas posibles:</strong> 1. La diferencia entre funcionales y no funcionales. 2. La verificación vs. validación. 3. La gestión de cambios. <br><br><strong>Advertencia:</strong> cierre de la unidad; no se introducen contenidos nuevos."
  }
];

// ─── Renderizado ──────────────────────────────────────────────
const stage = document.getElementById('stage');
const counter = document.getElementById('counter');
const previousBtn = document.getElementById('previous');
const nextBtn = document.getElementById('next');
const notes = document.getElementById('speaker-notes');
const indexNav = document.getElementById('slide-index');
let current = 0;
const presenterView = new URLSearchParams(location.search).get('view') === 'presenter';
let presenterWindow = null;

function slideMarkup(slide, index, headingId = 'slide-title') {
 return `<div class="slide" data-slide="${index}">
 <header class="slide-header">
 <span class="eyebrow">${slide.eyebrow}</span>
 <h1 id="${headingId}">${slide.title}</h1>
 </header>
 <div class="content">${slide.body}</div>
 </div>`;
}

function buildIndex() {
 indexNav.innerHTML = slides.map((slide, i) => {
 return `<button class="index-item" data-slide="${i}" aria-label="Ir a slide ${i + 1}: ${slide.title}">
 <span class="index-num">${String(i + 1).padStart(2, '0')}</span>
 <span class="index-title">${slide.title}</span>
 </button>`;
 }).join('');
 indexNav.addEventListener('click', (e) => {
 const btn = e.target.closest('.index-item');
 if (btn) {
 goTo(parseInt(btn.dataset.slide, 10));
 togglePanel('index-panel', false);
 }
 });
}

function goTo(index, silent) {
 if (index < 0 || index >= slides.length) return;
 current = index;
 const slide = slides[current];
 stage.innerHTML = slideMarkup(slide, current);
 counter.textContent = `${String(current + 1).padStart(2, '0')} / ${String(slides.length).padStart(2, '0')}`;
 previousBtn.disabled = current === 0;
 nextBtn.disabled = current === slides.length - 1;
 const progress = document.querySelector('#progress');
 progress.style.width = `${((current + 1) / slides.length) * 100}%`;
 progress.setAttribute('aria-valuenow', current + 1);
 notes.innerHTML = `<div class="note"><strong>Slide ${current + 1}: ${slide.title}</strong><p>${slide.note}</p></div>`;
 document.querySelectorAll('.index-item').forEach((button, i) => button.classList.toggle('active', i === current));
 history.replaceState(null, '', `#slide-${current + 1}`);
 if (!silent && presenterWindow && !presenterWindow.closed) {
  presenterWindow.postMessage({ type: 'presentation:navigate', index: current }, '*');
 }
}

function renderAllForPrint() {
 const total = slides.length;
 stage.innerHTML = slides.map((slide, position) => {
 const pageNum = String(position + 1).padStart(2, '0');
 const totalNum = String(total).padStart(2, '0');
 const header = `<div class="print-header"><div class="print-header-left"><img class="print-header-logo" src="assets/fpuna_logo_institucional.svg" alt="Logo FP-UNA"><div class="print-header-text"><span class="print-header-title">Unidad II · T3 - Requerimientos de Software</span><span class="print-header-subtitle">Ingeniería del Software I · FP-UNA / LCiK</span></div></div><span class="print-header-page">${pageNum} / ${totalNum}</span></div>`;
 return `<div class="print-slide">${header}${slideMarkup(slide, position)}</div>`;
 }).join('');
 fitSlidesForPrint();
}

function fitSlidesForPrint() {
 const PAGE_W = 1123;
 const PAGE_H = 631;
 const HEADER_H = 56;
 const PADDING_SIDE = 56, PADDING_TOP = 10, PADDING_BOTTOM = 32;
 const probe = document.createElement('div');
 probe.style.cssText = `position:absolute;visibility:hidden;width:${PAGE_W - PADDING_SIDE * 2}px;`;
 document.body.appendChild(probe);
 document.querySelectorAll('.print-slide').forEach(slide => {
 const inner = slide.querySelector('.slide');
 if (!inner) return;
 probe.innerHTML = '';
 probe.appendChild(inner.cloneNode(true));
 const fullH = probe.scrollHeight;
 const availH = PAGE_H - HEADER_H - PADDING_TOP - PADDING_BOTTOM;
 if (fullH > availH) {
 const scale = availH / fullH;
 inner.style.transform = `scale(${scale})`;
 inner.style.transformOrigin = 'top left';
 inner.style.width = `${(PAGE_W - PADDING_SIDE * 2) / scale}px`;
 }
 });
 document.body.removeChild(probe);
}

function togglePanel(id, force) {
 const panel = document.getElementById(id);
 const isOpen = force !== undefined ? force : !panel.classList.contains('open');
 panel.classList.toggle('open', isOpen);
 panel.setAttribute('aria-hidden', String(!isOpen));
 const toggleBtn = document.getElementById(id.replace('-panel', '-toggle'));
 if (toggleBtn) toggleBtn.setAttribute('aria-expanded', String(isOpen));
 if (isOpen) panel.querySelector('button, [href]')?.focus();
}

function showNotice(message) {
 const notice = document.querySelector('#popup-notice, #presenter-notice');
 if (!notice) return;
 notice.textContent = message;
 notice.hidden = false;
 window.setTimeout(() => { notice.hidden = true; }, 7000);
}

function openPresenter() {
 presenterWindow = window.open(`${location.pathname}?view=presenter#slide-${current + 1}`, 'fpuna-presenter', 'popup,width=1440,height=900,resizable=yes,scrollbars=yes');
 if (!presenterWindow) { showNotice('El navegador bloqueó la ventana del modo presentador. Permití las ventanas emergentes para este sitio e intentá nuevamente.'); return; }
 presenterWindow.focus();
}

function fitPresenterSlide(frame) {
 const slide = frame.querySelector('.slide'); if (!slide) return;
 slide.style.transform = 'none'; slide.style.width = '100%';
 const width = slide.scrollWidth; const height = slide.scrollHeight;
 const scale = Math.min(1, frame.clientWidth / width, frame.clientHeight / height);
 slide.style.width = `${100 / scale}%`; slide.style.transformOrigin = 'top left'; slide.style.transform = `scale(${scale})`;
 frame.style.setProperty('--slide-scale', scale);
}

function initPresenter() {
 document.body.innerHTML = `<main class="presenter-shell"><header class="presenter-header"><div><p class="presenter-kicker">FP-UNA · Unidad II · T3 - Requerimientos de Software</p><h1>Modo presentador</h1></div><div class="presenter-meta"><span id="presenter-counter">01 / ${String(slides.length).padStart(2, '0')}</span><time id="presenter-clock"></time></div></header><section class="presenter-workspace" aria-label="Vista del presentador"><section class="presenter-notes"><h2>Notas docentes</h2><div id="presenter-notes-content" tabindex="0"></div></section><div class="presenter-stack"><div class="presenter-current"><div class="presenter-label">Slide actual</div><div id="presenter-current-frame" class="presenter-slide-frame"></div></div><section class="presenter-next"><h2>Siguiente slide</h2><div id="presenter-next-frame" class="presenter-slide-frame presenter-slide-frame--next"></div></section></div></section><footer class="presenter-controls"><button id="presenter-previous" type="button">← Anterior</button><button id="presenter-next" type="button">Siguiente →</button><span class="presenter-spacer"></span><button id="presenter-public" type="button">Pantalla completa del público</button><button id="presenter-close" type="button">Cerrar</button></footer><div id="presenter-notice" class="popup-notice" role="status" aria-live="polite" hidden></div></main>`;
 const currentFrame = document.querySelector('#presenter-current-frame'); const nextFrame = document.querySelector('#presenter-next-frame');
 function renderPresenter() { const slide = slides[current]; const next = current + 1; currentFrame.innerHTML = slideMarkup(slide, current, 'presenter-current-title'); nextFrame.innerHTML = next < slides.length ? slideMarkup(slides[next], next, 'presenter-next-title') : '<p class="presenter-end-message">Fin de la presentación</p>'; document.querySelector('#presenter-notes-content').innerHTML = slide.note; document.querySelector('#presenter-counter').textContent = `${String(current + 1).padStart(2, '0')} / ${String(slides.length).padStart(2, '0')}`; requestAnimationFrame(() => { fitPresenterSlide(currentFrame); fitPresenterSlide(nextFrame); }); }
 function presenterGoTo(position, silent = false) { current = Math.max(0, Math.min(slides.length - 1, position)); renderPresenter(); if (!silent && window.opener && !window.opener.closed) window.opener.postMessage({ type: 'presenter:navigate', index: current }, '*'); history.replaceState(null, '', `#slide-${current + 1}`); }
 document.querySelector('#presenter-previous').addEventListener('click', () => presenterGoTo(current - 1)); document.querySelector('#presenter-next').addEventListener('click', () => presenterGoTo(current + 1));
 document.querySelector('#presenter-public').addEventListener('click', () => { if (window.opener && !window.opener.closed) window.opener.postMessage({ type: 'presenter:fullscreen' }, '*'); else showNotice('La pantalla pública no está vinculada a esta ventana.'); });
 document.querySelector('#presenter-close').addEventListener('click', () => window.close());
 document.addEventListener('keydown', event => { if (['ArrowRight', 'PageDown', ' '].includes(event.key)) { event.preventDefault(); presenterGoTo(current + 1); } if (['ArrowLeft', 'PageUp'].includes(event.key)) { event.preventDefault(); presenterGoTo(current - 1); } if (event.key === 'Home') presenterGoTo(0); if (event.key === 'End') presenterGoTo(slides.length - 1); });
 window.addEventListener('resize', () => { fitPresenterSlide(currentFrame); fitPresenterSlide(nextFrame); });
 window.addEventListener('message', event => { if (event.source !== window.opener) return; if (event.data?.type === 'presentation:state') presenterGoTo(event.data.index, true); });
 const initial = location.hash.match(/slide-(\d+)/); if (initial) current = Math.max(0, Math.min(slides.length - 1, Number(initial[1]) - 1)); renderPresenter();
 if (window.opener && !window.opener.closed) window.opener.postMessage({ type: 'presenter:ready' }, '*');
 setInterval(() => { document.querySelector('#presenter-clock').textContent = new Intl.DateTimeFormat('es-PY', { hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(new Date()); }, 1000);
}

const hashMatch = location.hash.match(/#slide-(\d+)/);
const startSlide = hashMatch ? parseInt(hashMatch[1], 10) - 1 : 0;

if (presenterView) {
 initPresenter();
} else {
 previousBtn.addEventListener('click', () => goTo(current - 1));
 nextBtn.addEventListener('click', () => goTo(current + 1));
 document.getElementById('index-toggle').addEventListener('click', () => togglePanel('index-panel'));
 document.getElementById('notes-toggle').addEventListener('click', () => togglePanel('notes-panel'));
 document.querySelectorAll('.close-panel').forEach(btn => {
  btn.addEventListener('click', () => togglePanel(btn.dataset.close, false));
 });
 document.getElementById('presenter-mode').addEventListener('click', openPresenter);

 document.addEventListener('keydown', (e) => {
  if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') { e.preventDefault(); goTo(current - 1); }
  if (e.key === 'ArrowRight' || e.key === 'ArrowDown' || e.key === ' ') { e.preventDefault(); goTo(current + 1); }
  if (e.key === 'Home') { e.preventDefault(); goTo(0); }
  if (e.key === 'End') { e.preventDefault(); goTo(slides.length - 1); }
  if (e.key === 'f' || e.key === 'F') {
  if (!document.fullscreenElement) document.documentElement.requestFullscreen();
  else document.exitFullscreen();
  }
  if (e.key === 'i' || e.key === 'I') togglePanel('index-panel');
  if (e.key === 'n' || e.key === 'N') togglePanel('notes-panel');
  if (e.key === 'Escape') {
  togglePanel('index-panel', false);
  togglePanel('notes-panel', false);
  }
 });

 document.getElementById('fullscreen').addEventListener('click', () => {
  if (!document.fullscreenElement) document.documentElement.requestFullscreen();
  else document.exitFullscreen();
 });

 window.addEventListener('message', (event) => {
  if (event.source !== presenterWindow) return;
  if (event.data?.type === 'presenter:ready') presenterWindow.postMessage({ type: 'presentation:state', index: current }, '*');
  if (event.data?.type === 'presenter:navigate') goTo(event.data.index, true);
  if (event.data?.type === 'presenter:fullscreen') {
  const request = document.documentElement.requestFullscreen?.();
  request?.catch(() => showNotice('El navegador no permitió activar pantalla completa desde la ventana presentador. Activala con el botón Pantalla completa de esta ventana.'));
  }
 });

 window.addEventListener('beforeprint', () => { renderAllForPrint(); });
 window.addEventListener('afterprint', () => { stage.innerHTML = ''; goTo(current); });

 buildIndex();
 goTo(Math.min(startSlide, slides.length - 1));
}
