const slides = [
  {
    "title": "Ingeniería de Software I",
    "eyebrow": "01 · Apertura",
    "body": "<div class=\"card card--hero\"><p class=\"lede\">UNIDAD III – REQUERIMIENTOS DE SOFTWARE</p><p>Prof. Lic. Guillermo Jacobo González Rodas Mst. PMP</p></div>",
    "note": "<strong>Desarrollo:</strong> Apertura de la Unidad III: se presenta la materia y se sitúa el tema de los requerimientos dentro de la Ingeniería de Software. El docente se presenta e invita a pensar en qué necesita realmente un sistema antes de construirlo. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): antes de diseñar el sistema de cambio de divisas definimos qué debe hacer: registrar operaciones, calcular tasas y emitir comprobantes. Segundo contexto industrial: un sistema de turnos necesita saber quién se atiende, en qué orden y con qué servicio. <br><br><strong>Reflexión docente:</strong> los requerimientos son la base de todo el proyecto: un error aquí se multiplica en las fases posteriores. <br><br><strong>Pregunta desafío:</strong> ¿qué pasa si construimos un sistema sin definir bien sus requerimientos? <br><br><strong>Respuestas posibles:</strong> 1. Se construye algo que el cliente no pidió. 2. Se descubren errores tarde y el retrabajo es costoso. 3. Se superan plazos y presupuesto. <br><br><strong>Advertencia:</strong> no confundir requerimientos con diseño; los requerimientos describen el QUÉ, no el CÓMO."
  },
  {
    "title": "Objetivos",
    "eyebrow": "02 · Objetivos",
    "body": "<div class=\"card-grid card-grid--3\"><div class=\"card card--num\"><span class=\"number\">01</span><p>Comprender qué son los requerimientos de software y por qué son importantes.</p></div><div class=\"card card--num\"><span class=\"number\">02</span><p>Familiarizarse con los diferentes tipos de requerimientos.</p></div><div class=\"card card--num\"><span class=\"number\">03</span><p>Aprender técnicas y herramientas para la obtención, análisis y gestión de requerimientos.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan los objetivos de la unidad: comprender qué son los requerimientos, distinguir sus tipos y aprender técnicas y herramientas para obtenerlos, analizarlos y gestionarlos. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): al finalizar la unidad sabremos definir los requerimientos funcionales (registrar cambio de divisas) y no funcionales (tiempo de respuesta, seguridad). Segundo contexto industrial: en un hospital, distinguir entre lo que el sistema debe hacer y las restricciones de privacidad. <br><br><strong>Reflexión docente:</strong> estos objetivos estructuran el recorrido de la unidad y dan criterio para evaluar el avance. <br><br><strong>Pregunta desafío:</strong> ¿cuál de los tres objetivos les parece más difícil de lograr y por qué? <br><br><strong>Respuestas posibles:</strong> 1. La obtención, porque los usuarios no siempre saben qué quieren. 2. El análisis, por la cantidad de fuentes y prioridades. 3. La gestión, porque los cambios son constantes. <br><br><strong>Advertencia:</strong> los objetivos son de aprendizaje; no describen aún contenido técnico."
  },
  {
    "title": "Contenido",
    "eyebrow": "03 · Recorrido",
    "body": "<div class=\"sequence-card\" aria-label=\"Recorrido de la unidad\"><div class=\"sequence-step\"><span class=\"sequence-index\">01</span><strong>Requerimientos de Software</strong></div><div class=\"sequence-step\"><span class=\"sequence-index\">02</span><strong>Tipos de Requerimientos</strong></div><div class=\"sequence-step\"><span class=\"sequence-index\">03</span><strong>Ingeniería de Requerimientos</strong></div><div class=\"sequence-step\"><span class=\"sequence-index\">04</span><strong>Proceso de Requerimientos</strong><small>Obtención, Análisis, Especificación, Verificación y Validación de Requerimientos</small></div><div class=\"sequence-step\"><span class=\"sequence-index\">05</span><strong>Gestión de Requerimientos</strong></div></div>",
    "note": "<strong>Desarrollo:</strong> Se presenta el mapa de la unidad: los cinco bloques que se recorrerán, desde la definición de requerimiento hasta la gestión de cambios. El paso 04 (Proceso de Requerimientos) agrupa las cinco actividades que lo componen: obtención, análisis, especificación, verificación y validación. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): el recorrido nos lleva desde \"qué es un requerimiento\" hasta \"cómo gestionar que el cliente pida más monedas o nuevas tasas\". Segundo contexto industrial: en un sistema de inventario, el mismo camino: definir, obtener, analizar, especificar, verificar, validar y gestionar. <br><br><strong>Reflexión docente:</strong> el proceso no es lineal estricto; las actividades se solapan y retroalimentan. <br><br><strong>Pregunta desafío:</strong> ¿por qué la verificación y la validación son pasos distintos? <br><br><strong>Respuestas posibles:</strong> 1. Verificar es comprobar que se especificó bien; validar es confirmar que es lo que el cliente necesita. 2. Se verifican contra el documento; se valida contra el usuario. 3. Ambas se complementan en el proceso. <br><br><strong>Advertencia:</strong> la gestión atraviesa todo el proceso; no es una etapa final."
  },
  {
    "title": "¿Qué Es un Requerimiento de Software?",
    "eyebrow": "04 · Definición",
    "body": "<div class=\"card-grid card-grid--2\" style=\"gap: 2rem; align-items: stretch;\"><div class=\"card\"><p><strong>Definición (Sweebok):</strong></p><p>«Propiedad que debe ser exhibida por un software para resolver un problema particular.»</p></div><div class=\"card\"><p><strong>Definición (usuario):</strong></p><p>«Condición o capacidad que necesita el usuario para resolver un problema o conseguir un objetivo determinado.»</p></div></div><div class=\"card\" style=\"margin-top: 1rem;\"><p><strong>ERS</strong> – Documento formal de Especificación de Requisitos Software</p></div><div class=\"card\" style=\"margin-top: .5rem;\"><p><strong>SRS</strong> – Software Requirements Specification</p></div><p class=\"reference\">IEEE Computer Society. Guide to the Software Engineering Body of Knowledge (SWEBOK). IEEE, 2014.</p>",
    "note": "<strong>Desarrollo:</strong> Se define qué es un requerimiento desde dos perspectivas: la de Sweebok (propiedad que debe exhibir el software) y la del usuario (condición o capacidad para resolver un problema). Se mencionan los documentos ERS y SRS. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): un requerimiento es \"el sistema debe calcular la tasa de cambio aplicando el margen definido\". Segundo contexto industrial: en un sistema de turnos, \"el sistema debe asignar el siguiente número según la prioridad del paciente\". <br><br><strong>Reflexión docente:</strong> la doble definición muestra que un requerimiento se puede ver desde el sistema y desde el negocio; ambos deben coincidir. <br><br><strong>Pregunta desafío:</strong> ¿un requerimiento describe lo que el sistema hace o lo que el usuario necesita? <br><br><strong>Respuestas posibles:</strong> 1. Ambas cosas, según la perspectiva. 2. Lo que el sistema hace para satisfacer la necesidad. 3. Lo que el usuario necesita, traducido a capacidad del sistema. <br><br><strong>Advertencia:</strong> Sweebok es la guía del cuerpo de conocimiento de la ingeniería de software; es una referencia académica."
  },
  {
    "title": "Características de los Requerimientos",
    "eyebrow": "05 · Características",
    "body": "<div class=\"card\"><p>Los requisitos de un software suelen ser una <strong>combinación compleja</strong> de los requisitos de <strong>diferentes personas</strong> en diferentes niveles de una organización y del entorno en el cual operará el software.</p></div><div class=\"card-grid card-grid--2\" style=\"margin-top: 1rem;\"><div class=\"card card--num\"><span class=\"number\">01</span><p><strong>Verificable:</strong> es fundamental que un requisito pueda comprobarse.</p></div><div class=\"card card--num\"><span class=\"number\">02</span><p><strong>Prioridad:</strong> atributo que les caracteriza.</p></div><div class=\"card card--num\"><span class=\"number\">03</span><p><strong>Identificador único:</strong> atributo que les caracteriza.</p></div><div class=\"card card--num\"><span class=\"number\">04</span><p><strong>Claros y no ambiguos:</strong> lo más que se pueda.</p></div><div class=\"card card--num\"><span class=\"number\">05</span><p><strong>Cuantificables</strong> (si es posible).</p></div></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> Se presentan las características de los requerimientos: surgen de combinar necesidades de distintas personas, deben ser verificables, claros, no ambiguos y cuantificables, y llevan atributos como prioridad e identificador único. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): \"la operación se registra en menos de 2 segundos\" es verificable y cuantificable. Segundo contexto industrial: en un ERP, \"el sistema debe ser rápido\" no es verificable; \"responder en menos de 3 segundos\" sí. <br><br><strong>Reflexión docente:</strong> la verificabilidad es clave: un requerimiento que no se puede comprobar no se puede aceptar ni probar. <br><br><strong>Pregunta desafío:</strong> ¿cómo harían verificable el requerimiento \"el sistema debe ser fácil de usar\"? <br><br><strong>Respuestas posibles:</strong> 1. Definiendo métricas (tiempo de aprendizaje, tasa de error). 2. Con pruebas de usabilidad con usuarios. 3. Con criterios de aceptación concretos. <br><br><strong>Advertencia:</strong> la prioridad y el identificador único ayudan a gestionar cambios y trazabilidad."
  },
  {
    "title": "Tipos de Requerimientos",
    "eyebrow": "06 · Clasificación",
    "body": "<div class=\"card-grid card-grid--2\" style=\"gap: 2rem;\"><div class=\"card card--hero\"><h3>Requerimientos Funcionales</h3><p>Describen qué debe hacer el sistema.</p></div><div class=\"card card--hero\"><h3>Requerimientos No Funcionales</h3><p>Describen restricciones y calidad.</p></div></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> Se introduce la clasificación principal de los requerimientos: funcionales y no funcionales. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): funcional \"registrar una venta de divisas\"; no funcional \"el sistema debe operar sin interrupciones en horario de atención\". Segundo contexto industrial: en un hospital, funcional \"asignar cama\" y no funcional \"cumplir la ley de protección de datos\". <br><br><strong>Reflexión docente:</strong> ambos tipos son necesarios; centrarse solo en los funcionales deja el sistema inusable. <br><br><strong>Pregunta desafío:</strong> ¿cuál de los dos tipos se suele olvidar en proyectos reales? <br><br><strong>Respuestas posibles:</strong> 1. Los no funcionales, por ser menos visibles. 2. Los funcionales, cuando el cliente describe restricciones. 3. Depende de cada proyecto. <br><br><strong>Advertencia:</strong> esta clasificación se profundizará en los slides siguientes."
  },
  {
    "title": "Requerimientos Funcionales",
    "eyebrow": "07 · Funcionales",
    "body": "<div class=\"card\"><p>Se refiere a las <strong>capacidades del sistema</strong>.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p>Describen las <strong>funciones</strong> que lleva a cabo el software, cómo debe reaccionar ante ciertas entradas y cómo debe comportarse en situaciones particulares.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p>Describen la <strong>funcionalidad o los servicios</strong> que se espera que éste provea.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p>Son <strong>declaraciones de los servicios</strong> que proveerá el sistema, de la manera en que éste reaccionará a entradas particulares.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p>En algunos casos, los requerimientos funcionales de los sistemas también declaran explícitamente lo que el sistema <strong>NO debe hacer</strong>.</p></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> Se definen los requerimientos funcionales: capacidades del sistema, cómo reacciona ante entradas y cómo se comporta en situaciones particulares; también declaran lo que el sistema NO debe hacer. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): \"el sistema permite al operador registrar una transacción con monto, moneda origen y destino\". Segundo contexto industrial: en un sistema de préstamos, \"el sistema no permite aprobar un préstamo sin verificación de identidad\". <br><br><strong>Reflexión docente:</strong> los requerimientos funcionales describen servicios, no la implementación interna. <br><br><strong>Pregunta desafío:</strong> ¿\"el sistema usa una base de datos MySQL\" es un requerimiento funcional? <br><br><strong>Respuestas posibles:</strong> 1. No, es una decisión de diseño. 2. Podría ser una restricción técnica (no funcional). 3. Solo es funcional si describe un comportamiento observable. <br><br><strong>Advertencia:</strong> no mezclar requerimientos con soluciones tecnológicas."
  },
  {
    "title": "Ejemplos de Requerimientos Funcionales",
    "eyebrow": "08 · Ejemplos",
    "body": "<div class=\"card\"><p><strong>RF1.</strong> El sistema controlará el acceso y lo permitirá solamente a usuarios autorizados. Los usuarios deben ingresar al sistema con un nombre de usuario y contraseña.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>RF2.</strong> El campo país consistirá en una lista de preselección. El país asociado a una dirección debe ser previamente registrado en el sistema.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>RF3.</strong> El campo estado, provincia o departamento consistirá en una lista de preselección. A los usuarios se les presentará únicamente los departamentos asociados al país seleccionado previamente.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>RF4.</strong> El sistema enviará un correo electrónico cuando se registre alguna de las siguientes transacciones: pedido de venta de cliente, emisión de factura a cliente y registro de pago de cliente.</p></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> Se muestran cuatro ejemplos de requerimientos funcionales (RF1-RF4) para un sistema típico de comercio: control de acceso, país de preselección, departamentos por país y envío de correos por transacción. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): RF \"el sistema valida el usuario y contraseña del operador\"; RF \"el sistema registra el tipo de cambio aplicado en cada venta\". Segundo contexto industrial: en un sistema de facturación, los mismos patrones de RF1-RF4. <br><br><strong>Reflexión docente:</strong> los ejemplos muestran la redacción típica: \"el sistema + verbo + condición\". <br><br><strong>Pregunta desafío:</strong> ¿qué características comparten todos estos requerimientos? <br><br><strong>Respuestas posibles:</strong> 1. Están redactados en tercera persona. 2. Son verificables y específicos. 3. Describen una acción observable del sistema. <br><br><strong>Advertencia:</strong> no copiar estos ejemplos tal cual; adaptarlos al dominio de cada proyecto."
  },
  {
    "title": "Requerimientos No Funcionales",
    "eyebrow": "09 · No funcionales",
    "body": "<div class=\"card\"><p>Se refiere a las <strong>restricciones y requisitos de calidad</strong>.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p><strong>Restricciones sobre las funciones o servicios</strong> ofrecidos por el sistema. Incluyen restricciones de <strong>tiempo</strong>, sobre el <strong>proceso de desarrollo</strong>, <strong>estándares</strong>, etc.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p>Son aquellos requerimientos que <strong>no se refieren directamente</strong> a las funciones específicas que entrega el sistema, sino a las <strong>propiedades emergentes</strong> de éste como la fiabilidad, la respuesta en el tiempo y la capacidad de almacenamiento.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p>De forma alternativa, definen las <strong>restricciones del sistema</strong> como la capacidad de los dispositivos de entrada/salida y la representación de datos que se utiliza en la interface del sistema.</p></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> Se definen los requerimientos no funcionales: restricciones y requisitos de calidad (fiabilidad, tiempo de respuesta, capacidad de almacenamiento, restricciones de hardware y representación de datos). <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): \"el sistema debe responder una cotización en menos de 2 segundos\" o \"debe operar en horario continuo sin caídas\". Segundo contexto industrial: en un sistema de salud, \"los datos de pacientes deben estar cifrados\". <br><br><strong>Reflexión docente:</strong> los no funcionales afectan propiedades emergentes del sistema, no funciones puntuales. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre una restricción y un requisito de calidad? <br><br><strong>Respuestas posibles:</strong> 1. La restricción limita (hardware, estándares); la calidad define propiedades (rendimiento, fiabilidad). 2. Ambas son no funcionales. 3. Se complementan. <br><br><strong>Advertencia:</strong> los no funcionales son difíciles de cuantificar; conviene hacerlo cuanto antes."
  },
  {
    "title": "Requerimientos No Funcionales",
    "eyebrow": "10 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/requerimientos-no-funcionales.png\" alt=\"Clasificación de los requerimientos no funcionales: del producto, organizacionales y externos\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> Slide visual: se muestra el diagrama de la clasificación de los requerimientos no funcionales (producto, organizacionales y externos). <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): ubicamos cada ejemplo en el diagrama: tiempos de respuesta (producto), cumplimiento normativo (externo). Segundo contexto industrial: en un banco, privacidad (externo) y disponibilidad (producto). <br><br><strong>Reflexión docente:</strong> la imagen resume la clasificación y sirve de referencia durante toda la unidad. <br><br><strong>Pregunta desafío:</strong> ¿en qué categoría ubicarían \"el sistema debe usar estándares de la organización\"? <br><br><strong>Respuestas posibles:</strong> 1. Organizacionales. 2. De producto. 3. Externos. <br><br><strong>Advertencia:</strong> la clasificación es orientativa; algunos requisitos pueden pertenecer a más de una categoría."
  },
  {
    "title": "Ejemplos de Requerimientos No Funcionales",
    "eyebrow": "11 · Ejemplos",
    "body": "<div class=\"card\"><p><strong>Requerimientos del Producto</strong></p><p><strong>RNF1.</strong> La interfaz de usuario será implementada como HTML simple sin frames ni applets Java.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Requerimientos Organizacionales</strong></p><p><strong>RNF2.</strong> El proceso de desarrollo y los entregables serán conformes a lo establecido en METRICA v3.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Requerimientos Externos</strong></p><p><strong>RNF3.</strong> El sistema no registrará ninguna información personal de los clientes salvo su nombre y número de referencia, respetando lo establecido en la Ley Orgánica de Protección de Datos (LOPD).</p></div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> Se muestran ejemplos de requerimientos no funcionales organizados en tres grupos: del producto, organizacionales y externos (RNF1-RNF3). <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): RNF \"la interfaz del operador será HTML sin applets\"; RNF \"los entregables cumplirán la norma interna\"; RNF \"no se registrará información personal innecesaria\". Segundo contexto industrial: en un sistema de salud, RNF externo \"cumplir la ley de protección de datos (LOPD)\". <br><br><strong>Reflexión docente:</strong> los ejemplos muestran cómo la normativa y la organización condicionan el sistema. <br><br><strong>Pregunta desafío:</strong> ¿por qué un requerimiento externo puede ser obligatorio por ley? <br><br><strong>Respuestas posibles:</strong> 1. Porque violarlo implica sanciones. 2. Porque afecta a terceros (clientes, pacientes). 3. Porque limita qué datos se pueden almacenar. <br><br><strong>Advertencia:</strong> la LOPD y METRICA v3 son ejemplos concretos; cada proyecto tendrá su normativa."
  },
  {
    "title": "Ejemplo de Requerimientos",
    "eyebrow": "12 · Ejemplo",
    "body": "<img class=\"figure-img\" src=\"assets/ejemplo-requerimientos.jpg\" alt=\"Ejemplo ilustrado de requerimientos de software\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> Slide visual: se muestra un ejemplo ilustrado de requerimientos, sirviendo de apoyo para fijar el concepto. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): la imagen ilustra cómo se describe un requerimiento con su contexto. Segundo contexto industrial: aplicable a cualquier dominio de negocio. <br><br><strong>Reflexión docente:</strong> los recursos visuales ayudan a conectar la teoría con casos concretos. <br><br><strong>Pregunta desafío:</strong> ¿qué información necesitaría un desarrollador para implementar el ejemplo de la imagen? <br><br><strong>Respuestas posibles:</strong> 1. El requerimiento funcional preciso. 2. Las restricciones no funcionales. 3. Los criterios de aceptación. <br><br><strong>Advertencia:</strong> la imagen es ilustrativa; el contenido técnico se desarrolla en slides posteriores."
  },
  {
    "title": "¿Qué Es la Ingeniería de Requisitos?",
    "eyebrow": "13 · Definición",
    "body": "<div class=\"quote\">«Conjunto de actividades para descubrir, documentar y mantener un conjunto de requisitos.»</div><div class=\"quote\">«Establecer los servicios que el cliente requiere de un sistema y las restricciones bajo las cuales opera y es desarrollado.»</div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> Se define la Ingeniería de Requisitos como el conjunto de actividades para descubrir, documentar y mantener los requisitos, y para establecer los servicios y restricciones que el cliente requiere. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): la ingeniería de requisitos nos permite pasar de \"queremos cambiar divisas\" a un documento claro de servicios y restricciones. Segundo contexto industrial: en un ERP, definir qué módulos y bajo qué restricciones. <br><br><strong>Reflexión docente:</strong> la ingeniería de requisitos es la primera disciplina del proceso; de ella depende el resto. <br><br><strong>Pregunta desafío:</strong> ¿por qué se dice que los requisitos son la etapa más cara de corregir? <br><br><strong>Respuestas posibles:</strong> 1. Porque un error se propaga al diseño y código. 2. Porque corregirlo al final requiere rehacer varias etapas. 3. Porque involucra a muchas personas. <br><br><strong>Advertencia:</strong> mantener requisitos no es solo documentar: incluye actualizarlos y gestionar su evolución."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "14 · Proceso",
    "body": "<div class=\"quote\">«Conjunto estructurado de actividades de cuya ejecución se obtiene, valida y mantiene un documento de requisitos del sistema (ERS).»</div><p class=\"reference\">Sommerville, I. Ingeniería de Software, 9ª ed. Pearson, 2011.</p>",
    "note": "<strong>Desarrollo:</strong> Se define el proceso de la ingeniería de requerimientos como un conjunto estructurado de actividades de cuya ejecución se obtiene, valida y mantiene el documento de requisitos (ERS). <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): el proceso comienza con obtener qué necesita el cliente y termina con un ERS validado. Segundo contexto industrial: en un sistema de logística, el mismo flujo. <br><br><strong>Reflexión docente:</strong> el ERS es el artefacto central; todas las actividades convergen en él. <br><br><strong>Pregunta desafío:</strong> ¿qué significa que el ERS se \"valida y mantiene\"? <br><br><strong>Respuestas posibles:</strong> 1. Se confirma con el cliente y se actualiza ante cambios. 2. Es un documento vivo. 3. Deja de ser válido cuando cambian los requisitos. <br><br><strong>Advertencia:</strong> el proceso es iterativo, no una secuencia rígida."
  },
  {
    "title": "Participantes en el Proceso",
    "eyebrow": "15 · Participantes",
    "body": "<div class=\"card-grid card-grid--2\"><div class=\"card\"><h3>Cliente y Usuarios</h3><p>Conocen los requisitos adecuados a sus necesidades.</p></div><div class=\"card\"><h3>Diseñadores</h3><p>Comprender los requerimientos para lograr un diseño que los satisfaga.</p></div><div class=\"card\"><h3>Supervisores del Contrato</h3><p>Establecen los hitos de Control y cronogramas.</p></div><div class=\"card\"><h3>Gerentes del Negocio</h3><p>Entienden el impacto en la Organización.</p></div><div class=\"card\"><h3>Verificadores</h3><p>Comprender los requerimientos para poder verificar si el sistema los satisface.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan los participantes en el proceso de ingeniería de requerimientos: cliente y usuarios, diseñadores, supervisores del contrato, gerentes del negocio y verificadores, con el rol de cada uno. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): el cliente define las reglas de cambio; el diseñador las convierte en arquitectura; el supervisor fija hitos; el verificador comprueba el cumplimiento. Segundo contexto industrial: en un hospital, pacientes (usuarios), médicos (gerentes), auditores (verificadores). <br><br><strong>Reflexión docente:</strong> cada participante ve los requisitos desde su rol; la ingeniería de requisitos debe conciliar todas las visiones. <br><br><strong>Pregunta desafío:</strong> ¿qué pasa si un participante no participa del proceso? <br><br><strong>Respuestas posibles:</strong> 1. Se pierden requisitos importantes. 2. Se diseñan soluciones incorrectas. 3. La verificación falla. <br><br><strong>Advertencia:</strong> los verificadores necesitan entender los requisitos para poder comprobar si el sistema los satisface."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "16 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos: actividades en el nivel superior (planificación, obtención, análisis, especificación, verificación y validación) y artefactos en el nivel inferior (documento de visión, documento de requisitos, modelo del sistema y especificación de requisitos), con flechas de flujo y de generación de documentos\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> Slide visual: se muestra el diagrama del proceso de la ingeniería de requerimientos con sus actividades. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): localizamos en el diagrama dónde estamos: obtención, análisis, especificación, verificación y validación. Segundo contexto industrial: igual para cualquier dominio. <br><br><strong>Reflexión docente:</strong> la imagen es el mapa del proceso; conviene volver a ella en cada fase. <br><br><strong>Pregunta desafío:</strong> ¿qué actividad del diagrama les parece que se repite más veces? <br><br><strong>Respuestas posibles:</strong> 1. La obtención, porque aparecen nuevos requisitos. 2. La validación, por las revisiones con el cliente. 3. La gestión, por los cambios. <br><br><strong>Advertencia:</strong> el diagrama es una simplificación; en la práctica las actividades se solapan."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "17 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-obtencion.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de obtención resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> Slide visual de apoyo: se repite el diagrama del proceso para fijar la secuencia de actividades. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): se repasa el flujo de actividades con el ejemplo de las divisas. Segundo contexto industrial: aplicación a cualquier proyecto. <br><br><strong>Reflexión docente:</strong> la repetición del diagrama refuerza la memorización del proceso. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre este diagrama y el del slide anterior? <br><br><strong>Respuestas posibles:</strong> 1. Ninguna, es el mismo proceso. 2. Cambia el énfasis visual. 3. Se enfoca en otra actividad. <br><br><strong>Advertencia:</strong> son diapositivas de apoyo visual del mismo proceso."
  },
  {
    "title": "Obtención de Requerimientos: Fuentes",
    "eyebrow": "18 · Fuentes",
    "body": "<div class=\"card\"><p><strong>Fuente de los Requerimientos</strong></p></div><div class=\"card-grid card-grid--2\" style=\"margin-top: 1rem;\"><div class=\"card\"><p><strong>Cliente, usuario, otros interesados</strong> (necesidades).</p></div><div class=\"card\"><p><strong>Modelos del dominio</strong>.</p></div><div class=\"card\"><p><strong>Revisar la situación actual</strong>: organización actual y sistemas.</p></div><div class=\"card\"><p><strong>Versión actual del sistema</strong> y desarrolladores de versión anterior.</p></div><div class=\"card\"><p><strong>Documentos existentes</strong> (antecedentes).</p></div><div class=\"card\"><p><strong>Sistemas análogos ya existentes</strong> (antecedentes).</p></div></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan las fuentes de donde se obtienen los requerimientos: clientes y usuarios, modelos del dominio, la situación actual, la organización y sistemas existentes, la versión anterior y documentos o sistemas análogos. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): se consulta al cliente (reglas de cambio), al sistema actual (planillas manuales) y a sistemas análogos (casas de cambio existentes). Segundo contexto industrial: en un hospital, revisar el sistema de turnos actual y los registros en papel. <br><br><strong>Reflexión docente:</strong> cuantas más fuentes se consulten, menos requisitos se pierden. <br><br><strong>Pregunta desafío:</strong> ¿qué fuente suele aportar los requisitos más completos? <br><br><strong>Respuestas posibles:</strong> 1. Los usuarios reales. 2. Los sistemas análogos. 3. La documentación existente. <br><br><strong>Advertencia:</strong> no confiar en una única fuente; los usuarios no siempre conocen todos los requisitos."
  },
  {
    "title": "Obtención de Requerimientos: Técnicas",
    "eyebrow": "19 · Técnicas",
    "body": "<div class=\"card\"><p><strong>Técnicas de Obtención</strong></p></div><div class=\"card-grid card-grid--2\" style=\"margin-top: 1rem;\"><div class=\"card card--num\"><span class=\"number\">01</span><h3>Reuniones / Entrevistas</h3></div><div class=\"card card--num\"><span class=\"number\">02</span><h3>Cuestionarios</h3></div><div class=\"card card--num\"><span class=\"number\">03</span><h3>Observación</h3></div><div class=\"card card--num\"><span class=\"number\">04</span><h3>Brainstorming</h3></div></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan las técnicas de obtención de requerimientos: reuniones/entrevistas, cuestionarios, observación y brainstorming. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): entrevistas con el cliente para conocer las reglas de cambio; observación de cómo los operadores registran operaciones hoy; brainstorming para ideas de nuevas funciones. Segundo contexto industrial: en un sistema de logística, encuestas a repartidores y observación de rutas. <br><br><strong>Reflexión docente:</strong> cada técnica tiene ventajas; suelen combinarse. <br><br><strong>Pregunta desafío:</strong> ¿qué técnica conviene cuando los usuarios están dispersos geográficamente? <br><br><strong>Respuestas posibles:</strong> 1. Cuestionarios. 2. Entrevistas virtuales. 3. Observación remota. <br><br><strong>Advertencia:</strong> la observación directa revela lo que los usuarios hacen, no solo lo que dicen que hacen."
  },
  {
    "title": "Obtención de Requerimientos: Problemas Comunes",
    "eyebrow": "20 · Problemas",
    "body": "<div class=\"card\"><p><strong>Problemas Comunes</strong></p></div><div class=\"card-grid card-grid--2\" style=\"margin-top: 1rem;\"><div class=\"card card--num\"><span class=\"number\">01</span><p>No saben lo que quieren del sistema, sólo en términos generales; no conocen el costo de sus peticiones.</p></div><div class=\"card card--num\"><span class=\"number\">02</span><p>Los requisitos están en sus términos y con conocimiento implícito de su propio trabajo.</p></div><div class=\"card card--num\"><span class=\"number\">03</span><p>Distintos usuarios tienen distintos requisitos; se deben encontrar todas las fuentes.</p></div><div class=\"card card--num\"><span class=\"number\">04</span><p>Influyen factores políticos.</p></div><div class=\"card card--num\"><span class=\"number\">05</span><p>La prioridad que se da a los requisitos varía con el tiempo.</p></div><div class=\"card card--num\"><span class=\"number\">06</span><p>Aparecen nuevos requisitos.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan los problemas comunes en la obtención de requerimientos: usuarios que no saben qué quieren o no conocen el costo, requisitos implícitos, distintas fuentes con requisitos distintos, factores políticos, prioridades que cambian y nuevos requisitos que aparecen. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): el cliente pide \"cambiar divisas\" sin saber cuántas monedas ni qué márgenes; luego pide más monedas. Segundo contexto industrial: en un sistema de turnos, distintas áreas piden prioridades distintas. <br><br><strong>Reflexión docente:</strong> estos problemas son la razón de ser de la ingeniería de requisitos: ordenar el caos. <br><br><strong>Pregunta desafío:</strong> ¿cómo se mitiga que el usuario no conozca el costo de sus peticiones? <br><br><strong>Respuestas posibles:</strong> 1. Estimando el impacto de cada requisito. 2. Mostrando prototipos. 3. Negociando prioridades. <br><br><strong>Advertencia:</strong> los factores políticos existen y deben gestionarse, no ignorarse."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "21 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-analisis.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de análisis resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> Slide visual de apoyo: se repite el diagrama del proceso para situar la actividad de análisis. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): se ubica la obtención y el análisis dentro del flujo general. Segundo contexto industrial: igual para cualquier proyecto. <br><br><strong>Reflexión docente:</strong> el diagrama sirve de guía de navegación de la unidad. <br><br><strong>Pregunta desafío:</strong> ¿en qué etapa del diagrama nos encontramos ahora? <br><br><strong>Respuestas posibles:</strong> 1. Obtención. 2. Análisis. 3. Especificación. <br><br><strong>Advertencia:</strong> el avance por las etapas no es estrictamente secuencial."
  },
  {
    "title": "Análisis de Requerimientos",
    "eyebrow": "22 · Análisis",
    "body": "<div class=\"card-grid card-grid--2\"><div class=\"card card--num\"><span class=\"number\">01</span><p>Analizar <strong>stakeholders</strong> / clientes / usuarios.</p></div><div class=\"card card--num\"><span class=\"number\">02</span><p>Crear <strong>vistas</strong>.</p></div><div class=\"card card--num\"><span class=\"number\">03</span><p><strong>Detallar</strong> y <strong>negociar prioridades</strong>.</p></div><div class=\"card card--num\"><span class=\"number\">04</span><p>Buscar <strong>requerimientos que faltan</strong>.</p></div><div class=\"card card--num\"><span class=\"number\">05</span><p>Evaluar <strong>factibilidad técnica</strong> – prototipos.</p></div><div class=\"card card--num\"><span class=\"number\">06</span><p>Evaluar <strong>riesgos</strong> de requerimientos.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan las actividades del análisis de requerimientos: analizar stakeholders, crear vistas, detallar, negociar prioridades, buscar requerimientos que faltan, evaluar factibilidad con prototipos y evaluar riesgos. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): se negocia qué monedas se soportan en la primera versión; se crean vistas del sistema por rol. Segundo contexto industrial: en un ERP, priorizar módulos y evaluar riesgos de integración. <br><br><strong>Reflexión docente:</strong> el análisis transforma necesidades dispersas en requisitos organizados y priorizados. <br><br><strong>Pregunta desafío:</strong> ¿por qué son útiles los prototipos en el análisis? <br><br><strong>Respuestas posibles:</strong> 1. Porque aclaran lo que el usuario quiere. 2. Porque validan la factibilidad. 3. Porque reducen malentendidos. <br><br><strong>Advertencia:</strong> el análisis no es diseño; busca entender y organizar, no construir la solución."
  },
  {
    "title": "Análisis de Requerimientos: Modelos del Sistema",
    "eyebrow": "23 · Modelos",
    "body": "<div class=\"card\"><p><strong>Modelos o Vistas del Sistema</strong></p></div><div class=\"card-grid card-grid--2\" style=\"margin-top: 1rem;\"><div class=\"card\"><p>Glosario.</p></div><div class=\"card\"><p>Modelos gráficos y modelo conceptual.</p></div><div class=\"card\"><p>Diagramas de estado – para entidades complejas que pasen por distintos estados.</p></div><div class=\"card\"><p>Diagramas de Flujo de Datos (DFD).</p></div><div class=\"card\"><p>Prototipos de interfaz gráfica.</p></div><div class=\"card\"><p>Casos de Prueba y Tablas de Decisión.</p></div><div class=\"card\"><p>Casos de Uso.</p></div></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan los modelos o vistas del sistema usados en el análisis: glosario, modelos gráficos, modelo conceptual, diagramas de estado, DFD, prototipos de interfaz, casos de prueba, tablas de decisión y casos de uso. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): un caso de uso \"registrar venta de divisas\", un DFD del flujo de operaciones, un prototipo de la pantalla de cotización. Segundo contexto industrial: en un hospital, un diagrama de estado del turno (en espera, en atención, finalizado). <br><br><strong>Reflexión docente:</strong> cada vista muestra una faceta del sistema; ninguna es suficiente por sí sola. <br><br><strong>Pregunta desafío:</strong> ¿qué vista usarían para entender los estados de una entidad? <br><br><strong>Respuestas posibles:</strong> 1. Diagrama de estados. 2. DFD. 3. Tabla de decisión. <br><br><strong>Advertencia:</strong> estos modelos se estudian en profundidad en unidades posteriores."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "24 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-especificacion.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de especificación resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> Slide visual de apoyo: diagrama del proceso, situando la especificación. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): se ubica el análisis y la especificación en el flujo. Segundo contexto industrial: igual. <br><br><strong>Reflexión docente:</strong> el diagrama mantiene el contexto del recorrido. <br><br><strong>Pregunta desafío:</strong> ¿qué actividad sigue al análisis en el proceso? <br><br><strong>Respuestas posibles:</strong> 1. Especificación. 2. Verificación. 3. Obtención. <br><br><strong>Advertencia:</strong> es un apoyo visual; no introduce contenido nuevo."
  },
  {
    "title": "Especificación de Requerimientos: Documentación",
    "eyebrow": "25 · Documentación",
    "body": "<div class=\"card\"><p><strong>Qué documentar?</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><ul><li>Lo que hace el sistema actual.</li><li>Lo que el cliente pide.</li><li>Lo que el sistema va a hacer.</li><li>Criterios de aceptación.</li><li>Criterios de verificación.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Recomendaciones:</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><ul><li>Agrupar por temas.</li><li>Formular los requerimientos como requerimientos positivos y no negativos.</li><li>Expresarlos en voz activa y no pasiva.</li><li>Indicar si se está documentando solo lo que va en el alcance o todo lo que se pidió.</li><li>Representar requerimientos con múltiples vistas.</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan las pautas para documentar los requisitos: qué documentar (lo que hace el sistema actual, lo que pide el cliente, lo que hará, criterios de aceptación y verificación) y recomendaciones de redacción (agrupar por temas, requerimientos positivos, voz activa, indicar alcance y múltiples vistas). <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): documentar que hoy se registra en planillas, que el cliente pide un sistema web, y que el nuevo sistema registrará operaciones en línea con criterios de aceptación definidos. Segundo contexto industrial: en un sistema de inventario, igual. <br><br><strong>Reflexión docente:</strong> la documentación es la base del ERS; redactar bien ahorra malentendidos. <br><br><strong>Pregunta desafío:</strong> ¿por qué se recomienda formular requerimientos en positivo y en voz activa? <br><br><strong>Respuestas posibles:</strong> 1. Para reducir ambigüedad. 2. Para facilitar la verificación. 3. Para que el lector sepa exactamente qué hacer. <br><br><strong>Advertencia:</strong> indicar si se documenta solo el alcance o todo lo pedido evita falsas expectativas."
  },
  {
    "title": "Especificación de Requerimientos: Documento SRS",
    "eyebrow": "26 · Documento",
    "body": "<div class=\"card\"><p><strong>Documento de Especificación de requisitos</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><ul><li>Registrar los requisitos en los términos del cliente.</li><li>Delinear el propósito general del sistema: Incluir referencias a otros sistemas, glosario y abreviaciones.</li><li>Describir el contexto y objetivos del desarrollo del sistema.</li><li>Delinear visión global del sistema: Incluir restricciones generales.</li><li>Definir en detalle las características del sistema propuesto, definir el alcance del sistema e interfaces.</li><li>Discutir el ambiente en el que el sistema va a operar (hardware, comunicaciones, personal).</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan los contenidos del documento de especificación de requisitos (SRS): registrar en términos del cliente, propósito general, contexto, visión global, características del sistema, alcance, interfaces y ambiente de operación. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): el SRS describe el propósito (sistema de cambio de divisas en línea), contexto (operaciones del local), características (registrar, cotizar, liquidar) e interfaces (con el sistema contable). Segundo contexto industrial: en un hospital, el SRS del sistema de turnos describe hardware, comunicaciones y personal. <br><br><strong>Reflexión docente:</strong> el SRS es el contrato técnico entre cliente y desarrolladores. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre el propósito y la visión global del sistema? <br><br><strong>Respuestas posibles:</strong> 1. El propósito es el porqué; la visión, el qué general. 2. El propósito es corto; la visión, más detallada. 3. Ambos describen el sistema desde lo alto. <br><br><strong>Advertencia:</strong> el SRS se redacta en términos del cliente, sin tecnicismos innecesarios."
  },
  {
    "title": "Características de una Buena Especificación SRS (IEEE 830)",
    "eyebrow": "27 · SRS IEEE 830",
    "body": "<div class=\"card\"><p><strong>SRS (IEEE 830)</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Correcta / Válida:</strong></p><ul><li>Todos los requerimientos son requeridos en el sistema.</li><li>No existe herramienta que asegure esto.</li><li>Validado por el cliente (que efectivamente refleje sus necesidades).</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>No Ambigua:</strong></p><ul><li>Todo requerimiento tiene una única interpretación.</li><li>Incluir glosario.</li><li>No ambigua para quienes lo crearon y para quienes lo usan.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Completa:</strong> debe incluir:</p><ul><li>Todos los requisitos asociados con funcionalidad, desempeño, restricciones de diseño, atributos o interfaces externas.</li><li>Definición de respuestas del sw a todo posible dato de entrada (válidos o inválidos) en toda clase de situaciones realizables.</li><li>No hay referencias sin definir en la especificación.</li><li>La frase «a determinar» indica que el SRS no está completa. Ocasionalmente necesaria; describir: condiciones que causan que no se sepa aún y qué se debe hacer para determinar lo que falta, con quién y cuándo.</li></ul></div><p class=\"reference\">IEEE. IEEE Std 830-1998, Recommended Practice for Software Requirements Specifications. IEEE, 1998.</p>",
    "note": "<strong>Desarrollo:</strong> Se presentan las primeras características de una buena especificación SRS según IEEE 830: correcta/válida, no ambigua y completa, con detalle de cada una. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): un requisito es correcto si el cliente lo valida; no ambiguo si tiene una única interpretación; completo si no hay \"a determinar\" sin explicar. Segundo contexto industrial: en un sistema de turnos, validar con el cliente cada requisito. <br><br><strong>Reflexión docente:</strong> la completitud es difícil de lograr; requiere revisar funcionalidad, desempeño, restricciones e interfaces. <br><br><strong>Pregunta desafío:</strong> ¿qué implica que una especificación tenga la frase \"a determinar\"? <br><br><strong>Respuestas posibles:</strong> 1. Que no está completa. 2. Que falta definir un valor. 3. Que debe documentarse qué falta, con quién y cuándo se definirá. <br><br><strong>Advertencia:</strong> la correctitud no la garantiza ninguna herramienta; la valida el cliente."
  },
  {
    "title": "Características de una Buena Especificación SRS (IEEE 830)",
    "eyebrow": "28 · SRS IEEE 830",
    "body": "<div class=\"card\"><p><strong>SRS (IEEE 830)</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Consistente internamente:</strong> los requisitos no son contradictorios entre sí.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Ordenados por grado de importancia y/o estabilidad:</strong> los requisitos deben tener un identificador.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Verificable:</strong></p><ul><li>Un requerimiento es verificable si existe un proceso finito de costo accesible para determinar que el sistema lo cumple.</li><li>Usar términos concretos y cantidades mesurables.</li><li>Preparar pruebas para demostrar que se cumplen. Si no se puede, eliminar o revisar el requisito.</li><li>Expresar cada req. separadamente.</li></ul></div><p class=\"reference\">IEEE. IEEE Std 830-1998, Recommended Practice for Software Requirements Specifications. IEEE, 1998.</p>",
    "note": "<strong>Desarrollo:</strong> Se presentan más características del SRS según IEEE 830: consistente internamente, ordenada por importancia/estabilidad, y verificable, con sus implicaciones. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): \"el sistema responde en 2 segundos\" es verificable si existe una prueba; un requisito contradictorio con otro rompe la consistencia. Segundo contexto industrial: en un sistema de facturación, definir pruebas para cada requisito. <br><br><strong>Reflexión docente:</strong> la verificabilidad exige usar términos concretos y cantidades mesurables. <br><br><strong>Pregunta desafío:</strong> ¿qué se hace si un requisito no es verificable? <br><br><strong>Respuestas posibles:</strong> 1. Revisarlo o eliminarlo. 2. Preparar pruebas. 3. Reformularlo con métricas. <br><br><strong>Advertencia:</strong> ordenar por importancia facilita priorizar el desarrollo y los cambios."
  },
  {
    "title": "Características de una Buena Especificación SRS (IEEE 830)",
    "eyebrow": "29 · SRS IEEE 830",
    "body": "<div class=\"card\"><p><strong>SRS (IEEE 830)</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Trazables:</strong></p><ul><li>El origen de cada requerimiento es claro, y es posible seguirle la pista en futuros desarrollos o mejora de la documentación.</li><li>Trazabilidad hacia atrás: en versiones previas.</li><li>Trazabilidad hacia adelante: documentos posteriores.</li><li>Requiere IDENTIFICADOR ÚNICO.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Realistas / Factibles:</strong></p><ul><li>Ej.: tiempo de respuesta local = remoto.</li><li>Ej.: el cliente quiere adelantarse a la tecnología.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Entendibles:</strong> tanto por los usuarios como por los desarrolladores.</p></div><p class=\"reference\">IEEE. IEEE Std 830-1998, Recommended Practice for Software Requirements Specifications. IEEE, 1998.</p>",
    "note": "<strong>Desarrollo:</strong> Se presentan las últimas características del SRS según IEEE 830: trazables (hacia atrás y hacia adelante), realistas/factibles y entendibles. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): cada requisito tiene un identificador único que permite rastrear su origen y su implementación; \"tiempo de respuesta local = remoto\" puede no ser factible. Segundo contexto industrial: en un sistema de salud, trazar cada requisito a su normativa. <br><br><strong>Reflexión docente:</strong> la trazabilidad exige identificadores únicos desde el inicio. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre trazabilidad hacia atrás y hacia adelante? <br><br><strong>Respuestas posibles:</strong> 1. Hacia atrás: versiones previas; hacia adelante: documentos posteriores. 2. Una rastrea el origen; la otra la implementación. 3. Ambas requieren identificador único. <br><br><strong>Advertencia:</strong> los requisitos deben ser entendibles tanto por usuarios como por desarrolladores."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "30 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-verificacion.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de verificación resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> Slide visual de apoyo: diagrama del proceso, situando la verificación. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): se ubica la verificación dentro del flujo, tras la especificación. Segundo contexto industrial: igual. <br><br><strong>Reflexión docente:</strong> el diagrama mantiene el contexto. <br><br><strong>Pregunta desafío:</strong> ¿qué viene después de especificar en el proceso? <br><br><strong>Respuestas posibles:</strong> 1. Verificar. 2. Validar. 3. Gestionar. <br><br><strong>Advertencia:</strong> es un apoyo visual."
  },
  {
    "title": "Verificación de Requerimientos",
    "eyebrow": "31 · Verificación",
    "body": "<div class=\"card\"><p><strong>Se verifica en el documento de requisitos:</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><ul><li><strong>Consistencia:</strong> que no haya contradicciones.</li><li><strong>Completitud:</strong> que no falte nada. Chequear por: <em>Omisiones</em> (hacer árboles de decisión para ver que estén todas las opciones detalladas) y <em>Límites</em> (más claro con tabla, ahí se ve que no falta ninguno).</li><li><strong>Ambigüedades.</strong></li><li><strong>Realismo o Factibilidad:</strong> que se puedan implementar con la tecnología, presupuesto y calendario existentes.</li><li><strong>Verificabilidad:</strong> que se pueda diseñar un conjunto de pruebas para demostrar que el sistema cumple esos requisitos. Cuidado con adjetivos y adverbios.</li><li><strong>Comprensibilidad:</strong> que los usuarios finales lo entiendan.</li><li><strong>Adaptabilidad:</strong> que el requisito se pueda cambiar sin afectar a otros.</li><li><strong>Trazabilidad:</strong> que esté establecido el origen.</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan los criterios para verificar el documento de requisitos: consistencia, completitud (omisiones y límites), ambigüedades, realismo o factibilidad, verificabilidad, comprensibilidad, adaptabilidad y trazabilidad. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): verificar que no haya contradicciones entre las reglas de cambio; usar tablas para ver que no falten casos (límites); revisar que \"el sistema debe ser rápido\" sea reformulado con métricas. Segundo contexto industrial: en un sistema de turnos, árboles de decisión para cubrir todas las opciones. <br><br><strong>Reflexión docente:</strong> la verificación comprueba la calidad del documento, no que el sistema esté bien construido. <br><br><strong>Pregunta desafío:</strong> ¿qué se revisa con las tablas de decisión? <br><br><strong>Respuestas posibles:</strong> 1. Que no falten combinaciones (completitud). 2. Los límites. 3. Las ambigüedades. <br><br><strong>Advertencia:</strong> cuidado con adjetivos y adverbios en la verificación de requerimientos."
  },
  {
    "title": "Verificación de Requerimientos No Funcionales",
    "eyebrow": "32 · No funcionales",
    "body": "<img class=\"figure-img\" src=\"assets/verificacion-requerimientos.png\" alt=\"Verificación de los requerimientos no funcionales\" style=\"display: block; margin: 0 auto;\"><div class=\"card\" style=\"margin-top: 1rem;\"><p>Son <strong>difíciles de verificar</strong>.</p></div><div class=\"card\" style=\"margin-top: .5rem;\"><p>Se deben expresar de manera <strong>cuantitativa</strong> utilizando métricas que se puedan probar de forma objetiva (esto es IDEAL).</p></div><div class=\"card\" style=\"margin-top: .5rem;\"><p>Para los usuarios es <strong>difícil especificarlos</strong> en forma cuantitativa.</p></div>",
    "note": "<strong>Desarrollo:</strong> Se presenta la verificación de los requerimientos no funcionales: son difíciles de verificar, deben expresarse cuantitativamente con métricas objetivas (ideal) y a los usuarios les cuesta especificarlos en forma cuantitativa. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): \"el sistema debe ser confiable\" se reformula como \"disponibilidad del 99,9% anual\". Segundo contexto industrial: en un sistema de salud, \"los datos deben protegerse\" se reformula como \"cifrado AES-256\". <br><br><strong>Reflexión docente:</strong> cuantificar los no funcionales es difícil pero necesario para poder probarlos. <br><br><strong>Pregunta desafío:</strong> ¿cómo cuantificarían \"el sistema debe ser fácil de usar\"? <br><br><strong>Respuestas posibles:</strong> 1. Tiempo máximo de aprendizaje. 2. Tasa de error permitida. 3. Satisfacción en una escala. <br><br><strong>Advertencia:</strong> la cuantificación es lo ideal; si no se logra, al menos definir criterios de aceptación claros."
  },
  {
    "title": "Proceso de la Ingeniería de Requerimientos",
    "eyebrow": "33 · Diagrama",
    "body": "<img class=\"figure-img\" src=\"assets/proceso-ingenieria-requisitos-validacion.svg\" alt=\"Diagrama del proceso de ingeniería de requisitos con la actividad de validación resaltada\" style=\"display: block; margin: 0 auto;\">",
    "note": "<strong>Desarrollo:</strong> Slide visual de apoyo: diagrama del proceso, situando la validación. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): se ubica la validación tras la verificación. Segundo contexto industrial: igual. <br><br><strong>Reflexión docente:</strong> el diagrama mantiene el contexto del proceso. <br><br><strong>Pregunta desafío:</strong> ¿qué actividad sigue a la verificación? <br><br><strong>Respuestas posibles:</strong> 1. Validación. 2. Especificación. 3. Gestión. <br><br><strong>Advertencia:</strong> es un apoyo visual."
  },
  {
    "title": "Validación de Requerimientos",
    "eyebrow": "34 · Validación",
    "body": "<div class=\"card\"><p>Proceso por el cual se determina si la <strong>especificación</strong> es consistente con las <strong>necesidades del cliente</strong>.</p></div><div class=\"card\" style=\"margin-top: 1rem;\"><p><strong>Se verifica en el documento de requisitos:</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><ul><li><strong>Validez:</strong> que el usuario valide qué es lo que quiere.</li><li>Planificar quién (qué stakeholder) va a validar qué artefacto y cómo (técnica).</li><li>Registrar – Reporte de validación / Firma.</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> Se define la validación de requerimientos: proceso por el cual se determina si la especificación es consistente con las necesidades del cliente; incluye validez, planificar quién valida qué artefacto y cómo, y registrar un reporte de validación con firma. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): el cliente valida que el SRS refleja las reglas de cambio que realmente necesita y firma el reporte. Segundo contexto industrial: en un hospital, cada stakeholder valida los artefactos que le conciernen. <br><br><strong>Reflexión docente:</strong> la validación es con el cliente; la verificación es contra el documento. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia hay entre verificar y validar? <br><br><strong>Respuestas posibles:</strong> 1. Verificar: el sistema cumple la especificación; validar: la especificación satisface al cliente. 2. Verificar es interno; validar es con el usuario. 3. Ambas son complementarias. <br><br><strong>Advertencia:</strong> la firma del reporte de validación compromete a las partes."
  },
  {
    "title": "Validación de Requerimientos: Revisiones",
    "eyebrow": "35 · Revisiones",
    "body": "<div class=\"card\"><p><strong>Proceso manual:</strong> se revisa el documento de requisitos buscando anomalías y omisiones.</p><ul><li><strong>Revisiones informales:</strong> discusión informal.</li><li><strong>Revisiones formales:</strong> se hace una «recorrida» del doc. de req. con el cliente, explicando implicancias de cada requisito.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Participan representantes:</strong></p><ul><li><strong>Del cliente:</strong> operadores, quienes realicen entradas, utilicen salidas, y sus gerentes.</li><li><strong>Del equipo de desarrollo:</strong> analistas de requisitos, diseñadores, encargados de pruebas y gestión de configuración.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Incluye:</strong></p><ul><li>Revisar objetivos del sistema.</li><li>Evaluar alineamiento de requisitos con los objetivos (necesidad).</li><li>Revisar el ambiente de operación y las interfaces con otros sistemas.</li><li>Funciones completas, restricciones realistas.</li><li>Evaluar riesgos.</li></ul></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Considerar:</strong> pruebas del sistema y cambios en los requisitos en el proyecto, su verificación y validación.</p></div>",
    "note": "<strong>Desarrollo:</strong> Se presenta la validación como proceso manual: revisiones informales y formales (recorrida del documento con el cliente), con participantes del cliente y del equipo de desarrollo, incluyendo revisión de objetivos, alineamiento, ambiente, funciones, restricciones y riesgos. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): una recorrida del SRS con el cliente explicando implicancias de cada requisito; participan el analista, el diseñador y los encargados de pruebas. Segundo contexto industrial: en un sistema de facturación, revisar objetivos y alineamiento con la normativa. <br><br><strong>Reflexión docente:</strong> la recorrida formal es una técnica efectiva para detectar anomalías tempranamente. <br><br><strong>Pregunta desafío:</strong> ¿qué se busca al evaluar la alineación de requisitos con los objetivos? <br><br><strong>Respuestas posibles:</strong> 1. Que cada requisito responda a una necesidad. 2. Que no haya requisitos innecesarios. 3. Que el alcance sea correcto. <br><br><strong>Advertencia:</strong> la validación debe considerar las pruebas del sistema y los cambios en los requisitos."
  },
  {
    "title": "Gestión de Requerimientos",
    "eyebrow": "36 · Gestión",
    "body": "<div class=\"card\"><p>Proceso de <strong>comprender y controlar</strong> los cambios en los requisitos del sistema; se hace <strong>en paralelo</strong> con el Proceso de Requisitos.</p></div><div class=\"card\" style=\"margin-top: .8rem;\"><p><strong>Los requisitos cambian, debido a:</strong></p></div><div class=\"card\" style=\"margin-top: .5rem;\"><ul><li>Muchos usuarios.</li><li>Quienes pagan por el sistema y los usuarios no son las mismas personas.</li><li>Cambios en el negocio.</li><li>Cambios en la tecnología.</li></ul></div><div class=\"card\" style=\"margin-top: .8rem;\"><p><strong>Tres etapas:</strong></p><ul><li><strong>Planificación:</strong> se realiza al comenzar el análisis de requisitos.</li><li><strong>Administración del cambio:</strong> comienza una vez que se tiene una primera versión del documento de requisitos.</li><li><strong>Trazabilidad:</strong> se mantiene a lo largo del proceso de requisitos.</li></ul></div>",
    "note": "<strong>Desarrollo:</strong> Se presenta la gestión de requerimientos: comprender y controlar los cambios; se hace en paralelo con el proceso de requisitos; los cambios surgen por muchos usuarios, diferencias entre quien paga y quien usa, cambios de negocio y de tecnología; tiene tres etapas: planificación, administración del cambio y trazabilidad. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): el cliente pide nuevas monedas; se administra el cambio evaluando su impacto y se actualiza la trazabilidad. Segundo contexto industrial: en un sistema de inventario, cambios por nueva normativa. <br><br><strong>Reflexión docente:</strong> la gestión evita que los cambios descontrolados destruyan el proyecto. <br><br><strong>Pregunta desafío:</strong> ¿por qué los cambios son inevitables en los proyectos de software? <br><br><strong>Respuestas posibles:</strong> 1. Porque el negocio y la tecnología cambian. 2. Porque los usuarios descubren nuevas necesidades. 3. Porque quien paga no siempre es quien usa. <br><br><strong>Advertencia:</strong> la trazabilidad se mantiene a lo largo de todo el proceso, no solo al final."
  },
  {
    "title": "Gestión de Requerimientos: Herramientas",
    "eyebrow": "37 · Herramientas",
    "body": "<div class=\"card\"><p><strong>JIRA:</strong> herramienta de gestión de proyectos ampliamente utilizada que también ofrece funcionalidades para la gestión de requerimientos. Permite la creación de historias de usuario, tareas, epics y otras unidades de trabajo, así como la asignación de prioridades, seguimiento de estado y colaboración en equipo.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Trello:</strong> herramienta de gestión de proyectos basada en tableros visuales que puede adaptarse para la gestión de requerimientos de software. Permite la creación de tarjetas para representar requerimientos, listas para organizarlos y tableros para visualizar el flujo de trabajo y el progreso del proyecto.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Confluence:</strong> plataforma de colaboración que también puede utilizarse para la gestión de requerimientos. Permite la creación de documentación estructurada, incluyendo especificaciones de requerimientos, casos de uso y otros artefactos.</p></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>GitHub Issues:</strong> herramienta de seguimiento de problemas integrada en la plataforma de desarrollo colaborativo GitHub. Permite la creación y seguimiento de problemas, bugs y mejoras, y puede ser utilizada para gestionar los requerimientos de software.</p></div>",
    "note": "<strong>Desarrollo:</strong> Se presentan herramientas para la gestión de requerimientos: JIRA (historias de usuario, tareas, épicas, prioridades), Trello (tableros visuales), Confluence (documentación estructurada) y GitHub Issues (seguimiento de problemas y mejoras). <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): usar JIRA para las historias de usuario del sistema de divisas, Confluence para el SRS y GitHub Issues para bugs. Segundo contexto industrial: en un ERP, Trello para el flujo de trabajo y Confluence para la especificación. <br><br><strong>Reflexión docente:</strong> las herramientas apoyan la gestión, pero no reemplazan el proceso. <br><br><strong>Pregunta desafío:</strong> ¿qué herramienta usarían para documentar la especificación SRS? <br><br><strong>Respuestas posibles:</strong> 1. Confluence. 2. JIRA. 3. GitHub Issues. <br><br><strong>Advertencia:</strong> la elección de herramienta depende de la organización; lo importante es el proceso."
  },
  {
    "title": "Ejemplos de Requerimientos",
    "eyebrow": "38 · Ejemplos",
    "body": "<div class=\"card\"><p><strong>Requerimientos funcionales:</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><a href=\"http://www.pmoinformatica.com/2017/02/requerimientos-funcionales-ejemplos.html\">http://www.pmoinformatica.com/2017/02/requerimientos-funcionales-ejemplos.html</a></div><div class=\"card\" style=\"margin-top: .6rem;\"><p><strong>Requerimientos no funcionales:</strong></p></div><div class=\"card\" style=\"margin-top: .6rem;\"><a href=\"http://www.pmoinformatica.com/2015/05/requerimientos-no-funcionales-ejemplos.html\">http://www.pmoinformatica.com/2015/05/requerimientos-no-funcionales-ejemplos.html</a></div>",
    "note": "<strong>Desarrollo:</strong> Se comparten referencias web con ejemplos de requerimientos funcionales y no funcionales para ampliar la práctica. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): usar los ejemplos de la referencia para redactar requerimientos del sistema de divisas. Segundo contexto industrial: adaptar los ejemplos a cualquier dominio. <br><br><strong>Reflexión docente:</strong> los ejemplos externos complementan la teoría con casos reales. <br><br><strong>Pregunta desafío:</strong> ¿qué diferencia encontraron entre los ejemplos funcionales y no funcionales de las referencias? <br><br><strong>Respuestas posibles:</strong> 1. Los funcionales describen acciones; los no funcionales, restricciones. 2. Los no funcionales son más difíciles de cuantificar. 3. Ambos son necesarios. <br><br><strong>Advertencia:</strong> las referencias son externas; verificar su vigencia."
  },
  {
    "title": "Muchas Gracias",
    "eyebrow": "39 · Cierre",
    "body": "<div class=\"card card--hero\"><h2 style=\"color:var(--fpuna-blue);\">PREGUNTAS</h2></div>",
    "note": "<strong>Desarrollo:</strong> Cierre de la unidad: se agradece y se abre el espacio de preguntas. <br><br><strong>Ejemplos:</strong> Global Exchange (conductor): repaso rápido de cómo definimos los requerimientos del sistema de cambio de divisas. Segundo contexto industrial: aplicación de lo aprendido a cualquier proyecto. <br><br><strong>Reflexión docente:</strong> la unidad sienta las bases para el diseño y desarrollo posteriores. <br><br><strong>Pregunta desafío:</strong> ¿qué concepto de la unidad les resultó más útil y por qué? <br><br><strong>Respuestas posibles:</strong> 1. La diferencia entre funcionales y no funcionales. 2. La verificación vs. validación. 3. La gestión de cambios. <br><br><strong>Advertencia:</strong> cierre de la unidad; no se introducen contenidos nuevos."
  }
];

// ─── Renderizado ──────────────────────────────────────────────
const stage = document.getElementById('stage');
const counter = document.getElementById('counter');
const previousBtn = document.getElementById('previous');
const nextBtn = document.getElementById('next');
const notes = document.getElementById('speaker-notes');
const indexNav = document.getElementById('slide-index');
let current = 0;

function slideMarkup(slide, index) {
 return `<div class="slide" data-slide="${index}">
 <header class="slide-header">
 <span class="eyebrow">${slide.eyebrow}</span>
 <h1 id="slide-title">${slide.title}</h1>
 </header>
 <div class="content">${slide.body}</div>
 </div>`;
}

function buildIndex() {
 indexNav.innerHTML = slides.map((slide, i) => {
 return `<button class="index-item" data-slide="${i}" aria-label="Ir a slide ${i + 1}: ${slide.title}">
 <span class="index-num">${String(i + 1).padStart(2, '0')}</span>
 <span class="index-title">${slide.title}</span>
 </button>`;
 }).join('');
 indexNav.addEventListener('click', (e) => {
 const btn = e.target.closest('.index-item');
 if (btn) {
 goTo(parseInt(btn.dataset.slide, 10));
 togglePanel('index-panel', false);
 }
 });
}

function goTo(index) {
 if (index < 0 || index >= slides.length) return;
 current = index;
 const slide = slides[current];
 stage.innerHTML = slideMarkup(slide, current);
 counter.textContent = `${String(current + 1).padStart(2, '0')} / ${String(slides.length).padStart(2, '0')}`;
 previousBtn.disabled = current === 0;
 nextBtn.disabled = current === slides.length - 1;
 const progress = document.querySelector('#progress');
 progress.style.width = `${((current + 1) / slides.length) * 100}%`;
 progress.setAttribute('aria-valuenow', current + 1);
 notes.innerHTML = `<div class="note"><strong>Slide ${current + 1}: ${slide.title}</strong><p>${slide.note}</p></div>`;
 document.querySelectorAll('.index-item').forEach((button, i) => button.classList.toggle('active', i === current));
 history.replaceState(null, '', `#slide-${current + 1}`);
}

function renderAllForPrint() {
 const total = slides.length;
 stage.innerHTML = slides.map((slide, position) => {
 const pageNum = String(position + 1).padStart(2, '0');
 const totalNum = String(total).padStart(2, '0');
 const header = `<div class="print-header"><div class="print-header-left"><img class="print-header-logo" src="assets/fpuna_logo_institucional.svg" alt="Logo FP-UNA"><div class="print-header-text"><span class="print-header-title">Ingeniería del Software I</span><span class="print-header-subtitle">FP-UNA / Licenciatura en Ciencias Informáticas (LCiK)</span></div></div><span class="print-header-page">${pageNum} / ${totalNum}</span></div>`;
 return `<div class="print-slide">${header}${slideMarkup(slide, position)}</div>`;
 }).join('');
 fitSlidesForPrint();
}

function fitSlidesForPrint() {
 const PAGE_W = 1123;
 const PAGE_H = 631;
 const HEADER_H = 56;
 const PADDING_SIDE = 56, PADDING_TOP = 10, PADDING_BOTTOM = 32;
 const probe = document.createElement('div');
 probe.style.cssText = `position:absolute;visibility:hidden;width:${PAGE_W - PADDING_SIDE * 2}px;`;
 document.body.appendChild(probe);
 document.querySelectorAll('.print-slide').forEach(slide => {
 const inner = slide.querySelector('.slide');
 if (!inner) return;
 probe.innerHTML = '';
 probe.appendChild(inner.cloneNode(true));
 const fullH = probe.scrollHeight;
 const availH = PAGE_H - HEADER_H - PADDING_TOP - PADDING_BOTTOM;
 if (fullH > availH) {
 const scale = availH / fullH;
 inner.style.transform = `scale(${scale})`;
 inner.style.transformOrigin = 'top left';
 inner.style.width = `${(PAGE_W - PADDING_SIDE * 2) / scale}px`;
 }
 });
 document.body.removeChild(probe);
}

function togglePanel(id, force) {
 const panel = document.getElementById(id);
 const isOpen = force !== undefined ? force : !panel.classList.contains('open');
 panel.classList.toggle('open', isOpen);
 panel.setAttribute('aria-hidden', String(!isOpen));
 const toggleBtn = document.getElementById(id.replace('-panel', '-toggle'));
 if (toggleBtn) toggleBtn.setAttribute('aria-expanded', String(isOpen));
 if (isOpen) panel.querySelector('button, [href]')?.focus();
}

previousBtn.addEventListener('click', () => goTo(current - 1));
nextBtn.addEventListener('click', () => goTo(current + 1));
document.getElementById('index-toggle').addEventListener('click', () => togglePanel('index-panel'));
document.getElementById('notes-toggle').addEventListener('click', () => togglePanel('notes-panel'));
document.querySelectorAll('.close-panel').forEach(btn => {
 btn.addEventListener('click', () => togglePanel(btn.dataset.close, false));
});

document.addEventListener('keydown', (e) => {
 if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') { e.preventDefault(); goTo(current - 1); }
 if (e.key === 'ArrowRight' || e.key === 'ArrowDown' || e.key === ' ') { e.preventDefault(); goTo(current + 1); }
 if (e.key === 'Home') { e.preventDefault(); goTo(0); }
 if (e.key === 'End') { e.preventDefault(); goTo(slides.length - 1); }
 if (e.key === 'f' || e.key === 'F') {
 if (!document.fullscreenElement) document.documentElement.requestFullscreen();
 else document.exitFullscreen();
 }
 if (e.key === 'i' || e.key === 'I') togglePanel('index-panel');
 if (e.key === 'n' || e.key === 'N') togglePanel('notes-panel');
 if (e.key === 'Escape') {
 togglePanel('index-panel', false);
 togglePanel('notes-panel', false);
 }
});

document.getElementById('fullscreen').addEventListener('click', () => {
 if (!document.fullscreenElement) document.documentElement.requestFullscreen();
 else document.exitFullscreen();
});

const hashMatch = location.hash.match(/#slide-(\d+)/);
const startSlide = hashMatch ? parseInt(hashMatch[1], 10) - 1 : 0;

window.addEventListener('beforeprint', () => { renderAllForPrint(); });
window.addEventListener('afterprint', () => { stage.innerHTML = ''; goTo(current); });

buildIndex();
goTo(Math.min(startSlide, slides.length - 1));
